### ISSUE TITLE
Translation management system

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#100]
Related to #21 .

I'd like to use Weblate for this, works well and allows anyone to easily contribute translations.

https://weblate.org

**Comment by SamMousa** [comment]
I have sent the an email to them asking for an account for open source use.

**Comment by SamMousa** [comment]
I have set up weblate here: https://weblate.whoapp.org/

@patniemeyer let me know when you have integrated react-intl and i'll look at automating weblate import & export.

**Comment by ivancastrogw1** [comment]
Happy to help with this topic I spoke with Anika Raghuvanshi  and I'll take the translations to Spanish and German also I'll like to begin to implement the translation pipes in the text we have available can you create a task in the kanban board?

**Comment by myiremark** [comment]
decision: lingo24

**Comment by comradekingu** [comment]
@myiremark Use https://hosted.weblate.org
Inhouse translation doesn't cut it.
