### ISSUE TITLE
Allow Efficient targeting of notifications to whole countries

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1000]
Current notification system does not efficiently allow us to target large regions for notifications.  We would have to run a query against Clients' location fields and then send batch notifications programmatically (which can only be sent approximately 1000 at a time).

Instead, we should use the feature built for such purpose: FCM topics.  On both `/putDeviceToken` AND `/putLocation`, we should subscribe the given FCM token for topics if both a token and location are at that time available.  The suggested topics to register for are:
```
LOCATION/$country
LOCATION/$country/$adminArea1 if adminArea1 not empty
LOCATION/$country/$adminArea1/$adminArea2 if adminArea2 not empty
LOCATION/$country/$adminArea1/$adminArea2/$adminArea3 if adminArea3 not empty
LOCATION/$country/$adminArea1/$adminArea2/$adminArea3/$adminArea4 if adminArea4 not empty
LOCATION/$country/$adminArea1/$adminArea2/$adminArea3/$adminArea4/$adminArea5 if adminArea5 not empty
LOCATION/$country/$adminArea1/$adminArea2/$adminArea3/$adminArea4/$adminArea5/$locality if locality not empty
```

* Note we must scrub these location fields as they are controlled by the user.  Any forward slashes in the names should be encoded as something else.
* The `LOCATION/` prefix gives us some namespaces for future non-location based topics.
* When `/putLocation` is called when a prior location exists in datastore, the client must be unregistered from its old location-based topics.
* App version and platform-based targeting are built-in to FCM.

cc @cbgrey @crazybob

**Comment by epicfaace** [comment]
The structure you proposed sounds good. Would we ever want targeting based on latitude-longitude-radius? I'm thinking if we have an alert or something that regards, say, the border of two countries.

**Comment by crazybob** [comment]
Good idea, Advay.

We should probably geocode on the server in putLocation as it would be more secure than trusting information from the client...

Ashwin, we can already efficiently target regions of any shape and size based on lat/lon. Just requires a bit of coding.

**Comment by advayDev1** [comment]
SG. I think the revised flow is:
1. Client: Get device GPS
2. Client: Reverse geocode the GPS to a locality
3. Client: Calls putLocation with the locality info (but no GPS)
4. Server: Geocode the locality back to a GPS (store both the locality info and GPS)
5. Server: Register topics with FCM if token and location available.

a. Right now both 2 and 4 are done on the client but I agree it would be safer to do 4 in the server.
b. This also ensures our servers continue to never see the exact GPS, while reducing the risk of junk info being stored in our server.
c. To a lesser degree, it could reduce GMaps api fees by caching the locality -> GPS geocoding (unlikely but possible).

This bug will cover topic registration.  I've adjusted #953 to reflect that the client should solely reverse geocode and filed

**Comment by advayDev1** [comment]
In v1, we will punt on FCM topics.  We will have to query the datastore based on rough s2 cell ids as needed.

**Comment by advayDev1** [comment]
This is now back to a required v1 feature.

**Comment by cbgrey** [comment]
On the description above I'm unclear on what "adminArea" is. How will the client know what adminArea to register for?

**Comment by advayDev1** [comment]
The client no longer sends any location info except a L9 S2 cell id (somewhere between 100 and 400 km2 area).

It is the server’s responsibility to rev geocode from that info to the appropriate areas.

adminArea1 in the US is state, and adminArea2 is the county for example

**Comment by advayDev1** [comment]
Per decision log we will solely target by country for v1.
