### ISSUE TITLE
Publish final Terms of Service

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1002]

**Comment by purpledrosophila** [comment]
If there's anything I can do to help with this or the terms, please let me know. I put those two files in docs/legal.

**Comment by advayDev1** [comment]
Yes - thank you @purpledrosophila - once attorneys have finalized the words, we can update the markdown version.

**Comment by purpledrosophila** [comment]
Great, keep me posted. :)

**Comment by brunobowden** [comment]
Folded in to #1001
