### ISSUE TITLE
missing touch feedback on items in 'Questions & Answers' and 'News & Press' screens

### ISSUE THREAD

**Issue by kassim** [WorldHealthOrganization/app#1009]
when I tap any of the items there is no ripple effect like there is for when you tap buttons elsewhere

--

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
They aren't really any button visual affordances on them as it stands.
@davidkaneda what are your thoughts here?

**Comment by davidkaneda** [comment]
Think a list row should be enough, especially if there's a chevron/icon on the right — Would just add the ripple to the row if it's easy (also probably better for accessibility if they're buttons)

**Comment by darish** [comment]
I added a PR to fix this issue. See it here. 

https://github.com/WorldHealthOrganization/app/pull/1034

 @advayDev1 Please approve.
