### ISSUE TITLE
CI to measure app binary size changes + gate large increases

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1013]
Automated build should common on every PR, listing the change in binary size. It should then automatically block the PR if it's beyond a certain size increase (e.g. 10K). As some increases will inevitably be larger, e.g. new image assets, a workaround will be needed, either acknowledgement in the PR or maybe a special reviewer who focuses on the app binary size.

Should be done in conjunction with #1014 to reduce the app binary sizes

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
FYI @SamMousa @advayDev1 @hspinks

**Comment by epicfaace** [comment]
We could use something fancy like [Diffuse](https://github.com/JakeWharton/diffuse) to compare APKs / aabs for Android https://levelup.gitconnected.com/diffusing-your-apk-ea9d044d4c0d

**Comment by Mastersam07** [comment]
I could send a PR that adds diffuse to the GitHub workflow to compare the apks on pull request if that is okay.

**Comment by advayDev1** [comment]
Thanks @Mastersam07 !

I’m just the person who added the `help wanted` label :)

Send out a PR, and @epicfaace @hspinks and I will review it.

**Comment by Mastersam07** [comment]
Sent a PR #1189
