### ISSUE TITLE
User feedback system in app

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1015]
The app should have a built in user feedback system. At our scale, we'll need to collate feedback rather than accept individual emails. 
* User feedback on any screen (e.g. shake or screenshot to initiate feedback)
* Automatically bundle device info in user feedback + other analytics
* Feature suggestions
* Possibly other features

We will need to be very careful about user privacy and ideally automatically block out anything sensitive before transmission. If we're using a third party service, then that will need additional consideration.

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
Think we're still targeting #989 if possible in v1

**Comment by hspinks** [comment]
Closing in favor of #1180
