### ISSUE TITLE
l10n code generation as part of CI

### ISSUE THREAD

**Issue by kassim** [WorldHealthOrganization/app#1019]
At the moment, l10n code is generated by a Flutter Intl IDE plugin (for IntelliJ or VS Code). This means it depends on a contributor having the correct plugin installed and the IDE opened when/after new strings are added, and it also requires generated code to be committed. 

As a better solution, we can include the dart plugin (by the same author as the IDE Plugin) that can be run as part of the build. https://pub.dev/packages/intl_utils

@clementmouchet @sapte91 have you used the IDE plugin over the Dart plugin for a particular reason or do you think this suggestion makes sense to move to?

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by hspinks** [comment]
cc @patniemeyer

**Comment by clementmouchet** [comment]
Hi @kassim,

I absolutely agree we shouldn't rely on the IDE plugins. I am using IntelliJ IDEA and the plugin to generate the code but I'd rather we leave the code generation to the build process (and possibly out of VCS) so it's just done at build time. 
This way developers would benefit from the instant updates from their IDE, but the diff in PRs would be must easier to look at.
