### ISSUE TITLE
Share the App doesn't work on iPad

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1020]
Click Share the App on iPad.
Nothing happens.

**Comment by hspinks** [comment]
@cbgrey GitHub won't let me assign you, would you mind commenting on this? I think that lets me assign you

**Comment by cbgrey** [comment]
I can take this one.

**Comment by pwicherski** [comment]
@cbgrey Just to let you know, quick test:
app version: 0.6.1 
iPad mini 2
iOS 12.4.5

🟢 Share the app works fine.

**Comment by advayDev1** [comment]
0.6.1(11), iPad Pro 11in, iOS 13.3.1

Does not work.

**Comment by britannio** [comment]
https://github.com/flutter/flutter/issues/47220#issuecomment-608453383

**Comment by advayDev1** [comment]
Thanks.  Btw this causes reproducible lock ups for me on iPad Pro.  Not crashes (so far).

**Comment by cbgrey** [comment]
PR submitted. Thank you for the research @britannio . Huge help.
