### ISSUE TITLE
Rename dynamically-loaded assets to avoid naming collisions

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#1029]
See https://github.com/WorldHealthOrganization/app/pull/1022#discussion_r407580934

---
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
Asset names should be scoped to their screen
