### ISSUE TITLE
v0.1 Illustration Issues

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#103]
Issues raised during Eng/Design flow review:
- The WHO-owned Protect Yourself  assets have text baked into the images. [localization and accessibility]
- Current WHO illustrations used in the v0.1 flow may be licensed in a way that is incompatible with our app. [legal]
- We have only CDC and no WHO-approved Check Your Health assets.
- Lack of illustrator resources.

**Comment by viviancromwell** [comment]
@advayDev1 there are multiple tickets to address the issues you raised separately, so I will be closing this one. thank you so much.
