### ISSUE TITLE
Pagination and Next fact button UI is overlapping content in split screen

### ISSUE THREAD

**Issue by mohit0208** [WorldHealthOrganization/app#1033]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

![NextFact_Pagination_UI_Issue](https://user-images.githubusercontent.com/21996559/79214929-b49b5a00-7e68-11ea-9924-a403f375098d.png)

**Comment by Mohit020888** [comment]
Steps to reproduce : 
1. Launch the app and complete onboarding/permissions.
2. Tap on Get the Facts.
3. Split the screen and observe the UI.

Pagination and Next fact button UI are overlapping the screen text as shown in the screen shot.

**Comment by Mohit020888** [comment]
![MotoX4_Android_9 0](https://user-images.githubusercontent.com/63721227/79590582-db6dc080-80f4-11ea-9566-93da78ac6098.png)

**Comment by advayDev1** [comment]
This UI button no longer exists - please re-verify with HEAD build.

**Comment by Mohit020888** [comment]
I tested on version 0.7.1 which QA got through Firebase app distribution.
Going forward will the testers get latest android build from Firebase or should we clone the code repository in our local and generate the build on our own?

**Comment by Mohit020888** [comment]
Retested on HEAD build version 0.8.0(15) on Huawei Honor 7c (Android 8.0)
The next fact UI button is no longer present but now the user cannot access Learn More button functionality on any of the Get The Facts screen under split screen mode.
![GetTheFacts_SplitScreen](https://user-images.githubusercontent.com/63721227/80934616-a6e15080-8de6-11ea-9c53-aa4b41d5e68f.jpg)
![GetTheFacts_SplitScreen_LearnMore_Isue](https://user-images.githubusercontent.com/63721227/80934623-b365a900-8de6-11ea-8ccc-6c66304c6fd9.gif)
