### ISSUE TITLE
Deploy to Staging Firebase App Distribution via CI

### ISSUE THREAD

**Issue by kassim** [WorldHealthOrganization/app#1044]
At the moment Android test builds are being sent to Firebase manually. It would be good to be executed via CI. Fastlane likely has support for this.

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
FYI @joshdholtz @crazybob @augustinreille
