### ISSUE TITLE
Localize source string on Latest Numbers screen

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#1047]
Remove hard-coded string in favor of a localized string:

https://github.com/WorldHealthOrganization/app/blob/ed87ee3e076bb0be51edbc1d5cfc1588cd543bd8/client/flutter/lib/pages/latest_numbers.dart#L110

---
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
If v0 is English only, this is not a v1-requirement but would be p0 for post-v1.

**Comment by hspinks** [comment]
@advayDev1 I think that as part of v1, we should have all of our strings extracted and locked to make it easier on the localization team to start the translations. I'd like to keep it as a p0 v1

**Comment by advayDev1** [comment]
The loc team however is not bound by our build cutting.  Anyway back to v1 - agree on quick to fix :)
