### ISSUE TITLE
Push notifications - Document that "click_action: FLUTTER_NOTIFICATION_CLICK" must be sent on all push notifications

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1049]
The [firebase_messaging documentation](https://pub.dev/packages/firebase_messaging#sending-messages) says:

> When sending a notification message to an Android device, you need to make sure to set the click_action property of the message to FLUTTER_NOTIFICATION_CLICK. Otherwise the plugin will be unable to deliver the notification to your app when the users clicks on it in the system tray.

We need to document this and make sure we do this when we actually send push notifications in production. We should also test sending push notifications in staging with this property and make sure that users can click on the message.

**Comment by advayDev1** [comment]
Please clarify this issue.  What is the problem?  How do we solve the problem?  What is the impact of not solving the problem?

**Comment by epicfaace** [comment]
When push notifications are sent through Firebase, we need to add the parameters `"click_action: FLUTTER_NOTIFICATION_CLICK"` -- otherwise notifications may not be properly handled by Android phones.

**Comment by advayDev1** [comment]
please add this to your push notifications design doc @cbgrey - thanks!

**Comment by epicfaace** [comment]
not stale

**Comment by cv692001** [comment]
I am new to contributing can you please help me how to proceed with this issue ,  It will be very nice of you
