### ISSUE TITLE
Can't receive push notifications on Android in debug mode

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1050]
It feels like push notifications functionality might be broken on Android when running in debug mode. I'm testing this on my Android device (Moto G 5), when running the app in debug mode through `flutter run`:

1. Go through the flow of accepting push notifications.
1. Send a push notification through the FCM console.
1. No notification shows up, but instead I get the following error on the console:

```
E/FlutterFcmService( 8145): Fatal: failed to find callback
I/zygote  ( 8145): Do partial code cache collection, code=62KB, data=52KB
I/flutter ( 8145): onMessage: {notification: {title: test2, body: test2 - tell Ashwin if you've received this message}, data: {}}
```

might be related to https://github.com/FirebaseExtended/flutterfire/issues/180 and https://github.com/WorldHealthOrganization/app/issues/1048, but it's not the same issue. note that the app is running in the _foreground_ in this issue, so this is not the case of us not handling background push notifications.

**Comment by epicfaace** [comment]
Could be because push notifications might only work on release mode? https://stackoverflow.com/questions/19459824/android-push-notifications-not-being-received-when-app-closed

**Comment by epicfaace** [comment]
I've tested this further, also in release mode (`flutter run --release`).

It appears that notifications are received when the app is in the background / not running, but _not_ when the app is in the foreground.

**Comment by epicfaace** [comment]
I've investigated this a bit further and clarified what the problem actually is in another issue -- #1054.

**Comment by andvalsol** [comment]
is the issue still going on?

**Comment by epicfaace** [comment]
@andvalsol this issue is not really an issue -- #1054 is the real issue here

**Comment by joelmathewphilip** [comment]
> I've tested this further, also in release mode (`flutter run --release`).
> 
> It appears that notifications are shown when the app is in the background / not running, but _not_ when the app is in the foreground.

I also experienced the same thing..
