### ISSUE TITLE
Animations are laggy on older/slower devices

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1051]
I use a pretty old / slow Moto G 5 Plus, and the animations don't feel very smooth / responsive. I wonder if older devices may have worse issues.

Perhaps we should disable the animations for Android devices below a threshold SDK version.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1689183/79403087-e93c0e00-7f5b-11ea-9f61-1d77f1d3c71b.gif)

**Comment by britannio** [comment]
It'd be nice if we had a setting to turn off animations for accessibility reasons, maybe that should be a separate issue.

**Comment by advayDev1** [comment]
@britannio Re: animations - I’ve verified that:
When Android “Remove animations” is on: Hand washing remains animated. The home page navigation animations are completely removed.
When iOS “Reduce motion” is on: Hand washing remains animated. The home page custom animations get replaced by standard iOS push/pop.
On the basis of this, I believe we are good for v1.

Punting this for now.

**Comment by britannio** [comment]
> @britannio Re: animations - I’ve verified that:
> When Android “Remove animations” is on: Hand washing remains animated. The home page navigation animations are completely removed.
> When iOS “Reduce motion” is on: Hand washing remains animated. The home page custom animations get replaced by standard iOS push/pop.
> On the basis of this, I believe we are good for v1.
> 
> Punting this for now.

Thanks, I was only changing the animation scales via android settings when I tested it.

**Comment by PieterAelse** [comment]
@epicfaace The displayed GIF is a debug build. Debug build in Flutter are JIT compiled (to make eg. hot-reload work) while profile or release builds are AOT, thus more performant. 

Could you recheck if general animations are slow on your device with the release-build?
