### ISSUE TITLE
Push Notifications - shows a grey icon on Android

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1053]
Should show our app icon instead.

![Screenshot_20200416-095312](https://user-images.githubusercontent.com/1689183/79464663-5b4a3c80-7fc8-11ea-916f-fde92f29ec04.png)

**Comment by epicfaace** [comment]
[The docs](https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorNotifications) say:

> Notifications are drawn with dark text atop white (or very light) backgrounds to match the new material design widgets. Make sure that all your notifications look right with the new color scheme. If your notifications look wrong, fix them:

> Use setColor() to set an accent color in a circle behind your icon image.
> Update or remove assets that involve color. The system ignores all non-alpha channels in action icons and in the main notification icon. You should assume that these icons will be alpha-only. The system draws notification icons in white and action icons in dark gray.

This means that we need to pick a single color and make an alpha-only image for the notification icon. We need to design this.

**Comment by PieterAelse** [comment]
Once there's a design, Android Studio can easily generate the different sized for notification icons. But indeed they need to be 1-color + transparent.

After that, also this is needed in the `AndroidManifest.xml`:
```xml
<application ....>
    ....

    <meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@drawable/ic_notification" />

     ....
</application>
```

**Comment by davidkaneda** [comment]
Sorry, if someone could help here: What are the size requirements/best practice size for the icon?

**Comment by epicfaace** [comment]
@davidkaneda I'm not exactly sure, but I think it might be safe to create 24x24, 36x36, 48x48, 72x72, and 96x96 icons as mentioned here https://stackoverflow.com/a/29478847.

**Comment by davidkaneda** [comment]
Let me know how this works?

[notification.zip](https://github.com/WorldHealthOrganization/app/files/4625604/notification.zip)

**Comment by epicfaace** [comment]
This works, will give it a try!

**Comment by Ishaan28malik** [comment]
Is this still Open for UI design changes or @epicfaace have you fixed it ?
