### ISSUE TITLE
Users will not see push notifications while the app is in the foreground

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1054]
Right now, when a push notification is received on iOS / Android when the app is in the foreground, the default push notification UI does not show, but `onMessage` is called with the push notification details. This means that, effectively, the notification is just logged to the console but the user doesn't see anything.

This is because we have to handle the push notification differently when the user is already using the app. We will need to either manually display the default push notification banner (by using [flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications)) or design something (like a toast) that shows the notification in-app.

**Comment by advayDev1** [comment]
Very low probability of occurring since users likely won't be in the app.  Low pri.

**Comment by epicfaace** [comment]
not stale
