### ISSUE TITLE
GitHub organisation url

### ISSUE THREAD

**Issue by hugolgst** [WorldHealthOrganization/app#1060]
You should change the URL in your GitHub organisation profile: http://worldhealthorganization.github.io
Which is unavailable

**Comment by SamMousa** [comment]
There is no content here though. I'm not sure an organisation pages makes sense at this point.

Thanks for the tip, will discuss during standup!

**Comment by hugolgst** [comment]
I thought you would put the WHO link directly, this one https://www.who.int

**Comment by advayDev1** [comment]
This is not a bug with this app.  Closing.
