### ISSUE TITLE
[Get the facts] Multiple taps on "Next fact" button create a stagger during slide to next fact.

### ISSUE THREAD

**Issue by VlasovD** [WorldHealthOrganization/app#1061]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

1. After tap on "Next fact" and during slide to next fact make multiple taps on button.
**Actual result:** Stagger effect appears during slide to next fact, delaying next fact.
Ideally button should be disabled during transition to next fact.

**Comment by advayDev1** [comment]
See also #714 - we need to be debouncing button clicks

**Comment by hspinks** [comment]
Thanks for this bug report! I'm closing this in favor of the more generalized #1219
