### ISSUE TITLE
Animation skin color programmatic control

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1063]
To be more culturally sensitive, it would be good to be able to alter the skin color depending on the local community. It should be easiest to do this with the Rive hand washing animation. This issue is simply for programmatic control to change the skin color from the source code. Another issue will track plumbing it in to the localization system.

Please also confer with Juan Carlos to see if the animation color contrasts will adapt well for everything from caucasian to dark skin.

These two sites give a good indication of the full range in skin colors.....
https://www.demilked.com/skin-tones-pantone-colors-photos-humanae-angelica-dass/
https://www2.palomar.edu/anthro/adapt/adapt_4.htm

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
FYI @advayDev1 @hspinks

**Comment by brunobowden** [comment]
@luigi-rosso - please advise us if this is something difficult to do. Looking at the sophistication of the Rive animation, I thought it would be relatively straight forward.

**Comment by pjayathissa** [comment]
IMHO it would be better to have it randomly generated then location specific. Otherwise we have to decide what location has what skin colour and this can be very tricky and potentially even more culturally insensitive.
