### ISSUE TITLE
Inconsistencies in content_bundles yaml HTML

### ISSUE THREAD

**Issue by purpledrosophila** [WorldHealthOrganization/app#1069]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [ x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

There are some inconsistencies in the content_bundles YAML -- some of the text strings are formatted with HTML, some aren't, and some have incorrect HTML formatting. Do we have a consistent plan for how we want to format those? I just formatted protect_yourself.en.yaml, so if that's the kind of format we want, I can continue that in the rest of the content_bundles YAML.

**Comment by advayDev1** [comment]
If the suffix of a field is _html, it should be a limited form of html.
All other fields must be plain text.

**Comment by purpledrosophila** [comment]
Makes sense. 🙂 Inconsistencies still exist though, want me to tackle them?

**Comment by advayDev1** [comment]
Go for it.

**Comment by purpledrosophila** [comment]
Awesome. :) I will get on it as soon as my other pull request in this folder is accepted; don't want to duplicate efforts or accidentally mess something up.
