### ISSUE TITLE
Build system should minify PNGs and SVGs

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1075]
During the build step, we should minify pngs and svgs.

Alternatives:
* Do nothing.  Why waste space?
* GitHub actions or pre-commit checks to crush assets.  This has the downside that the committed assets lack information.  We wouldn't do that with source code, why do it with assets?

**Comment by Mastersam07** [comment]
We could host the images(PNGs) on an external service like firebase and then call them in-app as a cached_network_image. On the first launch of the app, image is fetched from the internet and then cached hence image won't load from the internet subsequently.

**Comment by advayDev1** [comment]
Why not both?  Our app must be able to function offline fully so optimizing the built in files matters.  But we should have a separate issue to use cached network images
