### ISSUE TITLE
Issues while hosting the code on local

### ISSUE THREAD

**Issue by vivekkash6373** [WorldHealthOrganization/app#1080]
I have followed all the instructions mentioned on the server.
But it hosts on my localhost: 8080 on the web it shows error 403.

![Screenshot from 2020-04-20 15-29-05](https://user-images.githubusercontent.com/64008726/79739362-b73ff880-831b-11ea-9623-564f83d530ec.png)

on the terminal, it shows
![Screenshot from 2020-04-20 15-27-56](https://user-images.githubusercontent.com/64008726/79739288-9a0b2a00-831b-11ea-9e35-0740e0dc80d8.png).

Let me know How can I resolve the issue.

Thanks.

**Comment by advayDev1** [comment]
This is correct.  The app is not hosted by the appengine server.  The server provides certain apis and static files.   There is no homepage for the server.

To run the app, see docs/ONBOARDING.md section for the client
