### ISSUE TITLE
Release, development, and prototyping branching model

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1087]
We owe the team this.

**Comment by hspinks** [comment]
Proposal for now (full documentation can come later):
* When code-complete, we cut a `release/v1.0` branch
  * From that moment forward, any code changes that we want to be included in the v1 release **must** use the release branch as base for PR
  * Any code changes that are not intended to be included in the v1 release should still use `master` as the base
* We will also cut a `release/v1.0-private` branch for the private repo
  * This will only be used for the items that cannot go in the public repo (e.g. commercial assets like app icon, etc)
  * This branch will be downstream from `release/v1.0` and will pull in updates from the main release branch when we are submitting to the app stores
* Even though the release branch is titled `release/v1.0`, app versioning in the pubspec.yaml file may still use `v0` versions until we have release candidates (e.g. tonight's code complete build will be `v0.11.0`); once we have official release candidates, we will start using `v1.0.0+<buildnum>-rc1` etc
* Once v1 is released on the app store, the `release/v1.0` branch will be merged back into `master`; we will keep the `release/v1.0` branch active for hotfixes

**Comment by advayDev1** [comment]
For v1 is complete, puntinng past v1
