### ISSUE TITLE
Symptom Checker Screen: Choose 1 of a long list of options (list/dropdown but in native UI)

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1099]
**The product definition, design, content, and assets are a WIP and are neither finalized nor fully approved by WHO. The purpose of this task is to prototype the feature so we can execute quickly when the non-engineering deliverables are finalized.**

**Comment by hspinks** [comment]
No longer a v1 feature as there are no questions in the spec that will require this
