### ISSUE TITLE
iOS App Permissions Review

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#110]
Cannot ship using defaults from ionic capacitor.

TODO from #95 (that I may have missed in a comment)

**Comment by SamMousa** [comment]
Can you elaborate? Do the default settings request too few or too many permissions?

Is this about the push notification permission?

**Comment by epicfaace** [comment]
It's worth noting that unlike Android apps, iOS apps do not ship with permissions by default -- they must prompt the user for permissions the first time they use them / on app boot up.

As @hspinks  [said](https://github.com/WorldHealthOrganization/app/pull/95/files#r395955291), what's in Info.plist are only descriptions that show up in the [dialog that prompts the user](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources) for their permission.

It appears that what permissions are requested might depend on what cordova plugins we're using. That being said, it doesn't seem that there's a centralized file that has a list of all permissions that will be requested, so perhaps we should just to run this on a device and see what permissions are requested.

**Comment by advayDev1** [comment]
SG - this broad issue is not needed then.
