### ISSUE TITLE
Symptom Checker Screen: Results UI

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1108]
**The product definition, design, content, and assets are a WIP and are neither finalized nor fully approved by WHO. The purpose of this task is to prototype the feature so we can execute quickly when the non-engineering deliverables are finalized.**

**Comment by advayDev1** [comment]
<img width="316" alt="Screen Shot 2020-04-22 at 6 01 37 PM" src="https://user-images.githubusercontent.com/11729521/80047850-5d7a3280-84c3-11ea-9b40-9158aca2d60b.png">

The product definition, design, content, and assets are a WIP and are neither finalized nor fully approved by WHO. The purpose of this task is to prototype the feature so we can execute quickly when the non-engineering deliverables are finalized.

**Comment by jasonTelanoff** [comment]
I can do this!
