### ISSUE TITLE
Add Donate Now section to home screen

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#1111]
**The product definition, design, content, and assets are a WIP and are neither finalized nor fully approved by WHO. The purpose of this task is to prototype the feature so we can execute quickly when the non-engineering deliverables are finalized.**

Update UI to the new prototype

<details>
<summary>Rough mock (subject to change)</summary>
<img width="294" alt="Screen Shot 2020-04-22 at 6 04 31 PM" src="https://user-images.githubusercontent.com/1484366/80047990-b944bb80-84c3-11ea-9bd0-bc6319620558.png">
</details>

**Comment by ishandeveloper** [comment]
@hspinks This is my first open-source contribution ever. I have changed the UI to be quite similar to the one depicted above.
If you could provide me with the SVG that was used in that background image, I would add that as well.

Please assign this issue to me and review the PR.

**Comment by advayDev1** [comment]
Thanks for your effort @ishandeveloper ; unfortunately we are not adding this to our existing home page, and are re-creating the homepage, awaiting mocks.
