### ISSUE TITLE
Implement Learn Index screen to new design

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#1114]
**The product definition, design, content, and assets are a WIP and are neither finalized nor fully approved by WHO. The purpose of this task is to prototype the feature so we can execute quickly when the non-engineering deliverables are finalized.**

Design is a WIP, but at least get the visual elements on the screen

<details>
<summary>Rough mock (subject to change)</summary>
<img width="276" alt="Screen Shot 2020-04-22 at 6 08 17 PM" src="https://user-images.githubusercontent.com/1484366/80048173-3ff99880-84c4-11ea-9352-b5eaf1521c4a.png">
</details>

**Comment by advayDev1** [comment]
There shall be no search bar in v1.
