### ISSUE TITLE
[Questions&Answers] After you scroll page several times all cross signs(close) will change to plus signs (expand).

### ISSUE THREAD

**Issue by VlasovD** [WorldHealthOrganization/app#1118]
**To Reproduce**
1. Navigate to Questions & Answers
2. Expand multiple questions and observe that plus signs have changed to cross sign
3. Scroll this page up and down several times
4. Observe question that were expanded and had cross signs

**Expected, correct behavior**
Expected result: All cross signs for expanded questions are still displayed as cross signs
Actual result: All cross signs for expanded questions have changed to plus signs, as if they were closed.

**Phone/Tablet (please complete the following information):**
 - Device: Reproduced on multiple devices - iPhone 6s , Galaxy S8, iPad Mini Retina , Galaxy Note 10 
 - OS: iOS 13.3.1,  Android 9.0.0, iOS 9.0.2, Android 5.1.1
 - App Version: v0.7.1 (14)

**Additional context**
Seems to be reproducible all around the place.

**Screenshots**
<details>
<summary>Screenshots</summary>

![IMG_0562](https://user-images.githubusercontent.com/16258539/80097522-1e57ea00-8574-11ea-8efd-23f4e3e9ee67.PNG)

![Screenshot_2020-04-23-13-58-11](https://user-images.githubusercontent.com/16258539/80097532-2152da80-8574-11ea-9017-abfb6f82c603.png)
</details>

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by braulio-balanza** [comment]
I could take a look at this if no one else is working on it
