### ISSUE TITLE
Add I18N and L10N Guidelines to README docs

### ISSUE THREAD

**Issue by sapte91** [WorldHealthOrganization/app#1119]
WHO App contributors need one place to look for important information regarding how the app has been configured to support localization and how to approach I18N and L10N when adding, updating or deleting content to be localized.

To solve this issue, we will add a Readme doc to address the following:

1. How to format new/updated strings to be translated with examples
2. Steps of localization process, including translation activities facilitated by Lingo24 and integration points
3. Quality Management
4. Glossary for common I18N and L10N terms

**Comment by purpledrosophila** [comment]
Can I be of any help with this? I've been working on some docs, and I would be glad to assist if you need me.

**Comment by clementmouchet** [comment]
@purpledrosophila thanks for the offer, can you reach out to me on Slack so we can discuss it?

**Comment by purpledrosophila** [comment]
I'm not on the Slack; as far as I know, invites are closed right now. Can I
have an invite?
