### ISSUE TITLE
Switch Firebase Analytics to observe named routes

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1125]
We should not be manually adding analytics to each screen.
Instead use `FirebaseAnalyticsObserver` with named routing

cc @patniemeyer @britannio @epicfaace

**Comment by epicfaace** [comment]
What is remaining here after #1150 was merged?

**Comment by advayDev1** [comment]
Can we get tab views monitored this way too 🤗

**Comment by hspinks** [comment]
Closing this as it was addressed in #1150, opened #1185 for tab views
