### ISSUE TITLE
Pre-cache all content bundles immediately after ToS acceptance

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1136]
Furthermore, the app cache should be updated to simply return immediately the cached version if it is within a short time period (~1hr) of the existing cached version.

**Comment by patniemeyer** [comment]
@advayDev1 So, it seems me that the simplest way to handle this is that upon initial TOS acceptance and perhaps thereafter each time the app returns to the foreground we simply try to load all of the bundles via our normal content loading mechanism.  This will prime the existing caching mechanism or do nothing if already within the cache period.  The cache period is governed by the server cache control http headers and is currently set to 10 minutes, but we could up this to an hour or whatever is preferred.

**Comment by patniemeyer** [comment]
@advayDev1 Note that this does rely on us having all permutation of the language and local symlinked on the server, else there will be nothing to cache and we'll be trying each time anyway.

**Comment by hspinks** [comment]
> So, it seems me that the simplest way to handle this is that upon initial TOS acceptance and perhaps thereafter each time the app returns to the foreground we simply try to load all of the bundles via our normal content loading mechanism. This will prime the existing caching mechanism or do nothing if already within the cache period. The cache period is governed by the server cache control http headers and is currently set to 10 minutes, but we could up this to an hour or whatever is preferred.

I think the biggest gain will be the first time launching the app, pre-caching from the TOS acceptance before the homepage is visible, so I think the simple approach you described sounds good. I'm indifferent on cache period - I think 10 min is enough to give us the gain we're looking for with pre-caching on TOS acceptance, but also the content is not going to change frequently, so upping the cache period wouldn't be a problem. Maybe bump up to an hour? Open to your thoughts
