### ISSUE TITLE
Choose an open source Emoji style for assets

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1145]
Two we could use:
https://github.com/googlefonts/noto-emoji/tree/master/svg
https://github.com/twitter/twemoji/tree/master/assets/svg

Which do you prefer?  (ex. faces on symptom checker)

**Comment by advayDev1** [comment]
@davidkaneda confirm that for v1 we will not do annything beyond native emojis yes?

**Comment by davidkaneda** [comment]
Pretty sure it's out of bandwidth at this point, so yeah-
