### ISSUE TITLE
All tap targets should be splashable on all platforms

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1156]
From review with david, Instead of iOS "flash" effect, we shall use material splashes for all buttons/tiles/menus except the tab bar.

**Comment by kassim** [comment]
"ripple" is the correct term for the effect I believe you're referring to

in a previous PR https://github.com/WorldHealthOrganization/app/pull/1034 it had been applied using Inkwell and Material component classes
