### ISSUE TITLE
Need flutter plugin for ExposureNotification framework

### ISSUE THREAD

**Issue by billpugh** [WorldHealthOrganization/app#1167]
To be able to use the ExposureNotification framework from flutter, we need someone to write a flutter plugin. This will involve designing the API to be used from within flutter, and providing bindings to both the iOS and Android Exposure Notification APIs. 

This effort should include writing a sample flutter app using the plugin to allow for testing that it works.

**Comment by kassim** [comment]
the ExposureNotification framework API for Android doesn't seem to be available available to the public, would the licensing allow it to be included in an open source/public project?

**Comment by billpugh** [comment]
We can write the code for it, there isn't any problem in writing and publishing code that invokes the API.  To actually test or deploy an app using the API, you have to be officially blessed by Apple & Google. We've been having discussions with them, they seem willing to bless WHO.  See the Exposure Notification channel in Slack for more info.

**Comment by kassim** [comment]
It's just I assume Google is providing private/beta binaries to developers that expose the ExposureNotification API and assume there wouldn't be permission to distribute these openly - so the project would end up being uncompilable for those without the binaries shared. Compared with Apple who have exposed the API publicly.


Anyway, while writing that I just read the issue https://github.com/WorldHealthOrganization/app/issues/1083

>This task separates out the build process to ensure we can prototype, without affecting production builds, and ensure that the app remains functional in both variations (production without contact tracing, and internal prototype with contact tracing).

Seems that this is already expected.

**Comment by billpugh** [comment]
We can set it so that any exposure notification code is only compiled if iOS 13.5 is available (and something similar for Android). Once 13.5 is released (two weeks), the API is public. Further, if it is built without the required entitlement, we can have it transparently disable the exposure notification functionality, so that anyone will be able to build a version without that functionality.
