### ISSUE TITLE
Repetition of text on Questions & Answers screen

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1171]
To Reproduce

1. Launch the app and complete the onboarding/permissions
2. Tap on learn tab in the footer of the home screen.
3. Tap on Questions & Answers
4. Expand the section saying "What can I do to protect myself and prevent the spread of disease"

Expected, correct behavior
The section should expand and repetition of text "What can I do to protect myself and prevent the spread of disease?" should not be there

Actual result
The section gets expand and repetition of text "What can I do to protect myself and prevent the spread of disease?"  is displayed.

**Phone/Tablet (please complete the following information):**

- Device: Huawei Honor 7c and Moto x4
- OS:  Android 8.0 , Android 9.0
- App Version: 0.8.0

Additional context
The text repetition is not observed at the WHO document present here 
https://www.who.int/docs/default-source/searo/bangladesh/2019-ncov/q-a-en.pdf?sfvrsn=275ce4d2_6   so app should also display it in the similar way.

Screenshots
![Q A_Text_Repeat_Issue](https://user-images.githubusercontent.com/63721227/80918999-466df700-8d85-11ea-9a9b-553f4db15568.jpg)
![WHO_reference_text](https://user-images.githubusercontent.com/63721227/80919071-a2d11680-8d85-11ea-8677-1929b4638410.PNG)

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [ x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by advayDev1** [comment]
@Mohit020888 did you build this apk yourself?  if so please provide the git commit where you build it

**Comment by Mohit020888** [comment]
@advayDev1 - yes I build the apk myself .
The git commit where I build the apk is    8abc232ef01211cdb6cbc50f787b381f4171c504

**Comment by Mohit020888** [comment]
Repetition of text is no longer observed on the latest master build.
![Screenshot_20200510-122655](https://user-images.githubusercontent.com/63721227/81493245-7c970380-92bc-11ea-97cd-0db6b305e7ab.jpg)
