### ISSUE TITLE
New News & Press screen

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1172]
New design for this screen
<img width="372" alt="Screen Shot 2020-05-03 at 12 22 31 PM" src="https://user-images.githubusercontent.com/11729521/80923500-0e40c700-8d39-11ea-9182-188eb7384bb7.png">

**Comment by hspinks** [comment]
@davidkaneda I see new designs in Figma, is this ready to implement?

**Comment by davidkaneda** [comment]
Yep! Just for reference:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/21713/81858563-cc720680-9518-11ea-9624-c2527b006544.png">

**Comment by davidkaneda** [comment]
(But with new Material navbar, need to update mocks to that)

**Comment by hspinks** [comment]
Love it! Assigning myself
