### ISSUE TITLE
Updates to Protect Yourself screen

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1173]
New design for this screen

<img width="351" alt="Screen Shot 2020-05-03 at 12 25 45 PM" src="https://user-images.githubusercontent.com/11729521/80923535-3cbea200-8d39-11ea-8f63-36656d8fa6db.png">

**Comment by davidkaneda** [comment]
Closing for now- design hasn't changed much, illustrations incoming (#1282). Feel free to reopen if needed to track the implementation separately-
