### ISSUE TITLE
BestTime API data to avoid crowded shops

### ISSUE THREAD

**Issue by vermaat** [WorldHealthOrganization/app#1182]
**Is your feature request related to a problem? Please describe.**
Due to the COVID-19 outbreak shops have limited opening times, and people's shopping schedules have completely changed. This results in sometimes overcrowded shops (e.g. grocery shops). Subsequently, this results in either long waiting lines, or too much people close to each other.

**Describe the solution you'd like**
It would be great to have an application that informs shoppers when shops are too crowded, so they can avoid them. I'd like to inform you of the web service [BestTime.app](https://besttime.app/?utm_source=github&utm_medium=post&utm_campaign=corona) . BestTime is an API that provides forecasts for public businesses (e.g. grocery stores), live busyness, and additional analysis (predicted peaks, quiet hours, etc). They don't have any smartphone application to reach the masses, but they have a demo environment to compare the forecasts for shop on a dashboard: https://besttime.app/demo/compare?d=b82e53441aa14244a7bf187ed2fff6d8
People can create additional dashboards with supermarkets in their own neighborhood. Maybe this WHO app can integrate some of these features.

**Describe alternatives you've considered**
Most apps chose for contact tracing, but most of them don't tackle the problem by preventing the spread of COVID-19. This data could help people making more informed decisions (e.g. avoid a crowded supermarket).

**Additional context**
https://besttime.app/images/landingpage/features/tool_comparevenues.png 

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by brunobowden** [comment]
@vermaat - this is a nice idea but we need data sources that are global, high quality and can handle massive scale. Google Maps tracks things like this but I'm not sure if it's available by API. Low priority in any case.

**Comment by brunobowden** [comment]
Duplicate of #450
