### ISSUE TITLE
Optimize CI pipeline

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#119]
Currently we start from scratch every time, this is suboptimal.

Instead we should:
- Install npm dependencies once
- Upload them as an artifact 
- Download them for tasks that need them

We can run tests on of the React code base on just 1 platform as soon as  #118 is merged.

Then we get a graph like this:
```
- Install deps
    - Run Tests
       - Build android
       - Build ios
       - Build webapp
````

Note that when we're more confident in the build process we can actually remove the build from this pipeline and only execute that when a PR gets merged into master.

**Comment by SamMousa** [comment]
For caching we should use this: https://github.com/actions/cache

Note that it mentions we should not cache `node_modules`, so the flow above will be a bit different.

**Comment by epicfaace** [comment]
This is an Ionic issue
