### ISSUE TITLE
Update architecture diagram for v1 launch security review

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1195]
@hspinks I've updated everything that we're planning on changing for v1, except Instabug, can you add Instabug and anything I missed

Live: https://www.lucidchart.com/documents/edit/3ce4e176-551f-4e71-9ec5-1c2e38071dea/0_0

[WHO COVID-19 System - Before.pdf](https://github.com/WorldHealthOrganization/app/files/4590124/WHO.COVID-19.System.-.Before.pdf)  (not under repo license)

[WHO COVID-19 System - After.pdf](https://github.com/WorldHealthOrganization/app/files/4590111/WHO.COVID-19.System.-.Page.1.pdf) (not under repo license)

@brunobowden we'll have this ready by Thursday night for Friday morning review with WHO security

**Comment by hspinks** [comment]
Update: https://app.lucidchart.com/documents/view/3ce4e176-551f-4e71-9ec5-1c2e38071dea/0_0

**Comment by advayDev1** [comment]
As a PDF: https://drive.google.com/file/d/1BMEyOnVAvJkr0Rd8XB7DKELWiFKvQZRx/view
