### ISSUE TITLE
Feature : Show number of recovered cases as showing confirmed cases and deaths.

### ISSUE THREAD

**Issue by devtechnocode** [WorldHealthOrganization/app#1197]
**Describe the solution you'd like**
Adding a column to show number of recovered cases as showing confirmed cases and deaths.

**Additional context**
Here add a column of recovered cases.
![Screenshot (5)](https://user-images.githubusercontent.com/52890488/81290992-a1099a80-9086-11ea-861d-75e4ff7722b8.png)

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by brunobowden** [comment]
@devtechnocode - we're limited to the official stats from WHO which doesn't track recovered cases so far. Once it adds that stat to the COVID-19 dashboard - https://covid19.who.int/ - then please reopen this bug and we'll take a look.
