### ISSUE TITLE
Continuous integration system choice

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#12]
Suggestions: Travis or GitHub's new actions 
I'm very familiar with travis for open source.  I am not at all familiar with GitHub's actions system.

@brunobowden  and I have worked on a project using Travis long ago.

**Comment by myire** [comment]
@advayDev1 can you describe more of your background?

Do you have experience with it and cordova?

**Comment by advayDev1** [comment]
No experience with cordova.  Plenty of experience with travis.

My background: run a satellite analysis startup now, previously led various teams at google (Google Play, AI, and ads teams) - https://www.linkedin.com/in/advaymengle/

**Comment by epicfaace** [comment]
Let's use GitHub Actions -- it will be far easier to share and manage access control than having to create a new Travis account. Plus GitHub Actions is faster as it allows 20 concurrent builds (while Travis only allows 3). I can help set this up.

**Comment by advayDev1** [comment]
@epicfaace can you get github actions building this app in a fork?  Theoretically the workflow would just need to run `yarn` in the subdir.  The permission less nature of Actions sounds appealing so we don't bottleneck on the handful of us that are committers and even smaller few that are security admins.

**Comment by SamMousa** [comment]
See #31

**Comment by myire** [comment]
@advayDev1 I think we can close this now?
