### ISSUE TITLE
Case stats from whoapp.org requested before ToS

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1205]
Looks like the home screen is requesting latest numbers even before it is displayed.

cc @hspinks

**Comment by britannio** [comment]
![image](https://user-images.githubusercontent.com/33752528/81457715-27110880-918f-11ea-9b2d-065bd86f4ab7.png)
Are the content bundles also an issue? @advayDev1

**Comment by advayDev1** [comment]
No automatic access to whoapp.org until after ToS if possible, pleas
