### ISSUE TITLE
Spec for Push notification functionality

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1222]
What are the product needs for push notification?
Clicking on the notification should go where?
Always a particular page in the app, a specified page in the app, an external URL, etc.?

Tell us a prioritized list of what push notifications need to do and we'll see what we can do by Wednesday.

cc: @marie-troisfontaine

**Comment by marie-troisfontaine** [comment]
@advayDev1 I added this item to the pgm board - Product should prioritize the needs for this functionality before engineering do additionnal work https://github.com/WorldHealthOrganization/app-pgm/projects/1#card-37982687

**Comment by advayDev1** [comment]
No further engineer work required for v1
