### ISSUE TITLE
Spec for Product Metrics Dashboard

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1223]
Prioritized list of what you want to know about analytics-wise, dimensions, etc.
We'll see what can already be supported by Google Analytics built-in, what we've already implemented, and what would still need to be implemented.

cc @marie-troisfontaine

**Comment by marie-troisfontaine** [comment]
Thanks! This is already tracked on the xfn board - this is a need that should be specified and prioritized by Product https://github.com/WorldHealthOrganization/app-pgm/projects/1#card-37894335

**Comment by advayDev1** [comment]
No further v1 work on this feature
