### ISSUE TITLE
App screen fluctuates on taking the app from background to foreground

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1229]
1. Launch the app 
2. Complete onboarding permissions .
3. On homescreen of the app , press the mobile device home button
4.  App goes to background.
5. Select the app from the device background running apps and launch it again.

Expected, correct behavior
App should again come to the foreground without any screen fluctuation.

Actual behaviour
App comes to the foreground with screen fluctuation

Phone/Tablet (please complete the following information):

- Device: Huawei Honor 7c , Moto X4
- OS: Android 8.0, Android 9.0
- App Version: [0.8.0 + 15]

![Screen_Fluctuation_Issue](https://user-images.githubusercontent.com/63721227/81508847-47be9700-9324-11ea-98b6-7907c810a934.gif)

---

Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by advayDev1** [comment]
@britannio is this a flutter embedding issue

**Comment by britannio** [comment]
@advayDev1 Possibly, after seeing [this comment](https://github.com/flutter/flutter/issues/53889#issuecomment-619983261) I think it's a Huawei issue. I can't reproduce it.

@Mohit020888 Can you `git checkout` the commit before https://github.com/WorldHealthOrganization/app/commit/916d7d43f7273289717b618a4f91022fe8eb4241 and see if that fixes the issue? It's https://github.com/WorldHealthOrganization/app/commit/fec34d46bbc58615b731508e10c441c47cfca52e

**Comment by Mohit020888** [comment]
@britannio - As suggested by you I checked out the git commit fec34d4 and built the apk [0.1.1(2)] on my Huawei Honor 7c device , the screen fluctuation is still observed but I agree it doesn't occur on Moto x4

![Screen_Fluctuation_Huawei_Honor7c](https://user-images.githubusercontent.com/63721227/81512843-6bdca100-9341-11ea-93b3-41aeb7f6b9f9.gif)

**Comment by Mohit020888** [comment]
@britannio and @advayDev1 - I retested this issue on the latest android app 0.9.1 (17) and have noticed the following : 
1) Launch the app and once user is on home screen , press mobile device back button instead of the 
    mobile device home button.
2) Pressing back button kills the app , now tap on the app icon to launch the app again.
3) App Splash screen is displayed followed by a screen fluctuation and then followed by a blank 
    white screen on which loading indicator is displayed before finally launching the home screen.

The above behavior is observed on Moto x4 (Android 9.0) , Oneplus 2(Android 6.0) and Huawei honor 7c(Android 8.0).
This is in addition to the screen fluctuation which is observed by taking the app to background using mobile home button and then to foreground  in case of Huawei device.


![MotoX4_ScreenFluctuation](https://user-images.githubusercontent.com/63721227/81596210-4f904100-93e1-11ea-87fd-4794af70496a.gif)
