### ISSUE TITLE
Colors and icons for each Symptom Checker result type

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1239]
Need:

* Colors for each symptom state
  * Emergency, COVID19-Symptoms, Some-Symptoms, No-Symptoms
* Icons for each "card" in the S-C result flow spec

**Comment by davidkaneda** [comment]
How’s this?

Emergency: Red
COVID-19: Orange
Some-symptoms/No-symptoms: Blue

**Comment by davidkaneda** [comment]
Icons will be in #1278
