### ISSUE TITLE
Learn More button is hidden on some Get the Facts pages

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1240]
## Summary
Remove the "Learn More" button and then make it vertically scrollable. This will also surface the additional content and invite someone to learn more by scrolling. Horizontal swipes would reset the view to the top of the page for each fact.

## Reproduction Steps

1. Launch the app and complete onboarding permissions.
2. On the home screen tap on Learn more button inside Get the Facts section.
3. Swipe right on various screens under this section.
4. Observe the screens which says Thermal scanners cannot detect if people are infected...
    and the screen which says Currently there is no medicine that's recommended...

  Expected, correct behavior
  Learn more button should be present on these screens below the text.

  Actual behavior
  Learn more button is hidden at the bottom of the screen and not visible to the user
  

Phone/Tablet (please complete the following information):

- Device: Moto X4 , OnePlus 2
- OS: Android 9.0 , Android 6.0
- App Version: [0.9.1+17]

Screenshots

![Screenshot_20200512-011955 1](https://user-images.githubusercontent.com/63721227/81605777-9dac4100-93ef-11ea-8409-9e3f4cb36ea6.png)
![Screenshot_20200512-011936 1](https://user-images.githubusercontent.com/63721227/81605817-b0267a80-93ef-11ea-8406-5d2814233c70.png)

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by advayDev1** [comment]
Small screens having problems with the big text.  Should we limit it to N lines always and auto-size it?

**Comment by davidkaneda** [comment]
Down to try auto-sizing, but also down to just go to 30pt/38pt (size / line height) for everyone.

**Comment by Ishaan28malik** [comment]
Maybe resize the layout and provide padding to the recent activities.

**Comment by Mohit020888** [comment]
Hi @Ishaan28malik ! The excessive padding was reworked as part of [](https://github.com/WorldHealthOrganization/app/pull/1345)
Did you check whether this issue is happening with the latest master build?

**Comment by Mohit020888** [comment]
Hi @Ishaan28malik , the padding and layout were resized as part of https://github.com/WorldHealthOrganization/app/pull/1345
Did you check whether this issue is happening in the latest build as well?

**Comment by Ishaan28malik** [comment]
@Mohit020888 Oh okay, let me check it in the new Build.I checked it last it was working fine.

**Comment by Mohit020888** [comment]
@Ishaan28malik - I re-verified on the latest master build (0.11.0 + 20) on Huawei Honor 7c and the issue still exists.
Do you want to take this up?

Attaching screenshots for your reference.
![Screenshot_20200707-192850](https://user-images.githubusercontent.com/63721227/86795326-11cf3200-c08b-11ea-9819-76d7be99130a.jpg)
![Screenshot_20200707-192900](https://user-images.githubusercontent.com/63721227/86795344-14ca2280-c08b-11ea-94a9-d3899e93dc84.jpg)

**Comment by Ishaan28malik** [comment]
@Mohit020888 Let me give it a try.

**Comment by mohak852** [comment]
@advayDev1  We can wrap it in a fitted box it will automatically adjust the size of text

**Comment by TrilogyTrustGlbfund** [comment]
Time heals all wounds#

**Comment by borowiecth** [comment]
Related issue on my Android 7.0 Vernee Active, screen size 5.5 inch, resolution 1980*1080.
I don't see the end of the sentences.

![Screenshot_20201009-092520](https://user-images.githubusercontent.com/70315478/95555989-dee26480-0a12-11eb-9fe8-e7404d467ba5.jpg)
![Screenshot_20201009-092720](https://user-images.githubusercontent.com/70315478/95555991-df7afb00-0a12-11eb-89c4-4e8c1d9b1f64.jpg)

**Comment by borowiecth** [comment]
Another example in issue: https://github.com/WorldHealthOrganization/app/issues/1562

**Comment by brunobowden** [comment]
@theswerd - this is an important one to fix since it's scream basic competency
