### ISSUE TITLE
Design review: Home page Background bleed scroll should be blue

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1241]

**Comment by britannio** [comment]
@advayDev1 Is this referring to the space exposed when you scroll past the bottom and get the bounce effect?

**Comment by britannio** [comment]
I also noticed that there's a sizeable gap between the navigation(tab) bar and the bottom of the illustration.

**Comment by advayDev1** [comment]
@britannio yes, on iOS
