### ISSUE TITLE
Design Review: Learn page button SVGs have 1 pixel border

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1248]

**Comment by hspinks** [comment]
FYI I think this is just an issue with the size of the SVGs. I tested with a larger SVG, and it looked like that border disappeared. I haven't looked into if there's a better way to size SVGs using `flutter_svg` yet, but if we re-export the SVGs with a larger original size, this issue should be solved.

**Comment by britannio** [comment]
Found a fix
