### ISSUE TITLE
Pre-launch, In Production Test: Send a push notification to all of the US 

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1263]
Verify:
- it is seen by iOS and Android
- ppl click it and go into the app
- can see open analytics

**Comment by brunobowden** [comment]
Tested on Android without analytics. Waiting on analytics setup and also iOS testing.

**Comment by brunobowden** [comment]
US message received on Android. Other issues discovered:
- #1854
- #1855
- #1856
