### ISSUE TITLE
Pre-launch, In Production Test: Send a push notification to the whole World

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1265]
Verify:
- it is seen by iOS and Android
- ppl click it and go into the app
- can see open analytics

**Comment by mohak852** [comment]
@advayDev1  can you assign this to me. This issue can be solved using firebase Notification.

**Comment by advayDev1** [comment]
Hi @mohak852 thanks for the offer.  This functionality is already implemented, indeed using firebase cloud notifications.  THe label indicates that this is a production test of existing functionality.

**Comment by brunobowden** [comment]
"World" message received on Android. Other issues discovered:
- #1854
- #1855
- #1856
