### ISSUE TITLE
Add .htaccess

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#128]
For the web app to support refresh we need url rewriting.

Simple solution is to add a `.htaccess`, either it works with a hosting provider, or it provides a basis for configuring the webserver.

**Comment by epicfaace** [comment]
What do you mean by "to support refresh"? It appears that the preview site (https://preview.whoapp.org/menu) does support refresh.

**Comment by SamMousa** [comment]
Hmm, in a previous build there was no `.htaccess` now there is, you're right.
