### ISSUE TITLE
Allow none of the above to be an answer in Symptom CHecker

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1283]
add the following as an answer:
```
- id: no_symptoms
  none_of_the_above: true
  title: None of the above
```
Then we can use has(‘no_symptoms’) in a lot of conditions too!

**Comment by mohak852** [comment]
@advayDev1 can you please elaborate on your issue I wanna work on this issue. Please assign this to me as soon as possible.
