### ISSUE TITLE
Back button missing on check up page

### ISSUE THREAD

**Issue by britannio** [WorldHealthOrganization/app#1288]
**Describe the problem**
A clear and concise description of what the problem is, from a user's perspective

**To Reproduce**
1. Open the app to the home page
2. Press the check now button
3. Observe the absence of a back button.

**Expected, correct behavior**
After step 2. the Check-Up page should appear with a back button.

**Phone/Tablet (please complete the following information):**

- Device: Any device
- OS: Any OS
- App Version: master?

**Screenshots**

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/33752528/81805459-ca0cae00-9512-11ea-9793-2b45f2760a08.png)

</details>

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by britannio** [comment]
@davidkaneda What would you like here?

**Comment by davidkaneda** [comment]
Sorry, discussed on Slack, but to recap: Seems like it'll be difficult to make this just jump between tabs when tapped on from the home view, so I suppose let's add a back button for when this specific situation (but ideally not when the tab is selected from the tab bar)

**Comment by advayDev1** [comment]
Yes we'll def not have a back bar in any tab itself .
