### ISSUE TITLE
Current design spec

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#129]
I will keep this ticket up-to-date with the current design spec as I see it on Figma to give us something to work to as we keep the UI in line with design. I'll be adding new comments to the bottom of this ticket with each update.

**Comment by hspinks** [comment]
*As of Mar 21 3pm PT:*

Onboarding flow / first-time user:
<img width="1007" alt="Screen Shot 2020-03-21 at 3 01 28 PM" src="https://user-images.githubusercontent.com/1484366/77237400-27285b00-6b85-11ea-9407-5fdfc844dbad.png">

Main screen / returning user:
<img width="490" alt="Screen Shot 2020-03-21 at 3 01 36 PM" src="https://user-images.githubusercontent.com/1484366/77237406-327b8680-6b85-11ea-8ff8-f77fc8d95fcd.png">

Protect yourself flow:
<img width="1246" alt="Screen Shot 2020-03-21 at 3 02 04 PM" src="https://user-images.githubusercontent.com/1484366/77237414-3d361b80-6b85-11ea-9e8c-ff5b65c38269.png">

Check your health flow:
<img width="1042" alt="Screen Shot 2020-03-21 at 3 01 45 PM" src="https://user-images.githubusercontent.com/1484366/77237417-4626ed00-6b85-11ea-9340-4c0dc4341994.png">

**Comment by ltphan** [comment]
I will start with the main screen/returning user.

**Comment by SamMousa** [comment]
So are we, or we are not doing a basic triage survey in v0.1? It was removed by @myiremark based on these specs; at the same time it was also updated by @pjayathissa (#203).

**Comment by hspinks** [comment]
_As of Mar 23 9am PDT:_

Onboarding / first-time user flow:
<img width="1038" alt="Screen Shot 2020-03-23 at 9 05 32 AM" src="https://user-images.githubusercontent.com/1484366/77337222-d8de9d80-6ce5-11ea-8377-22b76c36d15f.png">
<img width="862" alt="Screen Shot 2020-03-23 at 9 05 39 AM" src="https://user-images.githubusercontent.com/1484366/77337241-e09e4200-6ce5-11ea-8069-3bdcdb7bfe0a.png">

Main screen (returning user):
<img width="433" alt="Screen Shot 2020-03-23 at 9 05 47 AM" src="https://user-images.githubusercontent.com/1484366/77337271-e98f1380-6ce5-11ea-9995-f06a7120ab62.png">

Check Your Health flow:
<img width="1042" alt="Screen Shot 2020-03-23 at 9 05 55 AM" src="https://user-images.githubusercontent.com/1484366/77337301-f14eb800-6ce5-11ea-9780-98a91ed9df7a.png">

Protect Yourself flow:
<img width="839" alt="Screen Shot 2020-03-23 at 9 06 12 AM" src="https://user-images.githubusercontent.com/1484366/77337327-f9a6f300-6ce5-11ea-9d14-ffce650eb8fa.png">
<img width="634" alt="Screen Shot 2020-03-23 at 9 06 18 AM" src="https://user-images.githubusercontent.com/1484366/77337341-ff043d80-6ce5-11ea-9769-c573b4ba440f.png">

About the App page (still needs content):
<img width="432" alt="Screen Shot 2020-03-23 at 9 06 26 AM" src="https://user-images.githubusercontent.com/1484366/77337384-0c212c80-6ce6-11ea-8445-dacf4fa17e86.png">

**Comment by alayondiana** [comment]
Hello, dear design community!
I'm an Industrial + Product Designer based in Seattle, doing UX. I joined the project a few minutes ago, please let me know if you are still needing volunteers. My skills are usability testing, animation, and prototyping (Principle). I can also help with localization services,  I'm a Spanish native speaker.

**Comment by viviancromwell** [comment]
@hspinks Hunter, let me know if you want me to cut the screen shots every morning for the eng.  There is an export button at the bottom of Figma where you can export all.

One small design tweak I added this morning per feedback is captured here:
https://github.com/WorldHealthOrganization/app/issues/242

In the near future, once things are settled down a bit, the idea flow is to make a snapshot of the current design and that will be the version eng to use for development. Because design and development started at the same time for this one from zero, so there hasn't been any gap for us to cut a release and so on.  In the future, hopefully we don't need to do this. thanks - Vivian

**Comment by SamMousa** [comment]
@hspinks could you add the figma link the the original post?

**Comment by dfourcfive** [comment]
Hello everyone,
i'm flutter developer and would love to to give a help making this app

**Comment by ravishankarahirwar** [comment]
@SamMousa Hi, I am an Android App Developer with 10+ years of experience in developing Android app with Java/Kotlin. It would be great I can get a chance to contribute to this project. The design I can see on this ticket I can make it Android. I am requesting you kindly grant me permission to do contribution to this great and meaningful project.

**Comment by munsifhayat** [comment]
Great Initiative! 
I would love to be its part.  I am an iOS developer with 4+ years of experience. Let me know how I can help.

**Comment by pbwauyo** [comment]
I'm a Flutter developer. Would love to contribute to this project

**Comment by iqbal-uiux** [comment]
Greetings All,
I am UI/UX Designer having 3 years of experience, I would love to know if I can contribute to this initiative

**Comment by madiansay** [comment]
Hi Guys

I'm a Graphics Desginer. And i wanna contribute to this project.

**Comment by mackenziefly** [comment]
Hi everyone! I'm a UX/UI designer based in Amsterdam. Excited to be a part of this and contribute in any way that I can!

**Comment by rsin11** [comment]
Hello everyone! I am a designer based in USA. I would be glad to contribute in any part of the process.

**Comment by RizkiRay** [comment]
Hi everyone, i am mobile dev based in Indonesia. I would love to contribute in this project.

**Comment by nogicoder** [comment]
Hi, I'm a senior Flutter dev and would love to contribute!

**Comment by positiveForce** [comment]
Hello @hspinks I am a mobile and web designer. The slack link is invalid and I am not sure how to contribute. The other thread was closed. :)

**Comment by Sakib-Shamin** [comment]
Hello, I am an android app developer as well as a full-stack web developer from Bangladesh. It will be a pleasure if I get the opportunity to contribute to this project.

I hope I will hear from you soon.

**Comment by danagbemava** [comment]
Hello, @hspinks I'm a flutter developer and I would like to contribute to this project.

**Comment by t-k-c** [comment]
Willing to Help. I'm a developer from Cameroon

Le ven. 27 mars 2020 à 5:23, Rizki Raynaldy <notifications@github.com> a
écrit :

**Comment by hspinks** [comment]
Closing as we update process around design communication
