### ISSUE TITLE
Country dropdown doesn't work if you return to the country page for the 2nd time

### ISSUE THREAD

**Issue by britannio** [WorldHealthOrganization/app#1290]
**Describe the problem**
A clear and concise description of what the problem is, from a user's perspective

**To Reproduce**
1. Start the onboarding process
2. Go to the second then third page
3. Go back to the second page(via the back button)
4. Attempt to select a country
5. The country list page isn't shown

**Expected, correct behavior**
At step 4 I'd expect the page to be switched to the country list page.

**Phone/Tablet (please complete the following information):**

- Device: OnePlus 7 Pro
- OS: Android
- App Version: master

**Additional context**
This should be fixable without changing the flow but I'd prefer pushing the country list page in a new route and then using `Navigator.pop(context, <country>)` to detect which country was selected.

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by advayDev1** [comment]
cc @asianfoodlab @davidkaneda @hspinks 
We already cut changing the country for v1 in the settings.
I recommend we just don't let you change your country.  Once you go past the country screen you're done.

**Comment by davidkaneda** [comment]
This doesn't feel right if they mis-tap on the selection screen. We can make them tap some sort of confirm button on that selection screen if editing the value isn't possible, but I wouldn't recommend making this tap-once-and-move-on kinda thing.

**Comment by Luccasoli** [comment]
i had noticed this bug when i was solving another bug at same screen, could i try to solve this?

**Comment by Dev-Manny** [comment]
cc @advayDev1 @davidkaneda 
What solution do you propose as I would love to get it done.
