### ISSUE TITLE
Get the Facts -> Pagination section , backward and forward arrow button links are not displayed on the first and last screen.

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1292]
To Reproduce

1. Launch the app and complete onboarding journey.
2. Tap on Learn More button under Get the facts section. 
3. Scroll through different screens and observe the pagination section.

Expected, correct behavior
Backward arrow should be present on the first screen to go directly to the last screen and forward 
arrow should be present on the last screen to go directly to the first screen

Actual behavior 
Backward arrow is not  present on the first screen to go directly to the last screen and forward 
arrow is not present on the last screen to go directly to the first screen and user has to to go through each screen one by one

Phone/Tablet (please complete the following information):

- Device: Any Device
- OS: Android 
- App Version: [0.10.1 + 19]

Additional context
If we are not displaying these arrows as mentioned above then is it possible to make the pagination 
section dots itself to be clickable buttons so user can directly go to any screen which ever they want to ?

Screenshots
![PaginationIssue1](https://user-images.githubusercontent.com/63721227/81808932-20431680-953e-11ea-8632-b26183b994d4.jpg)
![PaginationIssue](https://user-images.githubusercontent.com/63721227/81808941-22a57080-953e-11ea-9471-5ea7cc0ffd4b.jpg)

Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).

- [ x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by britannio** [comment]
It's the intended behavior.
https://github.com/WorldHealthOrganization/app/pull/1261

**Comment by britannio** [comment]
@Mohit020888 
> If we are not displaying these arrows as mentioned above then is it possible to make the pagination
section dots itself to be clickable buttons so user can directly go to any screen which ever they want to ?

Feel free to create a new issue about this.
