### ISSUE TITLE
Home page, Learn index, and Recent Stats tabs will not update content automatically

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#1297]
User needs to manually quit app and reopen to get new content, meaning we could be displaying content that is weeks or months old

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by advayDev1** [comment]
Product priority:
- Recent numbers must have a way to update without app switch
- Home page numbers and recent numbers tab must be in sync
- Last updated date on R/N

Low pri:
- Learn index

**Comment by hspinks** [comment]
Solution to #1136 should mitigate this by at least refreshing content on app coming to foreground
