### ISSUE TITLE
Investigate push notification setup

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#130]
Look into what Flutter supports and come up with a plan for what to use to deliver pushes. Design & document a technical strategy for getting users set up to be delivered push notifications in v1.0

**Comment by dhruvilp** [comment]
I would recommend (https://pub.dev/packages/flutter_local_notifications) and (https://pub.dev/packages/firebase_messaging -- implemented by Flutter Team), and also (https://pub.dev/packages/firebase_in_app_messaging)

**Comment by hspinks** [comment]
Closing - #675 implements Firebase Cloud Messaging
