### ISSUE TITLE
When both analytics and notifications are turned off, set _firebaseMessaging.setAutoInitEnabled() to false

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1308]
[_firebaseMessaging.setAutoInitEnabled](https://developers.google.com/android/reference/com/google/firebase/messaging/FirebaseMessaging#public-void-setautoinitenabled-boolean-enable):

> When enabled, Firebase Cloud Messaging generates a registration token on app startup if there is no valid one and generates a new token when it is deleted (which prevents deleteInstanceId() from stopping the periodic sending of data). This setting is persisted across app restarts and overrides the setting specified in your manifest.

This value is set to true after onboarding, because analytics is enabled by default. However, we need to:
- set this value to false when a user disables both analytics and notifications
- set this value to true when a user enables either analytics or notifications (or both)

**Comment by epicfaace** [comment]
not stale

**Comment by brunobowden** [comment]
@epicfaace - would you be able to help us with this Ashwin? We're working with limited engineering capacity right now and still many open bugs to launch.... so any help possible would be very helpful. I'm happy to code review it but my sense is that you have a much better insight in to how to fix this.

**Comment by brunobowden** [comment]
@epicfaace - were you able to look at this? It would be a great help but we need to know if you have time for this. We’re juggling a lot and we’re short staffed so your help would make a big difference
