### ISSUE TITLE
design push notification permission request flow

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#131]
Should follow best practices for getting user's consent to allow push notifications, presented in-context with adequate reasoning. Want to make sure this is on our radar if notifications are (potentially) one of our key value drivers!

**Comment by viviancromwell** [comment]
@hspinks yes, we will be using two-step notification with the first step to present strong value prop. But I don't think we have this in the near future as far as I can tell.

see the article I wrote a while back, 2nd and 3rd implementation have the best results, per instrumentation data. 

https://medium.com/chop-technologies/purposeful-design-for-user-permission-e0ca1a86fdb4.

**Comment by hspinks** [comment]
Design complete for v1.0
