### ISSUE TITLE
Check-Up page: Change wording regarding terms

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1311]
The Check-Up page has the following language:

![image](https://user-images.githubusercontent.com/1689183/81870815-a5c9c500-9544-11ea-8add-b036005e4981.png)

It says "By using this tool, you agree to its terms", which implies that the Check-Up tool has separate TOS from the regular app, but then it links to the same T&S that the user has already agreed to when using the app for the first time. Could we clarify in wording so that we aren't implying that the app terms and the Check-Up tool terms are two different things?

Perhaps we could say, "By using this tool, you acknowledge you have agreed to this app's terms of service"

**Comment by mohak852** [comment]
@advayDev1 I wanna work on this issue can you assign this to me

**Comment by advayDev1** [comment]
Hi @mohak852 - sorry there’s nothing for engineering to do here at the moment. It’s assigned to one of our product managers to make a decision about what the feature does.
