### ISSUE TITLE
Privacy Policy / Terms site on whocoronavirus.org should serve HTML pages, not PDFs

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#1313]
Extension of #812, now that the markdown files have been included.

It's not good that we basically have two public privacy policies, https://whocoronavirus.org/privacy and PRIVACY.md, and terms of service (https://whocoronavirus.org/terms and TERMS.md) -- it's possible for both to get out of sync.

We should:
- Make sure that PRIVACY.md and TERMS.md have the right legal content we want (are they completely up to date with the latest PDFs?)
- https://whocoronavirus.org/privacy should serve content from https://worldhealthorganization.github.io/app/legal/PRIVACY.html
- https://whocoronavirus.org/terms should serve content from https://worldhealthorganization.github.io/app/legal/TERMS.html

**Comment by epicfaace** [comment]
not stale

**Comment by brunobowden** [comment]
Current plan is to host PN and TOS on who.int website
