### ISSUE TITLE
Investigate tools to help with distribution **Decision: fastlane**

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#132]
Potentially for both beta distribution pre-app stores & distribution on app stores. Hopefully these can link with CI / work with GitHub Actions instead of replacing. We'd like to keep everything centralized on GitHub so everything's in one place and we don't have to manage permissions on multiple tools, but we also want to make distribution as easy as possible

E.g.:
* [fastlane](https://docs.fastlane.tools/)
* [Bitrise](https://www.bitrise.io/)
* [MSFT Visual Studio App Center](https://appcenter.ms/)
* [TestFlight](https://developer.apple.com/testflight/)

**Comment by RohanTalip** [comment]
While not an initial distribution mechanism, there's also [CodePush](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/), which is part of Microsoft's App Center and is useful for updating app bundles that are already on users' devices.

CodePush is intended to be used for bug fixes that are necessary to get out relatively faster than a full app version release (major functional changes are supposed to go through Apple's app review process, and I'm guessing that would be true for Google's app review process too).

There might need to be a separate issue for CodePush ...

I have some experience with CodePush and could help with this if necessary.  (A gotcha to avoid: the client CodePush code loads the latest bundle for the current version from the CodePush servers, so either disable CodePush in local development builds by default or increase the version number locally before testing local changes.)

**Comment by shankari** [comment]
AFAIK, TestFlight is the only option that apple approves for beta testing. And given that Apple essentially prohibits dynamic native code downloads, I don't see how a third-party can provide a full solution.

Of course, you can make javascript/UI level updates using CodePush or the equivalent (Ionic Deploy) for example.

**Comment by hspinks** [comment]
Making the call to go with [`fastlane`](https://fastlane.tools/) as this is compatible with WHO's process. Also works with Testflight for beta distribution
