### ISSUE TITLE
Rip out Ionic default app assets throughout

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#133]
Icons, splash screens, etc.

**Comment by sstur** [comment]
I can take this one. Do we have an icon for the app yet? to replace the default one. What about for the splash screen, should I just make a white image with the blue logo on it?

**Comment by RohanTalip** [comment]
I'm assuming that favicon(s) will also be updated?

**Comment by SamMousa** [comment]
For now I propose we take the favicon from WHO's website.
That way we have something decent and can update it later.

**Comment by sstur** [comment]
> I'm assuming that favicon(s) will also be updated?

Yes, I did this in #189, including the favicon.

**Comment by RohanTalip** [comment]
Should this issue be closed now?  Or is there still something left to do?

**Comment by sstur** [comment]
Not yet, because #189 got rolled back so we have #256 in the pipeline but not yet approved for landing.
