### ISSUE TITLE
Sharing the app through Gmail and pressing back button on Gmail interface takes the app to background

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1339]
To Reproduce

1. Launch the app and complete onboarding journey.
2. On the homepage of the app, tap on Settings tab.
3. Tap on Share the app option and select Gmail out of the available sharing options
4. Gmail compose mail interface opens up , tap on Gmail interface back button.
5. User is navigated to Gmail homepage where all the user emails are displayed.
6. On this page press mobile back button.

Expected, correct behavior
User should be navigated back to the app.

Actual Result
User is not navigated back to the app and app is going to background.

Phone/Tablet (please complete the following information):

- Device: [Huawei Honor 7c]
- OS: [Android 8.0]
- App Version: [0.11.1 (21)]

**Additional context**
Tried the same set of steps with Whatsapp, Instagram, Facebook, Messaging , FB Messenger, Hangouts, Linkedin, Notepad, Slack but issue is only happening in case of sharing via Gmail option

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by mohak852** [comment]
I think it is an error caused by Gmail @advayDev1 What do you think of this issue?

**Comment by Mohit020888** [comment]
@mohak852 - did you get the chance to look into this issue further as the issue still exists in the latest master build ( 0.11.0 + 20)

**Comment by brunobowden** [comment]
@Mohit020888 - does this still occur? Do you see another app where the behaviour doesn't occur like this?

**Comment by Mohit020888** [comment]
@brunobowden - Issue is not reproducible on app version [0.13.0 + 24] , verified on Huawei Honor 7c running on Android 8.0.
