### ISSUE TITLE
Get The Latest News Screen Logo is overlapping Mobile Notification Bar

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1340]
To Reproduce

1. Launch the app on Moto X4 for the first time
2. Tap on Get Started button on the launch screen.
3. User is navigated to  Get the latest news from your community screen
4. Observe the  Logo on top of the screen.

Expected, correct behavior
Logo placing should be correct and it should not overlap the mobile notification menu bar.

Phone/Tablet (please complete the following information):

- Device: [Moto X4]
- OS: [Android 9.0]
- App Version: [0.11.1 + 21]

Additional context
Issue is not observed on my Huawei Honor 7c device having 5.5. inch screen

Screenshots
![Get_The_Latest_News_Logo_Placing](https://user-images.githubusercontent.com/63721227/81990424-cab15b80-965c-11ea-8f91-66be899a562b.png)

---

Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).

- [x ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by Mohit020888** [comment]
Same issue is happening on the next screen (Allow Notifications) on Moto X4 running on Android 9.0
![StayUpToDate_Logo_Issue](https://user-images.githubusercontent.com/63721227/81991852-c89ccc00-965f-11ea-9cd2-faa89d0dc065.png)

**Comment by Luccasoli** [comment]
We can just use MediaQuery.of(context).padding.top or wrap with SafeArea widget

**Comment by Mohit020888** [comment]
@Luccasoli  - Thanks for taking this up ! 
@advayDev1 and @hspinks kindly suggest .
