### ISSUE TITLE
Larger clickable area on home page for each section

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1348]
Clicking through to the app sections doesn't make the links obvious. Instead only some of each section is clickable. For example for the "Recent Numbers" section, only "See All >" is clickable. My contention is that "Recent Numbers" and "NUMBERS \n Global Cases" should also be clickable. Infact any click in the minimal box that surrounds that should work.

Similarly for "Check Your Symptoms", "Protect Yourself", "Get the Facts". The "Donate Now" button is ok as it's very clear. I think a larger box for Check Your Symptoms would still have value.

- Device: iPhone 11 Pro Max
- OS: 13.5
- App Version: 0.11.1

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by brunobowden** [comment]
FYI @davidkaneda @hspinks @advayDev1

**Comment by advayDev1** [comment]
IMO the stat card for recent numbers should also be clickable.
