### ISSUE TITLE
On small screens, intro text is left aligned

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1350]
What's happening here is the text widget is centered in the container, but the widget's own text alignment is left.

iPhone 8:

![Simulator Screen Shot - iPhone 8 - 2020-05-23 at 17 55 02](https://user-images.githubusercontent.com/11729521/82743314-8f7af080-9d1e-11ea-84e7-e594a353458a.png)

**Comment by mohak852** [comment]
iN MY CASE THERE IS NO TEXT LIKE THIS BELOW THE LOGO

**Comment by mohak852** [comment]
@advayDev1

**Comment by mohak852** [comment]
![WhatsApp Image 2020-05-30 at 8 12 45 PM](https://user-images.githubusercontent.com/58987025/83331163-03cf0a00-a2b2-11ea-92ec-c0b46a472e55.jpeg)

**Comment by mohak852** [comment]
We can do this by knowing the height and width of the device and then can use the if-else case and then can customize the font-size in this. @advayDev1 correct me if I'm wrong.
we can detect the height and width of the device by height: (MediaQuery.of(context).size.height),
and width by width: (MediaQuery.of(context).size.width),
