### ISSUE TITLE
Replacing Person icon with settings icon

### ISSUE THREAD

**Issue by mohak852** [WorldHealthOrganization/app#1356]
**Describe the problem**
When you will open the dashboard in the bottom navigation bar. you will find profile icon in settings tab instead of settings icon.

**Actual Behaviour**
![2](https://user-images.githubusercontent.com/58987025/82998858-dbcb7680-a025-11ea-8c04-d9b205801ae9.png)

**Expected Behaviour**
![Screenshot_1590586644](https://user-images.githubusercontent.com/58987025/82998937-f867ae80-a025-11ea-82eb-af4bcf0fd93a.png)

This should be the icon that should be in the place of profile icon

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [ ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ ] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by mohak852** [comment]
I Have filled a pr for it please review it #1357 1357

**Comment by advayDev1** [comment]
The icon currently used is as specified by our design lead.
