### ISSUE TITLE
On bigger screens SVG doesn't resize properly leading to unnecessary white space.

### ISSUE THREAD

**Issue by cosmicRover** [WorldHealthOrganization/app#1366]
**To Reproduce**

1. Run on an iPhone 11 Pro Max.
2. During on-boarding observe the country selector, and allow notifications page.

**Expected, correct behavior**
Don't know if it is intended, but shouldn't the SVG on these pages fill up the white space above them?

**Phone/Tablet (please complete the following information):**

- Device: [iPhone 11 Pro max]
- OS: [13.3]
- App Version: [1.2.0+14]

**Screenshots**
![Country selector page](https://user-images.githubusercontent.com/41096232/83990826-e08f0500-a918-11ea-9eb9-18c1583daef8.png)
![Allow notifications page](https://user-images.githubusercontent.com/41096232/83990847-ebe23080-a918-11ea-91ef-8c513f5f1946.png)

**Comment by advayDev1** [comment]
by design
