### ISSUE TITLE
Build broken / GHPages shouldn't build server or client directories

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#138]
````
The symbolic link /server/root targets a file which does not exist within your site's repository.
````

https://github.com/WorldHealthOrganization/app/runs/524529204

**Comment by advayDev1** [comment]
Sam, can you either exclude the `server` directory from GitHub pages or convert the pages config to yaml instead of in the admin config?  We can't see the config atm.

**Comment by SamMousa** [comment]
There is no easy way to convert it to yaml afaik.
We can move to manual jekyll configuration but i'm not familiar with that.
I propose we tell github to publish `docs/` folder instead, and move the docs there.

**Comment by SamMousa** [comment]
For now I have disabled pages.
