### ISSUE TITLE
Translation into Yoruba

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1395]

**Comment by brunobowden** [comment]
We're going to have hundreds of issues if we track language requests in GitHub. We should maintain that separately so it can be cross indexed with number of speakers and translation support.

Naturally code specific changes like RTL, character sets and accessibility are legitimate issues for GitHub.

**Comment by brunobowden** [comment]
Translation to WHO official six languages tracked in #224
