### ISSUE TITLE
Cordova

### ISSUE THREAD

**Issue by myire** [WorldHealthOrganization/app#14]
Going to throw some useful resources in here for cordova:

https://cordova.apache.org/docs/en/latest/guide/overview/index.html

http://cordova-multiplatform-template.js.org/

https://github.com/CKGrafico/Cordova-Multiplatform-Template

I think it would be prudent to avoid adding multiple SDK's (ionic) on top of one another, as well as limiting to JS instead of TS for the time being.

**Comment by epicfaace** [comment]
I'd suggest that we use [Ionic React](https://ionicframework.com/docs/react). Ionic is quite good for quickly making apps together, and using React instead of Angular is probably better given the popularity / widespread usage of React and React components.

**Comment by theswerd** [comment]
Rather than react, I prefer [Flutter](https://flutter.dev). Flutter's prepackaged Material widgets and large package base make it perfect for development situations that require speed like this one.

**Comment by hspinks** [comment]
Closing for now as we're using Ionic React
