### ISSUE TITLE
Java: Improve encapsulation

### ISSUE THREAD

**Issue by LinuxClient** [WorldHealthOrganization/app#1402]
**Describe the problem**
Instead of public variable "getter" and "setter" methods should be used. These improve encapsulation and do not affect performance.

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by advayDev1** [comment]
Please point out files, lines, and the purpose of the encapsulation (i.e. are there invariants to enforce?).  @LinuxClient

**Comment by LinuxClient** [comment]
In the classes [Client](https://github.com/WorldHealthOrganization/app/blob/master/server/appengine/src/main/java/who/Client.java) (Lines: 19, 22, 24, 26, 31), [StoredCaseStats](https://github.com/WorldHealthOrganization/app/blob/master/server/appengine/src/main/java/who/StoredCaseStats.java) and [StoredCaseStats$SotredStatSnapshot](https://github.com/WorldHealthOrganization/app/blob/master/server/appengine/src/main/java/who/StoredCaseStats.java#L36) are many public and partly package-private variables. These could be encapsulated using getters, setters and constructors. This would look much cleaner.
