### ISSUE TITLE
Stats -> Recent Numbers are not getting fetched in the app.

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1408]
1. Launch the app and complete onboarding journey.
2. On the home screen tap on the Stats functionality in the footer bar.
3. User is navigated to Recent Numbers screen.

Expected, correct behavior
Stats corresponding to total and new cases should be displayed along with the graph.

Actual behavior 
Stats corresponding to total and new cases are not getting loaded and graph is also not being displayed.

- Device: Huawei Honor7c 
- OS: Android 8.0
- App Version: [0.11.0+20]

![Screenshot_20200710-210619](https://user-images.githubusercontent.com/63721227/87172653-2f520500-c2f2-11ea-9ae5-a5df0dbb41d8.jpg)
![Screenshot_20200710-210612](https://user-images.githubusercontent.com/63721227/87172665-324cf580-c2f2-11ea-8eda-13a694b688c7.jpg)

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by Dev-Manny** [comment]
This issue is due to the downtime of https://whoapp.org/

**Comment by Mohit020888** [comment]
@Dev-Manny - thanks for the update !
@advayDev1 - can you please look into this ?

**Comment by advayDev1** [comment]
@brunobowden is checking ownership and registration of whoapp.org
