### ISSUE TITLE
Update WHO ARCGIS to COVID_19_Historic_cases_by_country_pt_v7_view

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1413]
Kevin Crampton (WHO) asks us to look into using:
https://services.arcgis.com/5T5nSi527N4F7luB/arcgis/rest/services/COVID_19_Historic_cases_by_country_pt_v7_view/FeatureServer

We currently use:
https://github.com/WorldHealthOrganization/app/blob/c4bff09002f7b1d2d12b6579b9fb036ae567fcb6/server/appengine/src/main/java/who/RefreshCaseStatsServlet.java#L20

https://services.arcgis.com/5T5nSi527N4F7luB/arcgis/rest/services/COVID19_hist_cases_adm0_v5_view/FeatureServer

**Comment by travelkev** [comment]
I can do some more digging on the WHO side - I got this more recent API URL from the business analyst on the WHO dashboard (https://covid19.who.int/) project - Kateryna.  She has been working with GIS colleagues on this.  I can double check this is the right one if we have any doubts.  The key thing for us will be that any data we use is consistent with https://covid19.who.int/ I believe.
