### ISSUE TITLE
New home screen banner/hero mocks (without Check-Up)

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1429]
Please provide a new mock for what the home page banner/hero looks like if not pointing to Check-Up tool.

**Comment by davidkaneda** [comment]
Updated in Figma, just pointing to "Protect yourself" for now:

![image](https://user-images.githubusercontent.com/21713/92059522-4c311480-ed46-11ea-92e3-5ca925eb0a79.png)
