### ISSUE TITLE
New design for Symptom poster

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1434]
Bruno-mocks are:
<img width="927" alt="check-up-info-only" src="https://user-images.githubusercontent.com/11729521/90442796-10345900-e090-11ea-81d2-473ca3d62534.png">

**Comment by davidkaneda** [comment]
Added two options in Figma, one based on the mockup above, one as a more direct translation of the page mentioned: 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/21713/92060401-86031a80-ed48-11ea-98ed-52a2c3c1cf9f.png">
