### ISSUE TITLE
Test Plan for V1 Nigeria Launch 

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1443]
We currently have test cases according to the work done before the project went on pause present at  the following location - 

https://docs.google.com/spreadsheets/d/1gu5MTj1VihUFjWWTWC19od7SEX9I5EDM78SV4SgHYAw/edit#gid=808223244

We need to modify these according to the latest product specs for our v1 Nigeria launch which can be found at -
https://docs.google.com/document/d/1lDq_Z82n_nZeczwxQYXqQQBmKCDOB1VBwnHGKbL-noA/edit#heading=h.7l4geyefw0ug

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by advayDev1** [comment]
mention test @tabassumwajid2005.

**Comment by brunobowden** [comment]
Finished for V1. Thanks @Mohit020888
