### ISSUE TITLE
New copy for country selector

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1457]
<img width="331" alt="Screen Shot 2020-08-22 at 8 23 40 PM" src="https://user-images.githubusercontent.com/11729521/90970128-761c4880-e4b5-11ea-81c1-7378d29ab960.png">

**Comment by brunobowden** [comment]
Duplicate for #1570

**Comment by advayDev1** [comment]
Hey @brunobowden this is not a super of the country names bug.  This bug is to determine what the text should say on the intro screen.  Allow location sharing doesn't makes sense anymore.
