### ISSUE TITLE
Deployment: WHO Architectural/IT Review

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1463]
Diagram here:
https://app.lucidchart.com/documents/view/3ce4e176-551f-4e71-9ec5-1c2e38071dea 

AI for me to write up a para summary

**Comment by travelkev** [comment]
Architecture Lucid chart forwarded to WHO IMT infra team for FYI and comment.

**Comment by advayDev1** [comment]
Thanks @travelkev just FYI - the version you may have grabbed isn't finished, and we're writing up a list of risks for WHO to consider and evaluate as well.

**Comment by advayDev1** [comment]
An IT risk and architecture review has been sent to WHO to review.

**Comment by advayDev1** [comment]
Attaching updated version 

[WHO COVID-19 System - draft v0.5.pdf](https://github.com/WorldHealthOrganization/app/files/5158364/WHO.COVID-19.System.-.draft.v0.5.pdf)

**Comment by borowiecth** [comment]
> Attaching updated version
> 
> [WHO COVID-19 System - draft v0.5.pdf](https://github.com/WorldHealthOrganization/app/files/5158364/WHO.COVID-19.System.-.draft.v0.5.pdf)

Document shared to WHO Infra and Cyber Security team. While there is a Cyber Security gate that the project must pass before application is released, there is no architecture validation gate.
No feedback for now, next step is the Cyber Security review.

**Comment by advayDev1** [comment]
@borowiecth thanks!  There is I believe the gate of use of Google Cloud, as discussed yesterday =)

**Comment by brunobowden** [comment]
@borowiecth - please close this if the review is completed. There are still pending work that's come out of it though and they'll be tracked separately.

**Comment by brunobowden** [comment]
@borowiecth - closing this as I believe we're covered on the review side. There's specific items that are being tracked as follow up from the prior review.

**Comment by advayDev1** [comment]
Are all the follow-on items tracked as issues linked here or somewhere?
