### ISSUE TITLE
Deployment: WHO-approved client and server production update procedure (RACI)

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1468]
- After launch, what, if anything, can the volunteer team update on server and client without needing WHO approval?
- Who, at WHO, is the approver for such updates?
- How do we request the update, and what info should be submitted in such request for update?

cc @travelkev

**Comment by advayDev1** [comment]
I think this is the RACI matrix.  Over to @brunobowden

**Comment by brunobowden** [comment]
RACI done and approved
