### ISSUE TITLE
Privacy Notice / TOS published and linked

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1510]
Per convo with WHO/Joris today: 
- WHO to verify the Privacy Policy/ToS are in all the right places in app stores, etc. prior to download (if WHO deems that necessary)
- WHO to verify its comfort with any data that might leave the device/app prior to passing past the first ToS/Privacy screen (see, for example, but not only, https://github.com/WorldHealthOrganization/app/issues/1509 , https://github.com/WorldHealthOrganization/app/issues/934 , https://github.com/WorldHealthOrganization/app/issues/1308 )

Obviously this is not legal advice to WHO, and WHO needs to figure out how it wants to do things.

cc @brunobowden 

_Please don't edit to signify changes - GitHub makes it appear that such edits come from me.  If your goal is different than what is described here, say so in comments._

**Comment by brunobowden** [comment]
who.int website will host the Privacy Notice and TOS

**Comment by brunobowden** [comment]
@borowiecth - please push on this so we can get the app updated. It's currently using a very old policy and we need to get this fixed up properly. Even if Jochem can just publish two blank pages, that would be helpful to move ahead.

**Comment by borowiecth** [comment]
https://www.who.int/myhealthapp/terms-of-use/ published, Privacy Notice should come before end of the week.

**Comment by borowiecth** [comment]
Both pages are now available on WHO environment

- https://www.who.int/myhealthapp/terms-of-use
- https://www.who.int/myhealthapp/privacy-notice
This was approved by WHO legal, I should get access soon to update the documents and will apply changes suggested by Advay

**Comment by brunobowden** [comment]
Thanks Thierry.

**Comment by advayDev1** [comment]
To clarify, my comments referred to by @borowiecth were regarding the first Terms and were directed to WHO legal counsel (Joris) and are not and were not legal advice.

On the Privacy Policy, I have not been involved in these last iterations (since I left the project), and would simply ask that WHO verify:
- that its description of the location of storage of all data is correct,
- and check if you want the title to say "A/C Privilege"
(I have not, and do not plan to, review it in detail).

As always, none of this is legal advice and is contributed under the MIT License (including all of its disclaimers of liability and warranty).

It is in the end up to WHO what they wish to put in all of these docs.

**Comment by advayDev1** [comment]
Oh also there's a random "This is a test" in the privacy doc =)

**Comment by advayDev1** [comment]
A few more, so to summarize on the Privacy side @borowiecth consider reviewing the following with WHO's attorneys:
* The Google Firebase section mentions Cloud Messaging, but ofc, the app also uses Firebase Crashlytics (see https://firebase.google.com/terms/crashlytics-app-distribution-data-processing-terms , https://firebase.google.com/support/privacy#crash-stored-info , and https://firebase.google.com/support/privacy#examples_of_end-user_personal_data_processed_by_firebase ) and Google Analytics for Firebase (https://firebase.google.com/policies/analytics), and in development, uses Firebase App Distribution too.  There may also be some data points collected in there to be listed in the Notice.
* Verify that the description of the location of storage of all data is in fact correct.
* Check if you want the "A/C Privilege" in the title.
* There is a random "This is a test" in the privacy doc.

As always, not legal advice, submitted under the MIT License (including all of its disclaimers of liability and warranty), and this is just my personal commentary - it doesn't speak for the project.

**Comment by advayDev1** [comment]
Given the bugs I just filed, was this task actually verified by anyone?  This bug was for:

> Per convo with WHO/Joris today:
> 
> WHO to verify the Privacy Policy/ToS are in all the right places in app stores, etc. prior to download (if WHO deems that necessary)
> WHO to verify its comfort with any data that might leave the device/app prior to passing past the first ToS/Privacy screen (see, for example, but not only, #1509 , #934 , #1308 )
> Obviously this is not legal advice to WHO, and WHO needs to figure out how it wants to do things.

So, for example, privacy policy links would need to be updated everywhere, and Apple App Store allows you to paste in your TOS/EULA so that users see it before downloading, etc. (unsure if Play does the same).

**Comment by brunobowden** [comment]
- WHO approved PN and TOS published:
   - https://www.who.int/myhealthapp/privacy-notice
   - https://www.who.int/myhealthapp/terms-of-use
- App Store and Play store updated with corrected Privacy Notice links
- App Store updated with EULA copy and link to website (not available in Play Store)
- WHO informed and accepts app behaviour and PN / TOS accordingly
