### ISSUE TITLE
Connectivity package requires locations permissions on iOS

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1520]
Comment from Bruno:

> Flutter Connectivity package uses names of Wifi and SSID, which requires location permission on iOS. This issue has been open for a year with the Flutter team. They are considering splitting the library in two with a "no location permission" version or providing some other workaround.
> 
> https://github.com/flutter/flutter/issues/40418
> 
> There is also a `simple_connectivity` forked flutter plugin that strips out the location requirement but that's based on an older version and hasn't been updated since February:
> 
> https://github.com/vanethos/simple_connectivity
> 

Original issue:

From WHO Release Engineering to Hunter and myself,
documenting it here for handoff to Bruno et al.

There should not be a use of user location in the v1 of this project, for iOS nor Android, and if there is still a hanging dependency on such a system, it should be removed.

--------------- 
 
Dear Developer,We identified one or more issues with a recent delivery for your app, "COVID‑19" 0.12.0 (23). Your delivery was successful, but you may wish to correct the following issues in your next delivery: 

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by brunobowden** [comment]
Left comment to nudge Flutter team to fix this:
https://github.com/flutter/flutter/issues/40418#issuecomment-699190184
