### ISSUE TITLE
putLocation and putDeviceToken in single request

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1524]
The mutator rpcs are prone to a race condition where the devicetoken  or location get overwritten because both rpcs happen in quick succession during onboarding.

The two mutator RPCs must, within their body, read the Client, update the Client, and save it within a transaction.

We've seen this in real life as well, the race condition is not merely theoretical.

**Comment by brunobowden** [comment]
@crazybob - do you have any spare time that you can spend to work on this? I'm guessing it would be much faster for you than any of us. Any general pointers or even pseudocode would be helpful.

**Comment by brunobowden** [comment]
FYI @yukuairoy

**Comment by advayDev1** [comment]
IMO there's an easier solution that I also believe is simpler: just have a single rpc '/putClientInfo' to save all client info, with all attributes provided by the device each time.  The device always has the complete picture of its own configuration.

( Because the "read" of the Client happens in the ClientInterceptor and the "write" happens in the service implementation, I wasn't sure how to put the whole thing in a transaction (I'm not at all familiar with Objectify framework personally). )

**Comment by brunobowden** [comment]
@advayDev1 - good idea. I'll work on that once I get the new build unless someone else beats me to it.

**Comment by brunobowden** [comment]
@matthewblain - please take a look at this. Also see @advayDev1's suggestion of combining the two request in a single request to avoid the race condition. This sounds like a good approach to me:
https://github.com/WorldHealthOrganization/app/issues/1524#issuecomment-700260154

**Comment by matthewblain** [comment]
The inconsistent results should be much less likley now as the entire client configuration is passed to the server, and in the typical UI flow there will be an update which should write the correct value.

Next fixes:
 * Add a transaction to the server so an error will be reported on 'collision.' 
 * Have the client retry on error somehow. Perhaps by recording a timestamp for last client side update and last server side sync, and occasionally validating that the two match.
 * Have the client report errors, e.g.  add an event to who_service like widget.analytics.logEvent(name: 'WhoServicePutClientSettings', parameters: {'result': response.statusCode});

**Comment by matthewblain** [comment]
Also TODO at some point: remove server support for the old devicetoken and country methods.

**Comment by brunobowden** [comment]
@matthewblain - closing this one as fixed by #1820. Please move other issues over to a separate bug at lower priority.
