### ISSUE TITLE
Blank page on invalid route

### ISSUE THREAD

**Issue by darcien** [WorldHealthOrganization/app#153]
Right now, the web page only displays blank page if the route is invalid, e.g. `/notabout`

This is happening because we only have redirects for the `/` path.

https://github.com/WorldHealthOrganization/app/blob/3927e6d887d21dfef75aa787b566db73c16d92ea/client/ionic/src/App.tsx#L52

Solution:
We could add a catch-all route to redirect to existing page or serve a 404 page.
e.g.
```tsx
<Switch>
  <Route path="/about" component={About} exact={true} />
  <Route path="/menu" component={Menu} exact={true} />
  <Route path="*">
    {/* Redirect or 404 here. */}
  </Route>
</Switc>
```

**Comment by navikalingoth** [comment]
<Route component={ } exact={true} />
