### ISSUE TITLE
Android embedding v2

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1530]
Reported by @Mohit020888.
```
client\flutter$ flutter pub get
-------------
Warning
-------------
Your Flutter application is created with an older version of the Android embedding. It's being deprecated in favor of Android embedding v2. Follow the steps at:

https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
```

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by hspinks** [comment]
See #937 cc @britannio
