### ISSUE TITLE
Get The Facts cut off text on small screens

### ISSUE THREAD

**Issue by borowiecth** [WorldHealthOrganization/app#1541]
**Describe the problem**
iPhone SE (1st generation) has cut off text (device and simulator):
- "Get The Facts" has clip art that covers text on home page
- "Get The Facts" => "Learn More" links inaccessible for some items

Similar issues could also exist for other even smaller devices. So any fix should also test the following devices in simulators:
- **iPhone 4S** - oldest iPhone that supports iOS 9.0 (oldest iOS version supported by Flutter).
- **Samsung Galaxy S III Mini** - as far as I can tell, oldest Samsung device that support KitKat (API Level 19)

**To Reproduce**

1. Go to home page of app, scroll to "Get The Facts" => cut off text issue
2. Click on "Get The Facts" => first "Learn More" is cut off

**Expected, correct behavior**
Everything works on small devices

**Phone/Tablet (please complete the following information):**

- Device: Apple SE
- OS: iOS 13.7
- App Version: 0.13.0 (24)

**Screenshots**

<details>
<summary>Screenshots</summary>
Add any relev

![MyHealth App - Picture 1](https://user-images.githubusercontent.com/70315478/94919836-667d2000-04b5-11eb-8a96-b347f674c9ff.png)

![MyHealth App - Picture 2](https://user-images.githubusercontent.com/70315478/94919844-6a10a700-04b5-11eb-80f9-3de693cdd30f.png)

ant screenshots here
</details>

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by brunobowden** [comment]
@theswerd @britannio - it would be great to have your help from one of you on this. There's lots of small devices in Nigeria, so we should fix this for launch.

**Comment by borowiecth** [comment]
Similar problems raised in incidents https://github.com/WorldHealthOrganization/app/issues/1240 and https://github.com/WorldHealthOrganization/app/issues/1562
