### ISSUE TITLE
Donate Now link not working

### ISSUE THREAD

**Issue by borowiecth** [WorldHealthOrganization/app#1542]
**Describe the problem**
When clicking on the link for Donate Now I got the message Couldn't Load App, see attached

**To Reproduce**

User having issue: WRIGHT, Emma Louise

**Expected, correct behavior**

**Phone/Tablet (please complete the following information):**

- Device: iPhone SE
- OS: iOS 13.7
- App Version: 0.13.0 (24)

**Additional context**

**Screenshots**

<details>
<summary>Screenshots</summary>

![MyHealth App - Picture 3](https://user-images.githubusercontent.com/70315478/94920148-fa4eec00-04b5-11eb-9977-d39f28df71dd.png)
Add any relevant screenshots here
</details>

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by brunobowden** [comment]
Shows a screenshot for failed TestFlight install and not an issue with the Donate Now page. Awaiting further details.

**Comment by borowiecth** [comment]
Donate Now works on my Android device, I close it
