### ISSUE TITLE
IP Address Data Retention Policy

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1544]
Bruno's comment:
> IP Address Data Retention Policy, ideally documented in Privacy Notice. For example, see the Firebase Privacy Policy.

Original issue:
If you ever get to doing exposure notifications, I hope the project strives for at least the level of privacy Covid Alert NY does: "Your phone automatically shares your phone’s IP address with the back-end server (an IP is a network address for your computer, so the Internet knows where to send you emails, data, etc.) for the purposes of logging exposures. The app will use the IP address in its communication with the server to request exposure information but does not collect or store your phone’s IP address itself. The server also does not store your IP address. This process ensures anonymity with all app users." https://coronavirus.health.ny.gov/covidalert-privacy/

**Comment by brunobowden** [comment]
I am working with Google to make sure we use IP Addresses on a temporary basis only. This is regardless of whether we support GAEN or not in the future.

**Comment by advayDev1** [comment]
Nice!  To achieve full IP address removal, there's a lot of places it would need to happen, including but not limited to: Google Analytics, Cloud Messaging (personally, I don't see that being feasible as the IP is needed to push the notification from the backend to the phone, but perhaps there is something I don't understand there), and the appengine servers, specifically their logging

Cloud Messaging states that they retain info forever until someone deletes the install ID via API + some add'l time - which makes sense... how else would you send a push message indefinitely into the future?  (Just like the appengine servers have to retain their data for the same reason, no?)

**Comment by brunobowden** [comment]
The newly planned Privacy Notice incorporates IP Address retention policy. I think it's basically the best we can do with the current system.
