### ISSUE TITLE
Apache 2.0 Relicensing

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1546]
If you've been a contributor, please follow these instructions:
https://docs.google.com/document/d/1zFwSAArykotRb6Gyb0Wh4Zdz92paHjRU_ZUrxNFUbm4/edit#heading=h.lxbcu0rg4q0g

See #1626 and #1545.

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by brunobowden** [comment]
Tracked in #1474

**Comment by advayDev1** [comment]
Not sure why this issue was closed.

**Comment by brunobowden** [comment]
I wondered about tracking it across both an issue and a PR but really it's
ok to have both be open.
