### ISSUE TITLE
Use ECMA-402 to get user langauge

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#155]
_Originally posted by @SamMousa in https://github.com/WorldHealthOrganization/app/pull/126/review_comment/create_

This article explains how to use it: https://cordova.apache.org/news/2017/11/20/migrate-from-cordova-globalization-plugin.html

Not sure what the benefits are vs using `navigator.language`

**Comment by epicfaace** [comment]
I don't think this is relevant anymore in Flutter?
