### ISSUE TITLE
Learn More section is not accessible in Get the Facts > Thermal scanners...

### ISSUE THREAD

**Issue by kostenkoka** [WorldHealthOrganization/app#1562]
**Describe the problem**
A clear and concise description of what the problem is, from a user's perspective

**To Reproduce**

1. Go to 'Get the Facts' section
2. Click on 'Learn more'
3. Scroll down to 'Thermal scanners cannot detect....' fact and try to scroll down and click on "Learn more"
4. Error: it is not possible to click on Learn more

**Expected, correct behavior**
Be able to scroll till the end, click on Learn more and get it expanded similarly to other sections in Get the Facts.

**Phone/Tablet (please complete the following information):**

- Device: [e.g. iPhone7]
- OS:  iOS13.7
- App Version:

**Screenshots**

![Capture d’écran   2020-10-08 à 15 14 57](https://user-images.githubusercontent.com/72559155/95466297-7cd72000-097c-11eb-81a0-936b8d24bf14.png)

**Comment by Mohit020888** [comment]
https://github.com/WorldHealthOrganization/app/issues/1240 was created for the same issue for android devices as well.
