### ISSUE TITLE
Recent Numbers: XX,XXX number format and x-axis values

### ISSUE THREAD

**Issue by borowiecth** [WorldHealthOrganization/app#1563]
**Is your feature request related to a problem? Please describe.**
In the page Recent Numbers, there are curves, the number in the curves are in the format 46867.0 and there is no date on the x axis.

**Changes:**
1. number format to XX,XXX for tooltip
1. values on x-axis (e.g. 100K, 10M or similar abbreviations)

Numbers are outdated, but I guess this is a known issue
![Screenshot_20201008-144250](https://user-images.githubusercontent.com/70315478/95479650-4b198580-098b-11eb-957d-f17fc04b2da9.jpg)

**Describe the solution you'd like**
1. Change the format to 46,867
2. Show values on the x axis

**Describe alternatives you've considered**

**Additional context**
Propose a link to the covid-19 dashboard: https://covid19.who.int/

---

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**

- [X ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [X] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [X] Issue has descriptive title focused on the feature or problem from the user's perspective

**Comment by brunobowden** [comment]
Fixed by #1595
