### ISSUE TITLE
Please check our FOSS project for same, it may be helpful

### ISSUE THREAD

**Issue by avi33tbtt** [WorldHealthOrganization/app#157]
https://bit.ly/CovidPitch  
https://bit.ly/covidprojectdocs
http://bit.ly/Covid-Source 
avi33tbtt@gmail.com

**Comment by dahacouk** [comment]
I personally don't like clicking on bitly links anymore. But I did. And I'll save anyone else the bother:

- https://docs.google.com/presentation/d/1E2fbiX3KW2VNBMy1C6lNxp_ffgze1s86t8Kd-3bZHEc
- https://github.com/TheSciFiMed/Covid-FLutter/blob/master/README.md
- https://docs.google.com/document/d/1xMH5ysJeDQhHbYjFa8xpVroJpPamuaLDx6PJVpWkmEA

;-)

**Comment by myiremark** [comment]
Thanks for your interest and suggestion!

Closing this issue to maintain a centralized list at:

https://github.com/WorldHealthOrganization/app/issues/324

**Comment by avi33tbtt** [comment]
Evolving as quarantine management system  - http://covn.org/ https://covn.org/team
