### ISSUE TITLE
WHO official list of countries and territories

### ISSUE THREAD

**Issue by matof-who** [WorldHealthOrganization/app#1570]
The list shows territories such as "Reunion"
and unofficial countries such as "Palestina"

is that the expected list ? or should it show only official countries ?

**Comment by Mohit020888** [comment]
@borowiecth and @matof-who : new copy of country selector is already requested as part of https://github.com/WorldHealthOrganization/app/issues/1457

**Comment by brunobowden** [comment]
cc @borowiecth
