### ISSUE TITLE
"Get the Facts" accessibility in Learn More page

### ISSUE THREAD

**Issue by matof-who** [WorldHealthOrganization/app#1571]
In the learn section, get the fact text and button are not very visible over the background image

**Comment by matof-who** [comment]
![Screenshot_20201009-141231](https://user-images.githubusercontent.com/70581697/95581655-ab670080-0a39-11eb-9dc1-1a972f5814fc.jpg)

**Comment by advayDev1** [comment]
See item 9 in https://github.com/WorldHealthOrganization/app/issues/1511

**Comment by theswerd** [comment]
For issue  *9* the drop shadow should we switch from a **FlatButton** to an **ElevatedButton**?

**Comment by brunobowden** [comment]
@theswerd - This is a lower priority than the other issues. If we do get around to this, then by all means post a screenshot.

**Comment by brunobowden** [comment]
I'm wondering if we shouldn't change the "Get the Facts" link to one of the standard shaped buttons below like "Travel Advice" and "Protect Yourself". The consistency will instantly fix the accessibility issue and also makes it more extensible for the future.

**Comment by advayDev1** [comment]
Dave left the correct background here: https://www.figma.com/file/zGNV0VqCqIqbk8CJUPgx9V/myHealth-Product-Spec-v1?node-id=20%3A1897 - it has the right color scheme to avoid the accessibility issue

I guess (don't know) that it is designed the way it is to avoid making it just a wall of buttons visually.
