### ISSUE TITLE
Get the facts section - when clicking learn more the text is not showing complete when it's long

### ISSUE THREAD

**Issue by matof-who** [WorldHealthOrganization/app#1572]
Get the facts section - when clicking learn more the text is not showing 
![Screenshot_20201009-102200](https://user-images.githubusercontent.com/70581697/95581845-f97c0400-0a39-11eb-8eb1-2416ad74e638.jpg)
complete when it's long

**Comment by borowiecth** [comment]
#1240 was created for the same issue for android devices as well.
