### ISSUE TITLE
Stats - number of cases on tooltip not showing when graph comes close to the border

### ISSUE THREAD

**Issue by matof-who** [WorldHealthOrganization/app#1574]
In the stats section, touching the graph will show the number of cases/deatths

But when the graph bar is close to the image border, the tooltip shows only partially on not at all
This is easily testable on the switzerland total deaths, where the curve is very close to the border

**Comment by borowiecth** [comment]
In this example, only part of the figure is visible: ![Screenshot_20201009-154819](https://user-images.githubusercontent.com/70315478/95591269-5d58f980-0a47-11eb-949a-9a6c39d0e909.jpg)

**Comment by Mohit020888** [comment]
@borowiecth and @matof-who  - this issue was already raised earlier , please have a look at https://github.com/WorldHealthOrganization/app/issues/1460
