### ISSUE TITLE
Date + count label for Recent Numbers tooltip

### ISSUE THREAD

**Issue by matof-who** [WorldHealthOrganization/app#1575]
Show the date alongside the number of cases / deaths in the tooltip for the Recent Numbers page. Horizontally centered, such as:

**October 10, 2020
&nbsp;&nbsp;387,617 Cases**

This date avoids the need for localization. This is the format used on the WHO's COVID-19 dashboard: https://covid19.who.int/. Screenshots below. The differences to the WHO dashboard are no "Daily Change" or "Daily Increase" and instead of "Confirmed Cases", it uses the shorthand of "Cases":

<img width="336" alt="Screen Shot 2020-10-17 at 11 43 10 AM" src="https://user-images.githubusercontent.com/679339/96351513-a5dc6c80-1070-11eb-8dc1-8f16c36624e1.png">

<img width="274" alt="Screen Shot 2020-10-17 at 11 43 23 AM" src="https://user-images.githubusercontent.com/679339/96351518-a7a63000-1070-11eb-9e32-df3a2e0dfec8.png">

**Comment by theswerd** [comment]
Do you have a format for the date in mind? If so would this format need to be localized?

**Comment by brunobowden** [comment]
@theswerd - using "August 1, 2020" or similar avoid the need for localization. This is the format used on the WHO's COVID-19 dashboard: https://covid19.who.int/
