### ISSUE TITLE
Deployment: WHO Security Review

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#16]
placeholder tasks for the future

**Comment by advayDev1** [comment]
Consider getting a pro bono security audit from a specialist firm.

**Comment by brunobowden** [comment]
@ michiel3 @jobertabma - HackerOne co-founders and personal friends

Not enough to security review yet but someone to help with setting up a HackerOne bug bounty would be very helpful. We're aiming to launch an initial version within a week.

**Comment by jobertabma** [comment]
@advayDev1 We are ready to allocate some of the community efforts towards a security review for WHO. Just say the word and we'll get things going! We can coordinate here on GitHub or privately at jobert@hackerone.com. We've got your back, thanks for having ours during these times.

**Comment by advayDev1** [comment]
Thanks @jobertabma - its also been my pleasure working with HackerOne professionally in the past.  Bruno and @SamMousa are the point persons for organizational coordination.

**Comment by brunobowden** [comment]
@jobertabma - please get things going but they might just be in a holding pattern until the app is more mature. Someone with Mobile / Cloud experience would be helpful.

**Comment by jobertabma** [comment]
@advayDev1 @brunobowden - @michiel3 and I coordinated with some people on our side and we can offer a program free of charge, including a Program Manager who will help set up the program (scope, policy, etc.). HackerOne also has a dedicated triage team that may have resources available to help with reproducing and escalating any security vulnerabilities that may be found during the test. We've reached out to some stakeholders internally and expect to have an answer tomorrow.

In addition to that, we were thinking to build a special COVID-19 hacker badge for participation in the program to further engage the community. Some of the hackers have already indicated in the past weeks that they want to make their time available to such causes.

At which point do you think the application will be mature enough to be tested?

**Comment by brunobowden** [comment]
@jobertabma - unknown at this point, I'd just have them follow on GitHub and https://who-app.slack.com and it'll be apparent as it gets going

**Comment by advayDev1** [comment]
cc @crazybob  - need to see what needs to be reviewed in our dependencies before 0.1, and then before vNext and what the relative scope of distribution for each is.

**Comment by brunobowden** [comment]
@jobertabma - this is a good juncture for HackerOne to get engaged around a more thorough security review on the WHO App (Flutter based on iOS and Android) and the backend (Firebase and App Engine). For anything sensitive, please email me or Bob Lee directly.

**Comment by willackerly** [comment]
@brunobowden @crazybob - Virtru is willing to fully sponsor / commit our security & compliance team (ran our product through FedRAMP and SOC2) and 3rd party assessors / pen testers that we used, starting as soon as tomorrow.  (as an addition to the HackerOne program)

**Comment by ramuz108** [comment]
I am a pentester as well. i can also help in security.

**Comment by rmspeers** [comment]
Per discussion in Slack, River Loop Security will assist with a pro-bono audit of parts of the app or infrastructure as requested. Waiting to get more details in Slack as to the appropriate scoping to not conflict with the HackerOne group looking at this as well.

**Comment by brunobowden** [comment]
@rmspeers - please see this for tracking the Security Review. There's also a number of other security work going on: https://github.com/WorldHealthOrganization/app/issues?q=is%3Aissue+is%3Aopen+security

**Comment by advayDev1** [comment]
Over to WHO Kevin to schedule review

**Comment by travelkev** [comment]
WHO cybersecurity team has been advised that they will be asked to run pentests on the solution.

**Comment by borowiecth** [comment]
Update on this topic, the WHO Cyber Security team has no capability to run the pentests on the solution.
So we need to find a third party to perform the penetration tests and create the report.

**Comment by borowiecth** [comment]
WHO Security Team has accepted the security level of the application provided that a few actions are completed before Go Live. I think we can close this issue.
