### ISSUE TITLE
Should we refactor ionic components to divs?

### ISSUE THREAD

**Issue by pjayathissa** [WorldHealthOrganization/app#161]
Right now we have been using a lot of Ion components. However if we go pure react native down the line there will be a lot of refactoring to do.

Would it make sense now to refactor all the IonComponents into plain divs? Just so the transission will be smoother

**Comment by myiremark** [comment]
It seems to me like a pretty tight timeline to finish the functionality and refactor everything within a day.

We're supposed to submit by Monday/Tuesday.

**Comment by epicfaace** [comment]
I think that would be a good idea (it doesn't have to be done by Mon/Tue), though I don't know if it would help with a transition to React Native -- because React Native doesn't support divs. This would help if we were to prepare to transition to pure React + Cordova, though.

**Comment by SamMousa** [comment]
imo don't worry about long term now, we can redo when we make a decision. Until then we're all-in on ion.
