### ISSUE TITLE
Stats screen should display daily case count along with the date on the tool tip

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1617]
Stats screen should display daily case count along with the date on the tool tip 

1. Launch the app and complete onboarding journey.
2. On the homescreen tap on Stats in the footer section
3. Tap on the charts UI on any of the Total Cases/Total Deaths section

Expected Behavior
The tool tip should display the date and number of cases on the particular selected day in accordance with the official WHO dashboard present at https://covid19.who.int/

Actual Behavior 
The tool tip is currently only showing the date and the number of cases on the particular selected date is not being displayed to the user.

- Device: Huawei Honor 7c
- OS: Android 8.0
- App Version: [0.13.0+24]

Screenshots
![Screenshot_20201015-113325](https://user-images.githubusercontent.com/63721227/96088140-9e875880-0ee2-11eb-9b91-49de40d579ca.jpg)

Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
Fixed by #1595
