### ISSUE TITLE
Device coverage

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#163]
@advayDev1 per Advay's suggestion, I think I should write down the device coverage.

**Comment by shankari** [comment]
Do you already have beta testers lined up for the launch? That can get some real device/non simulator coverage. One option is for us to track what personal devices the community has. That may already be enough.

**Comment by viviancromwell** [comment]
@shankari I dont have a testing plan yet, ideally we should have done it both before and after the app. But we are short on time. I have a designer who is coming on board who is going to address this.

**Comment by shankari** [comment]
@viviancromwell If you think it is appropriate, I can set up a google doc and ask people to log their phone model and log any beta testing issues that they encounter. Hopefully the eng team can then triage them and file Github issues for the real ones. Would you like me to do this?
