### ISSUE TITLE
Apache 2.0 Relicensing - Please comment "I Agree"

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1645]
## Apache 2.0 Relicensing:

Please comment "I Agree" to consent to the following (unsubscribe after to avoid further spam):

> I have used or may have used the email addresses listed alongside my GitHub username below. I consent to change the current license contained in the License file at https://github.com/WorldHealthOrganization/app/blob/master/LICENSE from the [MIT License](https://opensource.org/licenses/MIT) to the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0) with respect to all of my contributions to the WHO App.

Please comment with corrected name / email address(es) if needed. By granting this permission, you are confirming that you have the right to make your contribution(s) to the WHO App and to grant this permission, and that if you made your contribution(s) in the course of your employment, that such contributions and consent have been authorized by your employer.

The relicensing change is documented in https://github.com/WorldHealthOrganization/app/pull/1626. I will then document these consents in this file: https://github.com/WorldHealthOrganization/app/blob/master/docs/legal/apache-2.0-relicensing.txt.

## Motivation:

The Apache 2.0 license is a requirement for the Linux Foundation for Public Health to potentially host the WHO App project. See [FAQ](https://docs.google.com/document/d/1zFwSAArykotRb6Gyb0Wh4Zdz92paHjRU_ZUrxNFUbm4/edit) for more details.

## V1 Launch:

We'd welcome help to get through the last set of tasks for the v1 launch. Please pitch in with fixes or find us on Slack (contact github@brunobowden.com to join):
https://github.com/WorldHealthOrganization/app/milestone/4

## Email Addresses

Please correct name / email address(es) in your comment if needed.

@advayDev1: Advay Mengle - source@madvay.com, 11729521+advayDev1@users.noreply.github.com, advay.mengle.dev1@gmail.com, advayDev1@users.noreply.github.com
@????: AFeng - 2301230182@qq.com
@anikaraghu: Anika Raghuvanshi - anikaraghu@users.noreply.github.com
@areille: Augustin Reille - 32739983+areille@users.noreply.github.com, 32739983+augustinreille@users.noreply.github.com
@avkvirtru: Arthur Klepchukov - 44370126+avkvirtru@users.noreply.github.com
@brunobowden: Bruno Bowden - brunob@gmail.com, github@brunobowden.com
@epicfaace: Ashwin Ramaswami - aramaswamis@gmail.com
@AyushBherwani1998: Ayush Bherwani - ayush.bherwani1998@gmail.com
@ayushr2: Ayush Ranjan - ayush.ranjan98@gmail.com
@theswerd: Benjamin Swerdlow - swerdlowbenjamin@gmail.com
@crazybob: Bob Lee - bob@present.co, crazybob@crazybob.org. bob@whocoronavirus.org, crazyboblee@gmail.com
@britannio: Britannio Jarrett - britanniojarrett@gmail.com, 33752528+britannio@users.noreply.github.com
@cbgrey: Chris Grey - chris@wingtip.dev, thechrisgrey@gmail.com
@clementmouchet: Clément Mouchet - clement.mouchet@gmail.com
@creativecreatorormaybenot: creativecreatorormaybenot - 19204050+creativecreatorormaybenot@users.noreply.github.com
@orchardbirds: Dan - daniel.timbrell@ing.com, 49144672+orchardbirds@users.noreply.github.com
@dnfield: Dan Field - dfield@gmail.com, dnfield@google.com
@darish: Darish - 7066963+darish@users.noreply.github.com
@deanhach: Dean Hachamovitch - deanhach@users.noreply.github.com
@devamhdz: Alfredo Hernández - ahernandez@nyva.mx, 54552940+devamhdz@users.noreply.github.com
@devoncarew: Devon Carew - devoncarew@google.com
@dhruvilp: Dhruvil Patel - 38077836+dhruvilp@users.noreply.github.com
@guillermo-varela: Guillermo Varela - guille.varela3.16@gmail.com
@Moosphan: Hulk Su - 2301230182@qq.com
@hspinks: Hunter Spinks - hspinks@gmail.com
@jamesblasco: Jaime Blasco - jaimeblasco97@gmail.com
@jasonTelanoff: Jason Telanoff - 57235796+jasonTelanoff@users.noreply.github.com, jason.telanoff@gmail.com
@jpelgrim: Johan Pelgrim - johan.pelgrim@gmail.com
@joshdholtz: Josh Holtz - josh@rokkincat.com
@kassim: Kassim Maguire - kassim@users.noreply.github.com, okmaguire@gmail.com
@kieranbehn: Kieran Uddin - kieranbehn@users.noreply.github.com
@yukuairoy: Kuai Yu - yukuairoy@gmail.com
@Luccasoli: Lucas Mesquita - lucasoliveira98@outlook.com
@luigi-rosso: Luigi Rosso - luigi-rosso@users.noreply.github.com
@marctan: Marc Tan - marcqtan@gmail.com
@myiremark: Mark - 62413667+myiremark@users.noreply.github.com
@mjohnsullivan: Matt Sullivan - matt.j.sullivan@gmail.com, matt@rive.app
@amourakora: Omar Ashraf - 31867324+amourakora@users.noreply.github.com
@patniemeyer: Pat Niemeyer - pat@pat.net, patniemeyer@gmail.com
@PieterAelse: Pieter Otten - pieterotten@gmail.com
@pwicherski: Piotr Wicherski - pwicherski@gmail.com
@pjayathissa: Prageeth Jayathissa - p.jayathissa@gmail.com
@purpledrosophila: purpledrosophila - 55105187+purpledrosophila@users.noreply.github.com
@RohanTalip: Rohan Talip - RohanTalip@users.noreply.github.com
@nightlark: Ryan Mast - nightlark@users.noreply.github.com
@Samaritan1011001: Manoj Narayan Bisarahalli - manojnb95@gmail.com
@SamMousa: Sam Mousa - sam@mousa.nl
@sapte91: Shilpa Apte - shilpa.apte09@gmail.com, 2432064+sapte91@users.noreply.github.com
@shankari: Shankari - shankari@eecs.berkeley.edu
@ShivamSinghania:  Shivam Singhania - 30895841+ShivamSinghania@users.noreply.github.com
@sstur: Simon Sturmer - sstur@me.com
@stevan-milovanovic: Stevan Milovanovic - stevanm993@gmail.com
@tomgilder: Tom Gilder - tom.gilder@codemate.com, tom@tom.me.uk
@darcien: Yosua Ian Sebastian - yosua.ian.sebastian@gmail.com

#### Separate Consents
@davidkaneda: David Kaneda - dk@morfunk.com - see commit cf5a69c

**Comment by dnfield** [comment]
I Agree

**Comment by britannio** [comment]
I Agree

**Comment by dhruvilp** [comment]
I Agree

**Comment by Samaritan1011001** [comment]
I agree

**Comment by Luccasoli** [comment]
I agree!

**Comment by kassim** [comment]
I agree

**Comment by kieranbehn** [comment]
I agree

**Comment by patniemeyer** [comment]
I agree.  Thanks.

- Pat Niemeyer

**Comment by purpledrosophila** [comment]
I Agree

**Comment by brunobowden** [comment]
Thanks everyone so far.

@kieranbehn - the GitHub noreply email address - kieranbehn@users.noreply.github.com - is what's listed in the repo for your contributions, so that's the better one to record down.

**Comment by guillermo-varela** [comment]
I agree.

**Comment by devamhdz** [comment]
I Agree

**Comment by ayushr2** [comment]
I agree

**Comment by theswerd** [comment]
I agree

**Comment by sstur** [comment]
I agree

**Comment by devoncarew** [comment]
I agree

**Comment by jasonTelanoff** [comment]
I Agree

**Comment by AyushBherwani1998** [comment]
I Agree

**Comment by SamMousa** [comment]
I agree

**Comment by pjayathissa** [comment]
I agree

**Comment by RohanTalip** [comment]
I Agree

**Comment by orchardbirds** [comment]
I agree

Op wo 21 okt. 2020 00:10 schreef Bruno Bowden <notifications@github.com>:

**Comment by creativecreatorormaybenot** [comment]
I agree

**Comment by PieterAelse** [comment]
I agree
(name is Pieter Otten btw)

**Comment by clementmouchet** [comment]
I agree

**Comment by areille** [comment]
I agree
Email is : areille@tuta.io

**Comment by marctan** [comment]
I agree. marc tan here.Sent from my Huawei phone-------- Original message --------From: areille <notifications@github.com>Date: Wed, 21 Oct 2020, 7:34 pmTo: WorldHealthOrganization/app <app@noreply.github.com>Cc: Marc <marcqtan@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [WorldHealthOrganization/app] Apache 2.0 Relicensing - Please comment "I Agree" (#1645)
I agree
Email is : areille@tuta.io

**Comment by epicfaace** [comment]
I agree

**Comment by yukuairoy** [comment]
I agree

**Comment by jamesblasco** [comment]
I agree

**Comment by yukuairoy** [comment]
I agree

**Comment by avkvirtru** [comment]
I Agree

**Comment by mjohnsullivan** [comment]
I agree

**Comment by brunobowden** [comment]
Please reply with "I Agree" to consent to relicensing your contributions from the MIT to Apache 2.0 License. Full details here: https://github.com/WorldHealthOrganization/app/issues/1645#issue-725979510. Feel free to unsubscribe to avoid further notifications.

Thanks for everyone who's consented so far. Currently 25 / 53 (47%) code consents are now done. If your handle is below, then I still need consent from you:

@advayDev1
@amourakora
@anikaraghu
@britannio
@cbgrey
@crazybob
@darcien
@darish
@davidkaneda
@deanhach
@devoncarew
@hspinks
@jamesblasco
@joshdholtz
@jpelgrim
@luigi-rosso
@Moosphan
@myiremark
@nightlark
@pjayathissa
@pwicherski
@sapte91
@shankari
@ShivamSinghania
@sstur
@stevan-milovanovic
@theswerd
@tomgilder

**Comment by joshdholtz** [comment]
I Agree

**Comment by ShivamSinghania** [comment]
I agree

**Comment by darcien** [comment]
I Agree

**Comment by advayDev1** [comment]
Good morning.  First, note that some of the emails initially listed in this issue may not have known github names or pinged, namely afeng and alfredo.

Regarding my consent:

I do not intend to consent within this issue, but instead intend to provide a limited and different form of consent, by separate PR #1636, subject to certain conditions previously discussed with Bruno, including but not limited to the prior consent of certain persons not listed above whose contributions are not tracked via the github repository (which Bruno is working on).

That separate commit description will include a legend similar to the following:

> 
> This limited consent is based on the following:
>   * The consent by Ayman Badr on behalf of the World Health Organization to accept, and to license WHO's own contributions under, that certain form of license at https://raw.githubusercontent.com/WorldHealthOrganization/app/4d1a611bfa5ea807a8c3d2551beecfe8bc7f8cb2/LICENSE which includes a WHO copyright statement and also documents other components not licensed under the expected-new main Apache License 2.0 (which is documented in email from Ayman). Because the specific PR that Ayman referenced has been superseded, the file has been archived at https://web.archive.org/web/20200916041246/https://raw.githubusercontent.com/WorldHealthOrganization/app/4d1a611bfa5ea807a8c3d2551beecfe8bc7f8cb2/LICENSE
>   * @brunobowden 's representation that all of the persons listed within the "Apache 2.0 and MIT Licensing" section have consented as stated therein, in writing, to Bruno even though they have not recorded their own consent via git.  Their contributions are not necessarily tracked via the git repository.
>   * @brunobowden 's prior commitment that he will reach out to at least all of the people on both sheets of the contributor spreadsheet, and if he decides not to wait for any of their consent, to document that they did not consent in the final relicensing PR and document what was owned by them that he removed.
> 
> Notes:
> * If not all contributors consent, it may be necessary to remove not only their direct contributions to the repository but also moves, copies, refactors, adaptations, or resurrections of deleted files, etc. of their work added in subsequent commits, even though the non-consenter's name may not appear on the subsequent commit.
> * Note that not all contributors are necessarily documented via the Git history, and that some contributors that are tracked via Git are not within the commit author field but instead within the `Co-authored-by:` or `Signed-off-by:` (case-insensitive) lines in the commit message.
> * It may be difficult to track these contributions, especially for contributors whose work is largely performed outside of git and then put into git by a different contributor.
>  * My consent is provided in limited form partly to ensure that if not all contributors consent to the relicensing, the non-consenters' work, if it has been adapted, moved, copied, resurrected, or refactored in a subsequent commit by myself, is not deemed to be relicensed by my own consent, which applies even if my name appears on the `git blame` for a particular contribution or segment of code.
>  * None of this constitutes legal advice, nor can I represent that it is sufficient to lawfully perform the contemplated relicensing of the repository, nor can I represent that the contributor spreadsheet lists all IP-owners for this project.
>  * I recommend that @brunobowden and the project seek legal advice regarding this relicensing process to ensure that the rights of all contributors are appropriately protected and to ensure that downstream recipients of the contemplated new license can use it with confidence.
>
> If you have any questions about my intended consent, I may be reached at source@madvay.com

**Comment by stevan-milovanovic** [comment]
I agree

**Comment by devamhdz** [comment]
I Agree @devamhdz: Alfredo Hernández - ahernandez@nyva.mx
Please correct my user

**Comment by theswerd** [comment]
I agree

**Comment by sstur** [comment]
I Agree

**Comment by tomgilder** [comment]
I Agree

**Comment by brunobowden** [comment]
Please reply with "I Agree" to consent to relicensing your contributions from the MIT to Apache 2.0 License. Full details here: #1645 (comment). Feel free to unsubscribe to avoid further notifications. If your handle is below, then I still need consent from you.

Thanks for everyone who's consented so far. Currently 36 / 53 (68%) code consents are now done. We'd welcome help to get through the last set of tasks for the v1 launch. Please find us on Slack (contact github@brunobowden.com to join): or comment on one of the [remaining issues](https://github.com/WorldHealthOrganization/app/milestone/4
) to offer to help.

@advayDev1
@amourakora
@anikaraghu
@cbgrey
@crazybob
@darish
@deanhach
@hspinks
@jpelgrim
@luigi-rosso
@Moosphan
@myiremark
@nightlark
@pwicherski
@sapte91
@shankari
@stevan-milovanovic


#### Corrections (consent already given):
@PieterAelse: Pieter Otten - pieterotten@gmail.com
@devamhdz: Alfredo Hernández - ahernandez@nyva.mx
@davidkaneda: David Kaneda - dk@morfunk.com - see commit `cf5a69c`

**Comment by jpelgrim** [comment]
I agree

**Comment by davidkaneda** [comment]
I agree

**Comment by cbgrey** [comment]
I agree

**Comment by crazybob** [comment]
I agree

**Comment by pwicherski** [comment]
I Agree

**Comment by brunobowden** [comment]
Please reply with "I Agree" to consent to relicensing your contributions from the MIT to Apache 2.0 License. Full details here: #1645 (comment). Feel free to unsubscribe to avoid further notifications. If your handle is below, then I still need consent from you.

Thanks for everyone who's consented so far. Currently 42 / 54 (78%) code consents are now done. We'd welcome help to get through the last set of tasks for the v1 launch. Please find us on Slack (contact github@brunobowden.com to join): or comment on one of the [remaining issues](https://github.com/WorldHealthOrganization/app/milestone/4
) to offer to help.

@amourakora
@anikaraghu
@darish
@deanhach
@hspinks
@luigi-rosso
@Moosphan
@myiremark
@nightlark
@sapte91
@shankari
@stevan-milovanovic

**Comment by deanhach** [comment]
`I agree`

**Comment by stevan-milovanovic** [comment]
I Agree

**Comment by darish** [comment]
I Agree

**Comment by hspinks** [comment]
I agree

**Comment by shankari** [comment]
I agree. I also need to move my GitHub notifications to a more prominent place in my Inbox. Good luck!

**Comment by luigi-rosso** [comment]
I agree.

**Comment by sapte91** [comment]
I agree

**Comment by anikaraghu** [comment]
I agree

**Comment by nightlark** [comment]
I Agree

**Comment by brunobowden** [comment]
@myiremark, @Moosphan, @amourakora - you're the last GitHub consents we need to switch from the MIT to the Apache 2.0 license.

Please reply with "I Agree".

Full details here: [#1645 comment](https://github.com/WorldHealthOrganization/app/issues/1645#issue-725979510). Feel free to unsubscribe to avoid further notifications.

Thanks for everyone who's consented so far. Currently 51 / 54 (94%) GitHub code consents are now done. We'd welcome help to get through the last set of tasks for the v1 launch. Please find us on Slack (contact github@brunobowden.com to join): or send PRs for one of the [remaining issues](https://github.com/WorldHealthOrganization/app/milestone/4) (better comment first to avoid collisions).

**Comment by Henrymarks1** [comment]
I agree

**Comment by myiremark** [comment]
I agree

**Comment by kqtqk93** [comment]
I Agree

Pada Rab, 21 Okt 2020 06:10 Bruno Bowden <notifications@github.com> menulis:

**Comment by brunobowden** [comment]
@Moosphan @amourakora - you're the only two left! Just reply with "I Agree". Thanks.

@kqtqk93 - I couldn't see you listed as a contributor but we'd still welcome you.

**Comment by brunobowden** [comment]
@Moosphan - please reply with "I Agree" for the Apache 2.0 relicensing. All the other contributors have consented. We just need you.

**Comment by Moosphan** [comment]
I Agree

**Comment by brunobowden** [comment]
@Moosphan - thanks so much! You’re the last significant contributor we needed.

@amourakora - please reply with “I Agree”. You’re the very last permission we need! I know all you did was remove a single apostrophe.... but it would be nice for consent to be unanimous.
Ref: https://github.com/WorldHealthOrganization/app/commit/91b2c881858a7da03f74165869d1fe76829d450f

**Comment by brunobowden** [comment]
@amourakora - you're the only one left!! Even though your only edit was removing an apostrophe, it would be nice to get unanimous consent.

@Moosphan - thanks

**Comment by brunobowden** [comment]
Planning to merge this in an hour's time. Updated timestamp on the commit message for PR #1626. The PR also documents consents not received and why they're immaterial to the relicensing.

@amourakora - last chance to make it unanimous! Your single commit of 91b2c88 only removed an apostrophe. So it's not a blocker on the relicensing but it would be nice to make it unanimous for all the GitHub contributors.

**Comment by brunobowden** [comment]
Apache 2.0 License changed merged in. It's finally done. Thanks everyone.
