### ISSUE TITLE
UV Lamp correction - Get The Facts

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1667]
## Summary

UV lamps are used to kill the coronavirus but this message should be updated to explain why it's not used to disinfect hands and skin.

Current text:
```
Ultraviolet (UV) lamps **do not** kill the new coronavirus
```

Replacement Headline:
```
Ultra-violet (UV) lamps **should not** be used to disinfect hands or other areas of your skin
```

Replacement Learn More text:
```
UV radiation can cause skin irritation and damage your eyes.
<p>
Cleaning your hands with alcohol-based hand rub or washing your hands with soap and water are the most effective ways to remove the virus.
```

Source: https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public/myth-busters#uv

## Screenshots

WHO website:
<img width="773" alt="Screen Shot 2020-10-25 at 3 39 05 PM" src="https://user-images.githubusercontent.com/679339/97120952-3867b600-16d8-11eb-8704-0b4951011c6d.png">

## Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
@borowiecth - please review as part of the content review next week. Since it's a word for word copy of the website text, we're just going to merge it first and then review later.

**Comment by borowiecth** [comment]
Thanks, this is OK for me
