### ISSUE TITLE
Deployment: WHO Legal Review

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#17]
TBD:
-  3rd party libraries / dependency license review
-  CLA / developer license review
-  Verify privacy policy vs actual system #58 and #1509

_Please don't edit to signify changes - GitHub makes it appear that such edits come from me.  If your goal is different than what is described here, say so in comments._

**Comment by advayDev1** [comment]
- [ ] License review

**Comment by hspinks** [comment]
[ ] 3rd party libraries / dependency license review
[ ] CLA / developer license review

**Comment by advayDev1** [comment]
- [ ] Verify privacy policy vs actual system #58

**Comment by nightlark** [comment]
A CLA can create a very real, very big barrier to contribution. See https://github.com/WorldHealthOrganization/app/issues/10#issuecomment-602920695

**Comment by brunobowden** [comment]
I will confirm WHO legal sign off

**Comment by advayDev1** [comment]
The Privacy Policy on app stores is pointing to generic WHO PP, not the app-specific PP.

**Comment by borowiecth** [comment]
WHO legal signed off the updated version of Privacy Policy and Terms of Use

**Comment by brunobowden** [comment]
WHO legal done. All items closed except for #1509 which will be tracked separately for launch.
