### ISSUE TITLE
Home - Get the facts - whole card is clickable.

### ISSUE THREAD

**Issue by tabassumwajid2005** [WorldHealthOrganization/app#1704]
## Summary

Home - Get the facts - whole card is clickable if we have a button ' learn more' than only that button will navigate to the facts screen not complete card.

## Reproduction Steps

1. Launch the App
2. Go to the Home tab
3. Scroll down and click on get the facts card on other area than learn more button.
4. It will navigate user to the expected scree.

## Expected Behavior

Complete card should not be clickable if we gave a navigation button only that button should be clickable .

## System

- Device: Infinix Note 7
- OS: Android 10
- App Version: 1.13.0(24)

## Screenshots

<details>
<summary>Screenshots</summary>
https://prnt.sc/vc27c6
</details>

## Checklist:

- [ ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
@tabassumwajid2005 - I can acknowledge the issue. Closing this as we're looking to replace it with a different UI: #1672

**Comment by tabassumwajid2005** [comment]
Ok
