### ISSUE TITLE
What version of nodejs / npm is being assumed?

### ISSUE THREAD

**Issue by RohanTalip** [WorldHealthOrganization/app#171]
I'm assuming the latest LTS version as found here: https://nodejs.org/en/blog/

i.e. [nodejs version 12.16.1](https://nodejs.org/en/blog/release/v12.16.1/)

Is that a valid assumption?

**Comment by epicfaace** [comment]
The CI builds use Node 10.x -- https://github.com/WorldHealthOrganization/app/blob/master/.github/workflows/client.yml#L32

**Comment by RohanTalip** [comment]
@epicfaace , thanks.  I'll send a PR for adding a .tool-versions file for those people (like myself) that use [asdf](https://github.com/asdf-vm/asdf) to manage installed versions of tools.

**Comment by epicfaace** [comment]
This is an Ionic issue
