### ISSUE TITLE
Please make it for me, im looking for autobot to saving

### ISSUE THREAD

**Issue by kqtqk93** [WorldHealthOrganization/app#1739]
## Summary

A clear and concise description of what the problem is from the user's perspective.

## Checklist:

- [ ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
I can’t understand this
