### ISSUE TITLE
New Logo?

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1743]
## Summary

WHO has approved making this change. The motivation is greater awareness of the brand and fostering more trust with a global public audience.

## Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by theswerd** [comment]
Where should I go to get the assets?

**Comment by brunobowden** [comment]
See the Slack message that you were linked on in the #marketing channel.
Anshul may need to create the images for you.

**Comment by brunobowden** [comment]
Still in discussions with WHO

**Comment by brunobowden** [comment]
Fixed by #1849
