### ISSUE TITLE
Cloud Armor in Terraform: compute_security_policy

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1758]
## Summary

Setup Cloud Armor with sensible values. Likely this will include some defaults and a configured but not used IP block list. The configured but not used list is so that we can test the system... and if we need to deploy it in a rush then it will be easy to change data rather than write code.

It's probably the DDOS protection that's most helpful but I'm not sure how to configure that in Terraform.

https://www.terraform.io/docs/providers/google/r/compute_security_policy.html
https://www.terraform.io/docs/providers/google/r/compute_backend_service.html#security_policy
https://cloud.google.com/armor/docs/rule-tuning#preconfigured_rules

## Checklist

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by matthewblain** [comment]
"DDoS protection is automatically provided for HTTP(S) Load Balancing" - https://cloud.google.com/armor/docs/security-policy-overview.

I don't see anything in the documentation about 'enabling' Cloud Armor as a whole; is it always on when using a load balancer, or only when the a security policy is configured, even a pointless one? My guess is, always on. But it is worth having the placholder  placeholder CIDR block so we have that ready to go if needed.

I'm not sure of the cost vs benefit of the WAF rules.

**Comment by brunobowden** [comment]
@matthewblain - I think you're probably right about it always being on. There wasn't an option to "enable" it in the console either, which would be consistent with that conclusion.

**Comment by matthewblain** [comment]
Yes, in my Cloud Console instance some page went from advertising that I should use Cloud Armor to telling me that i have it enabled. Interestingly it's priced by rules, etc. so it's one of the things using up my starter credit.

I believe it was here that I saw it:
https://console.cloud.google.com/net-security/securitypolicies/list?
