### ISSUE TITLE
App showing No Internet Connection Message even when there is active internet connection

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1759]
App is incorrectly showing No Internet Connection Message even when there is active internet connection and it is also showing incorrect last update time.

1. Launch the app when mobile device has active internet connection.
2. Observe the warning message

Expected Behavior
App should only show this warning message when there is no active internet connection on the mobile device.

- Device: Huawei Honor 7c
- OS: Android 8.0
- App Version: 0.14.0 (25)

 Additional Context

Last update calculation is also incorrect when we compare the last available stats date as those are getting populated correctly

Screenshots
![No_Internet_Warning_Message](https://user-images.githubusercontent.com/63721227/99497937-a2ecd880-299c-11eb-9e98-0aa00e0f9608.jpg)

Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
@theswerd - more of a concerning bug. Not sure how this would occur.

**Comment by theswerd** [comment]
My current running theory is that the caching is failing but the network is working, however I'm going to need to test further before I can confirm.

**Comment by brunobowden** [comment]
Sprinkly in a few Google Analytics tracking events so that we can get stats
on the problems that users see.

**Comment by advayDev1** [comment]
I get this everytime I start the app on iPad.  Its pretty glaring bug when you use the app.

**Comment by brunobowden** [comment]
@matthewblain and I agreed earlier today about removing the warning as it's not reliable enough.

**Comment by brunobowden** [comment]
Fixed by #1843
