### ISSUE TITLE
Production Google Analytics

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1780]
## Summary

Production app must use WHO Google Analytics account. Users can disable analytics in the settings page.

## Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
If you are using an existing GA account, then the account level settings preventing any extraneous data sharing would also need to be set up - which may need the WHO owner to do that.

**Comment by brunobowden** [comment]
Yes indeed. All the required steps are recorded here:
https://github.com/WorldHealthOrganization/app/blob/master/server/terraform/README.md#analytics

**Comment by advayDev1** [comment]
@brunobowden no the steps are not detailed therein.  There are various data sharing settings that google auto-enables that one has to disable before using with this app at the *account* level.

![F357D747-4688-4213-B0C2-E409F87466DF](https://user-images.githubusercontent.com/11729521/100518749-65c8d900-3148-11eb-97d5-2318d2620f99.jpeg)

If WHO wants those settings enabled on their existing GA account, you would have to have a separate GA account (not just separate property), and ensure no cross-device attribution occurs for the app users.

Furthermore, GA auto-enables ad-personalization at the property level, which you would also need to disable:
![3956C70B-0F68-446D-8DCF-B3F4D288EAFB](https://user-images.githubusercontent.com/11729521/100518875-42525e00-3149-11eb-9da3-5fe6ab80ed26.jpeg)

It also auto-enables cross-device user tracking you need to disable:
![6BBB818C-8035-4CB9-BE95-BA16D6F7928D](https://user-images.githubusercontent.com/11729521/100518880-4d0cf300-3149-11eb-85a9-24721ed9e186.jpeg)

There are probably other settings to disable too that I haven't found.  But you would need to go through all the analytics account and property settings to make sure nothing is enabled that isn't private.

**Comment by brunobowden** [comment]
Thanks @advayDev1. I'm looking in to this.

**Comment by brunobowden** [comment]
Production Analytics account setup and configured according to new published Privacy Notice
