### ISSUE TITLE
refreshCaseStats / cron job disabled by ingress restrictions

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1799]
## Summary

The `refreshCaseStats` cron job is failing due to the `--ingress internal-and-cloud-load-balancing` settings. The url request is at `/internal/cron/refreshCaseStats`, so I thought it would be allowed as internal request but apparently not. That also explains why there's no logs for the cron job as the request can't reach the server.

## Workaround

Disable the ingress settings:
```
gcloud beta app --quiet --project=who-mh-staging services update default --ingress all
# WORKS: cron job succeeds

gcloud beta app --quiet --project=who-mh-staging services update default --ingress internal-and-cloud-load-balancing
# FAILS: cron job fails as before
```

## Reproduction Steps

1. App Engine Cron Dashboard shows "Failed": https://console.cloud.google.com/appengine/cronjobs?project=who-mh-staging&organizationId=532343229286
2. Click on "View" shows zero logs: https://console.cloud.google.com/logs/query;query=protoPayload.taskQueueName%3D%22__cron%22?organizationId=532343229286&project=who-mh-staging

## Expected Behavior

Cron job to run successfully with the ingress restrictions in place.

## Screenshots

App Engine Cron dashboard shows "Failed":
https://console.cloud.google.com/appengine/cronjobs?project=who-mh-staging&organizationId=532343229286
<img width="897" alt="Screen Shot 2020-12-06 at 1 14 34 AM" src="https://user-images.githubusercontent.com/679339/101276263-738de800-3760-11eb-87d3-da87a0b65f23.png">

Clicking on "View" shows zero logs:
https://console.cloud.google.com/logs/query;query=protoPayload.taskQueueName%3D%22__cron%22?organizationId=532343229286&project=who-mh-staging
<img width="1171" alt="Screen Shot 2020-12-06 at 12 56 35 AM" src="https://user-images.githubusercontent.com/679339/101276246-52c59280-3760-11eb-8484-1a6695286c90.png">

## Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by matthewblain** [comment]
Yes, this seems to be the case. Put together a simple test which makes it easy for anyone to verify. 
https://github.com/matthewblain/appengine_cron_test
