### ISSUE TITLE
Lint errors/warnings should fail the CI build

### ISSUE THREAD

**Issue by sstur** [WorldHealthOrganization/app#180]
This is as per our conversation in standup on Sun, Mar 22, and it is a followup of #168 by @epicfaace.

The current ESLint config in package.json extends the react-app config, but we are using [gts](https://github.com/google/gts) as our style guide. We should configure the project to use gts and configure the CI so that it will enforce this.

**Comment by epicfaace** [comment]
As I said in https://github.com/WorldHealthOrganization/app/pull/168#issuecomment-602221526, there's a problem here. It appears that react-scripts has its own eslint config, but gts has another eslint config.

If we enforce the react-scripts eslint config as in #181, this may cause issues -- what if something is an error in react-scripts eslint, but is not considered an error in gts eslint? Or vice versa? Or if doing X is considered an error by react-scripts eslint but _not_ doing X is considered an error by gts eslint?

Compounding this fact is that react-scripts doesn't let you override the default eslint config that it uses, unless you eject. I think we have the following options, but let me know if I missed anything:

1) keep the status quo, where react-scripts warnings are ignored (note that currently, gts eslint warnings _do_ fail the CI build),
2) eject react-scripts so it can use the gts config
3) stop using the gts eslint config and just use the react-scripts eslint instead.

**Comment by sstur** [comment]
> "there's a problem here. It appears that react-scripts has its own eslint config, but gts has another eslint config"

Right, I think we need to pick one of the two and stick to it. I'm inclined to go with the `react-scripts` one, but let's dig into the next part...

> "override the eslint config of gts by setting EXTEND_ESLINT=true."

Looking at that link you sent, it seems to be the opposite. If I'm understanding correctly, setting `EXTEND_ESLINT=true` lets us override the react-scripts eslint and use that of gts (or whatever we choose) instead.

So here's a question: what prevents us from just ditching gts's lint config and going with that of `react-scripts` and then we don't need to mess with EXTEND_ESLINT, right? I guess that means replacing `gts check` with the react-scripts equivalent. Although maybe that's a broader team decision, because likely someone added gts in here for a reason. I'll bring it up in standup tomorrow.

**Comment by SamMousa** [comment]
@sstur  https://github.com/WorldHealthOrganization/app/issues/30

The decision was made here. If really needed we can reopen, but I'd rather not seeing as this is all about one time configuration and not really about whether one is better than the other.

**Comment by epicfaace** [comment]
I'm fine with ditching gts's lint config, though as @SamMousa , that decision was already made and I'm not particularly in favor of one over the other.

I did try using EXTEND_ESLINT to use the gts config, though, and it appears that the latest npm package published for gts has a bug that doesn't allow you to extend its eslint config: https://github.com/google/gts/issues/465

**Comment by epicfaace** [comment]
As per discussion in https://github.com/google/gts/issues/465, it appears that we can use the gts config for everything by setting EXTEND_ESLINT=true and upgrading to gts version 2.

**Comment by epicfaace** [comment]
Actually, we discussed in standup (yesterday, I think) that it would be fine to switch to the react-scripts config from gts altogether, because the react-scripts eslint config has specialized rules for React and components that are not present in gts. So #181 is still relevant @sstur (although this won't matter since we're moving away from Ionic anyway).

**Comment by sstur** [comment]
Closing this as we've moved away from the Ionic implementation.
