### ISSUE TITLE
Re-ToS/PN users with the final version of the launch docs

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1842]
@brunobowden Hunter made a change a while back re-tosing users, which I guess can be redone again for the launch version.  Most importantly GA opt-outs should be preserved across re-toses which is a bit tricky.  Think we discussed this a few months ago, but I don't see a bug.

Nothing herein is legal advice.

**Comment by brunobowden** [comment]
I'm looking in to repeating what @hspinks did before:
https://github.com/WorldHealthOrganization/app/pull/1450
