### ISSUE TITLE
App Store (TestFlight) privacy policy link seems old

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1847]
At least testflight links to https://whoapp.org/privacy And has bruno's personal email address as the dev.

**Comment by brunobowden** [comment]
Updated policy just published:

https://www.who.int/myhealthapp/privacy-notice

**Comment by advayDev1** [comment]
It's the link i was filing a bug about

**Comment by brunobowden** [comment]
Understood. That's why it's a comment and not me closing it as resolved.

**Comment by brunobowden** [comment]
Just had a session with WHO to update the App Store and Play Store privacy links + App Store only update of EULA (couldn't find EULA link on Play Store). These will be published with the next version.
