### ISSUE TITLE
512 x 512 App Icon Quality Improvement

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1852]
## Summary

The current version of the 512 x 512 app icon imagery looks like a resampled image and poor quality. 
https://github.com/WorldHealthOrganization/app/blob/f7cb2b3405681500cf791746a1b139e46e01f763/client/android/app/src/main/ic_launcher-playstore.png

This might be a better high resolution image to base it on:
https://www.who.int/images/default-source/infographics/who-emblem.png?sfvrsn=877bb56a_2

## Screenshots

For close up on the image:
<img width="750" alt="Screen Shot 2020-12-19 at 7 28 53 PM" src="https://user-images.githubusercontent.com/679339/102704454-71cc2600-4230-11eb-8b79-5d0285e26a72.png">

## Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by theswerd** [comment]
@brunobowden @Mohit020888 I think I'm good to close

**Comment by brunobowden** [comment]
It should've closed it automatically. Closing now anyway....
