### ISSUE TITLE
Notifications disable doesn't work (topics issue?)

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1857]
## Summary

A clear and concise description of what the problem is, from the user's perspective

## Reproduction Steps

1. Go to Settings
3. Enable "Notifications"
4. Send message to `ALL~LOCATION~US` topic
5. WORKS: notification received

6. Disable "Notifications"
4. Send message to `ALL~LOCATION~US` topic
5. FAILS: notification received

## Expected Behavior

No notifications

## System

- Nexus 5
- Android 6.0.1

## Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
Given that this appears not to match the privacy policy, should this not be marked a privacy bug?
