### ISSUE TITLE
Wrong Stats are being displayed when internet connectivity is lost and country is changed

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1858]
1.  Launch the app and complete onboarding journey.
2.  Tap on Stats icon in the footer.
3.  Stats for the selected country is displayed to the user.
4.  Switch of mobile internet.
5.  Go to Settings and and change the country from the dropdown.
6.  Tap on Stats again after changing the country.

Expected Behavior
Previous Country Stats should not be loaded for the changed country

Actual Behavior 
Stats of previously selected country are being displayed for the newly selected country.

 System

- Device: Huawei Honor 7c
- OS: Android 8.0
- App Version: Version 1.0.0-staging(281)

 Additional Context

Another observation is that if we change the country by the search option in the dropdown then this bug doesn't occur, it only happens when we change the country by scrolling the country selector dropdown.

https://user-images.githubusercontent.com/63721227/102717147-706d2d00-4306-11eb-9d45-2a5755048e5d.mp4

Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by matthewblain** [comment]
Will be away for several hours but have proposed the fix above.
