### ISSUE TITLE
Bring UI to spec for v0.1

### ISSUE THREAD

**Issue by myiremark** [WorldHealthOrganization/app#186]

**Comment by advayDev1** [comment]
If this means v0.1 (i.e. Tuesday) please use that moniker 🙏

**Comment by britannio** [comment]
The Figma link(https://www.figma.com/file/fjzTIloCEK4FpbyDiTLj2X/iOS-UX) in the ROADMAP.md doesn't work 
https://github.com/WorldHealthOrganization/app/blob/master/docs/ROADMAP.md#v01
