### ISSUE TITLE
Home Screen shows a blank animation for countries having 0 daily National Cases

### ISSUE THREAD

**Issue by Mohit020888** [WorldHealthOrganization/app#1860]
1. Launch the app and complete onboarding journey and select any country which has 0 daily National Cases like Anguila.
2. Observe the home screen animation which switches between Global and National cases

Expected Behavior
0 Cases should be displayed for daily National cases instead of a blank animation

Actual Behavior
Blank animation is displayed for 0 daily National cases

System

- Device: Huawei Honor 7c
- OS: Android 8.0
- App Version: 1.0.0-staging(281)

Screenshots

https://user-images.githubusercontent.com/63721227/102721683-63f6cd80-4322-11eb-8002-d5b58c16ceb5.mp4

 Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by champ96k** [comment]
I can solve this issue, can you please assign me : )

**Comment by Mohit020888** [comment]
@champ96k - I have assigned it to you!
Please create a PR and get it reviewed by @brunobowden @theswerd

**Comment by champ96k** [comment]
@Mohit020888  Thanks for assigning me, I am currently working on this issue!

**Comment by champ96k** [comment]
This issue resolves and created a new pull request #1096
