### ISSUE TITLE
TestFlight for 1.0.0 (281) shows bruno as dev and old privacy policy

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1866]
Its unclear whether this is a testflight only bug.
The email is @brunobowden 's personal gmail and privacy policy is broken on whoapp.org

**Comment by brunobowden** [comment]
I saw the same issue but wasn't sure it was an update issue or not. Clearly it's not just me that's affected. I'll get this fixed.

**Comment by advayDev1** [comment]
Does the real app store have the real privacy policy?  Obviously I can't see the Nigerian app store.

**Comment by brunobowden** [comment]
I went through the App Store settings on a screen share, so I'm confident that has the right policy. At the same time, I can't see the App Store public listing. Raising the issue on TestFlight.

**Comment by brunobowden** [comment]
This is now fixed.... though they still need to create an email group for the new email address provided.
