### ISSUE TITLE
Deployment - app screenshots and image assets needed

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#187]
## iOS

Screenshots ([exact dimensions of all possible screenshots here](https://help.apple.com/app-store-connect/#/devd274dd925)):

- [x] 1 screenshot for iPhone 5.5" display (1242 x 2208 pixels (portrait) or 2208 x 1242 pixels (landscape))
- [x] 1 screenshot for iPhone 6.5" display (1242 x 2688 pixels (portrait) or 2688 x 1242 pixels (landscape))
- [x] 1 screenshot for iPad Pro (3rd Gen) 12.9" display (2048 x 2732 pixels (portrait) or 2732 x 2048 pixels (landscape))
- [x] 1 screenshot for iPad Pro (2nd Gen) 12.9" display (2048 x 2732 pixels (portrait) or 2732 x 2048 pixels (landscape))
- [ ] App Store Icon (1024 x 1024)

OPTIONAL for iOS
- [ ] Up to 10 screenshots and 3 [App Previews](https://help.apple.com/app-store-connect/#/dev4e413fcb8) for each device size

## Android

All files need to be JPEG / PNG ([more info on exact requirements](https://support.google.com/googleplay/android-developer/answer/1078870)).

- [x] 2 screenshots overall, which can be across any of the form factors (Phone / Tablet). Would be good to get 1 phone screenshot and 1 tablet screenshot.
  - Min length for any side: 320px. Max length for any side: 3840px.
- [ ] High-res icon, 512 x 512 32-bit PNG, has to be less than 1024 KB
- [x] Feature graphic, 1024px by 500px (#250) - https://user-images.githubusercontent.com/54385392/77468970-9becd680-6dcb-11ea-928f-ba402f3e1376.png

OPTIONAL for Android
- [ ] Promo graphic, 180 w x 120 h

**Comment by kassim** [comment]
<details><summary>taken on a Pixel 3 simulator (click to expand):</summary>
![Screenshot_1585071459](https://user-images.githubusercontent.com/11020264/77458801-0ec37500-6dff-11ea-877b-9a1c047b3060.png)
![Screenshot_1585071455](https://user-images.githubusercontent.com/11020264/77458825-1551ec80-6dff-11ea-81e0-dffb761764c5.png)
![Screenshot_1585071442](https://user-images.githubusercontent.com/11020264/77458826-15ea8300-6dff-11ea-8c36-2119d3360f87.png)
![Screenshot_1585071484](https://user-images.githubusercontent.com/11020264/77458829-16831980-6dff-11ea-9207-a43bb507d024.png)
![Screenshot_1585071502](https://user-images.githubusercontent.com/11020264/77458830-171bb000-6dff-11ea-84a5-d4b73fcc516f.png)
![Screenshot_1585071463](https://user-images.githubusercontent.com/11020264/77458833-171bb000-6dff-11ea-8e53-494c3b367ce7.png)
</details>

**Comment by pedmilrey** [comment]
Android - Pixel 4

![photo_2020-03-24_18-55-24](https://user-images.githubusercontent.com/12101087/77460227-1be16380-6e01-11ea-883e-500f73d1a09b.jpg)
![photo_2020-03-24_18-55-22](https://user-images.githubusercontent.com/12101087/77460231-1d129080-6e01-11ea-8d70-a01df099d70e.jpg)
![photo_2020-03-24_18-55-21](https://user-images.githubusercontent.com/12101087/77460232-1dab2700-6e01-11ea-9484-4c54a7540799.jpg)
![photo_2020-03-24_18-55-19](https://user-images.githubusercontent.com/12101087/77460234-1e43bd80-6e01-11ea-8bf7-ec8df7db288b.jpg)
![photo_2020-03-24_18-55-17](https://user-images.githubusercontent.com/12101087/77460236-1edc5400-6e01-11ea-82e4-2831c8bb0aa9.jpg)

**Comment by yourkompas** [comment]
Can edit any of these if needed!

**Comment by kassim** [comment]
<details><summary>taken on a Pixel C (tablet) emulator - click to expand</summary>

![Screenshot_1585074112](https://user-images.githubusercontent.com/11020264/77462848-f9514980-6e04-11ea-929e-0b031a1d923a.png)
![Screenshot_1585074101](https://user-images.githubusercontent.com/11020264/77462857-fbb3a380-6e04-11ea-9f2b-718861ef1f72.png)
![Screenshot_1585074095](https://user-images.githubusercontent.com/11020264/77462862-fc4c3a00-6e04-11ea-9e6d-7420e79ff1b4.png)
![Screenshot_1585074091](https://user-images.githubusercontent.com/11020264/77462864-fce4d080-6e04-11ea-9d57-15ad29330aee.png)
![Screenshot_1585074137](https://user-images.githubusercontent.com/11020264/77462865-fce4d080-6e04-11ea-8101-1f93b8b4656a.png)
![Screenshot_1585074084](https://user-images.githubusercontent.com/11020264/77462868-fd7d6700-6e04-11ea-8f22-e98adfd7c2cf.png)
![Screenshot_1585074129](https://user-images.githubusercontent.com/11020264/77462870-fe15fd80-6e04-11ea-8886-3ccd59ea1db9.png)


</details>

**Comment by ivancastrogw1** [comment]
ios screen shots 
[screen_shots_who_app.zip](https://github.com/WorldHealthOrganization/app/files/4377114/screen_shots_who_app.zip)

**Comment by ivancastrogw1** [comment]
[iPhone_5_5_app_preview.mov.zip](https://github.com/WorldHealthOrganization/app/files/4377120/iPhone_5_5_app_preview.mov.zip)

**Comment by yourkompas** [comment]
![App Store Screenshot - 5 5](https://user-images.githubusercontent.com/54385392/77467015-6a264080-6dc8-11ea-9b72-3b0ff4f628c4.png)
![App Store Screenshot - 6 5](https://user-images.githubusercontent.com/54385392/77467024-6db9c780-6dc8-11ea-8647-404a6c10f4db.jpg)

**Comment by yourkompas** [comment]
![Android](https://user-images.githubusercontent.com/54385392/77467585-7ced4500-6dc9-11ea-875c-3e4282ea68fd.png)

**Comment by yourkompas** [comment]
![iPad 2nd Gen](https://user-images.githubusercontent.com/54385392/77467686-b02fd400-6dc9-11ea-88ab-a37485e8f267.jpg)

**Comment by yourkompas** [comment]
![iPad-3rd-Gen](https://user-images.githubusercontent.com/54385392/77468479-d609a880-6dca-11ea-8dfc-14bd09852585.png)

**Comment by yourkompas** [comment]
![Android 2](https://user-images.githubusercontent.com/54385392/77468968-9b544000-6dcb-11ea-910b-8dd8dd9550de.png)
![Play Store Feature Graphic](https://user-images.githubusercontent.com/54385392/77468970-9becd680-6dcb-11ea-928f-ba402f3e1376.png)

**Comment by ivancastrogw1** [comment]
<details>
  <summary>iOS Screenshots</summary>
 
![iPad_Pro_(2nd_Gen)_12_9_landscape](https://user-images.githubusercontent.com/40570614/77472998-1130c980-6e15-11ea-84e4-793e9d7d0d33.png)
![iPad_Pro_(3rd_Gen)_12_9_landscape](https://user-images.githubusercontent.com/40570614/77473010-155ce700-6e15-11ea-8c6e-5788cbf9d4ce.png)
![iPhone_6_5_landscape](https://user-images.githubusercontent.com/40570614/77473012-15f57d80-6e15-11ea-8a4c-96ccd0e4503a.png)
![iPhone_5_5_landscape](https://user-images.githubusercontent.com/40570614/77473014-17bf4100-6e15-11ea-8de6-74dfe4ba17b9.png)
![iPad_Pro_(2nd_Gen)_12_9_portrait](https://user-images.githubusercontent.com/40570614/77473016-1857d780-6e15-11ea-84f7-7dfb1c7a32be.png)
![iPad_Pro_(3rd_Gen)_12_9_portrait](https://user-images.githubusercontent.com/40570614/77473021-19890480-6e15-11ea-887c-7c007e669191.png)
![iPhone_6_5_portrait](https://user-images.githubusercontent.com/40570614/77473022-1a219b00-6e15-11ea-8395-61f1c6fc7b76.png)
![iPhone_5_5_portrait](https://user-images.githubusercontent.com/40570614/77473023-1aba3180-6e15-11ea-907f-8c897106ea12.png)








</details>

**Comment by viviancromwell** [comment]
@yourkompas Kristina, is this done? If so, please close the ticket.

**Comment by brunobowden** [comment]
@yourkompas - thanks for the screenshots but we need to remove the border to satisfy the Apple App Store requirements. Reviewer feedback: _"No screenshots that are marketing the app, but rather, images of what’s within the app"_

FYI @hspinks @patniemeyer

**Comment by vikilinho** [comment]
Can I still drop screenshots for Android device.

**Comment by yourkompas** [comment]
[App Store Screenshots.zip](https://github.com/WorldHealthOrganization/app/files/4394503/App.Store.Screenshots.zip)
