### ISSUE TITLE
Deployment - text assets needed

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#188]
## iOS
- [ ] Name (0-30 chars)
- [ ] Subtitle (0-30 chars)
- [ ] Privacy Policy URL (#58)
- [ ] [Primary Category](https://developer.apple.com/app-store/categories/)
- [ ] Keywords (0-100 chars)
- [ ] Description (0-4000 chars)
- [ ] Contact info: first name, last name, email, phone number
- [ ] Fill out questionnaire for Age Rating

OPTIONAL for iOS
- [ ] Promotional Text (0-170 chars) (appears above description)
- [ ] Copyright text (such as  "2008 Acme Inc.")
- [ ] Secondary Category

## Android

- [ ] Title (0-50 chars)
- [ ] Description (0-80 chars)
- [ ] Full description (0-4000 chars)
- [ ] [Application Category](https://support.google.com/googleplay/android-developer/answer/113475), Tags
- [ ] Fill out questionnaire to get content rating
- [ ] Contact email
- [ ] Privacy Policy URL

OPTIONAL for Android
- [ ] Promo video (YouTube URL)
- [ ] Website URL
- [ ] Contact phone

**Comment by hspinks** [comment]
Closing the v0.1 version of this task, will open a separate issue for v1.0
