### ISSUE TITLE
Stats style and content changes

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#1916]
## Summary

For only home page:

1. Change to only "Global Total Cases" and "XXX_Country Total Cases", e.g. "Nigeria Total Cases"

For stats page:

2. Add at the bottom:
```
Data may be incomplete for the current day or week. Also see the website dashboard: https://covid19.who.int
```
3. For stats page, list the date below the numbers, e.g. 
```
7,393
Daily deaths
Dec 26
```

## Checklist:

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by theswerd** [comment]
Does anyone have a preference where the link to https://covid19.who.int should go? @brunobowden @Mohit020888

**Comment by Mohit020888** [comment]
@theswerd - I think at the bottom of the screen below Daily/Total Deaths unless @brunobowden has something else in mind.

**Comment by brunobowden** [comment]
Just updated description to have more detail
