### ISSUE TITLE
Investigate non-Ionic Implementation (Flutter or React Native)

### ISSUE THREAD

**Issue by sstur** [WorldHealthOrganization/app#193]
As per our discussion at this morning's standup (Sun 22nd Mar), I'm opening this issue to track the progress of alternate implementations, particularly React Native and Flutter.

I'll get a React Native prototype up (with help from @darcien) in the next few days that mirrors the features in the Ionic one, and I'll add a link to it here.

Also Ben (@theswerd) is doing a Flutter implementation with @patniemeyer (link in the comments).

**Comment by myiremark** [comment]
also @patniemeyer

**Comment by theswerd** [comment]
Flutter: https://github.com/theswerd/WHOFlutter

**Comment by sstur** [comment]
> Flutter: https://github.com/theswerd/WHOFlutter

This is awesome work!

I'll see about getting our code put up soon too.

**Comment by sstur** [comment]
Hey team!

Here's the entire repo for our React Native implementation:
https://github.com/kodefox/who-app-rn

Expo demo is in the readme of that repo.

Special shout out to @darcien for help with this, along with [a few other contributors](https://github.com/kodefox/who-app-rn/graphs/contributors).

**Comment by sstur** [comment]
Just an update on this, In standup today (Wed, 25th Mar) we decided to go forward with the Flutter implementation which has been submitted for review in the App/Play store. I'll close this issue for now but if anything changes in the future we can re-open.
