### ISSUE TITLE
v2 backend: create client flavor that uses v2 backend

### ISSUE THREAD

**Issue by rjhuijsman** [WorldHealthOrganization/app#1971]
## Summary

Currently, the v2 backends aren't used by our clients (Android, iOS) yet.

## Desired Solution

To begin using the v2 backends, the easiest approach might be to introduce a "flavor" for each v2 backend that we'd like to connect to.

## Additional Context

The v2 backends currently support the v1 API, so should be relatively straightforward to use in the existing app. However, unlike in v1 backends, for v2 the URLs at which to access the dynamic API endpoints are different from URLs that serve the static content. More details are available in the `server`'s [README](https://github.com/WorldHealthOrganization/app/blob/master/server/README.md).

**Comment by brunobowden** [comment]
@rjhuijsman - I wouldn't bother with a flavor at all. There's little usage of the dev servers, so we can just make a breaking change.
