### ISSUE TITLE
Need to purchase fonts

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#205]
Currently using national. 

If that is indeed what we are using in the long term, will need to make sure we purchase.

**Comment by epicfaace** [comment]
Even if we do purchase, that may cause some complications because we may not be able to check in the font file with the GitHub repository (since this repo is public).

**Comment by hspinks** [comment]
Per @viviancromwell note in Slack, we will use the free/system fonts on iOS and Android for now. Roboto on Android, San Francisco on iOS. Closing for now
