### ISSUE TITLE
Compare to the Fevermap app

### ISSUE THREAD

**Issue by ottok** [WorldHealthOrganization/app#209]
Hello!

There are also other similar open source app developments in progress. See the list we have compiled at https://gitlab.com/fevermap/fevermap/-/issues/1

Our Fevermap is about collecting fever and other potential Corona virus symptoms from the field to create situational awareness. Stack is a PWA app with Python/Flask backend. Works on all mobile platforms.

You might want to cross-check/benchmark with this, or even collaborate?

[![image](https://user-images.githubusercontent.com/668724/77352887-a0bc7680-6d48-11ea-8ecc-bc5aa4328eeb.png)](https://www.youtube.com/watch?v=7wqdTifGiPc)

**Comment by myiremark** [comment]
Thanks for your interest and suggestion!

Closing this issue to maintain a centralized list at:

https://github.com/WorldHealthOrganization/app/issues/324
