### ISSUE TITLE
Restrict app to iPhone (not iPad), portrait mode

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#210]
To restrict to iPhone (not iPad), we would need to do this: https://stackoverflow.com/questions/24927716/how-to-restrict-the-ios-app-only-for-iphone-excluding-ipad

**Comment by hspinks** [comment]
this feels a bit hacky to me... I think for the purposes of initial submission, this is fine, but longer term I think we'll want to just support iPad screen sizes. but up for discussion on that one

**Comment by hspinks** [comment]
Per the discussion in standup today, we can probably submit without thinking about the iPad screen size quite yet. Noting that this is a risk item for app store approval, this may end up being an immediate priority and pushed back into this milestone. But for now, moving to v0.2

**Comment by huxaiphaer** [comment]
Is this task already taken?

**Comment by advayDev1** [comment]
I know of no plan at this time not to launch on iPad
