### ISSUE TITLE
Change wording from "World Health Organization App"

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#218]
Right now, the description for the repo says "World Health Organization App" and the README says "This is the official World Health Organization app." We should make it clear that this is not the official app for the WHO, but rather a WHO app focused on the coronavirus pandemic.

**Comment by ctrimm** [comment]
Made an attempt at updating the text in the README.md. Welcome any and all feedback on that open PR.

**Comment by advayDev1** [comment]
This is still something very much in flux right now and there aren't decisions.
