### ISSUE TITLE
Ingest assets from design team

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#22]
Once someone has initial, properly licensed (MIT/Public Domain), assets let's get them checked in.

**Comment by advayDev1** [comment]
Due to the excessive constraints at https://www.cdc.gov/other/agencymaterials.html not going to check in the CDC diagrams at this point.

**Comment by hspinks** [comment]
I'll close this for now as we can communicate design specs & assets per specific ticket and/or more generally over Slack & Figma
