### ISSUE TITLE
Support YouTube video embeds in informational content

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#225]
Brought up as a desired future feature during one of the standups

**Comment by kassim** [comment]
appears to be a Flutter plugin for that https://pub.dev/packages/youtube_player_flutter

is there some sort of design for how this may be included?

**Comment by dhruvilp** [comment]
Instead of using _youtube_player_flutter_ I would recommend to use https://pub.dev/packages/webview_flutter (by flutter team) and embed youtube videos in the app. I can easily do it.

**Comment by json469** [comment]
What would be the reason for using the [webivew_flutter](https://pub.dev/packages/webview_flutter) other than it is built and maintained by the Flutter team? Although we should prefer the safe and tested approach, the YouTube video via webview may not provide the most pleasant UX (with the whole page visible). If we are simply embedding a video for information-delivery sake (read-only) we should stick to a package like [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter) that could render the video on its own.

Either way, I think we should identify/define the requirement on how the YouTube video embeds be used before we choose what dependency to introduce 😃

**Comment by dhruvilp** [comment]
Since "The plugin uses webview_flutter under-the-hood to play videos", I feel like using webview_flutter by ourselves would make resolving upcoming issues easy in the long run. webview_flutter is pretty powerful and doesn't serve as typical native webview plugin so we'll see what's the requirements and decide later 👍

**Comment by advayDev1** [comment]
Lets see what some of the ui updates look like before implementing
