### ISSUE TITLE
Fix carousel slide indicators not showing on iOS

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#231]
The dots at the bottom of the slides indicating which slide the user is on are not displaying when running the app on iOS, even though they are when running the app in the browser. See screenshots...

iOS Simulator (iPhone 11 Pro Max, iOS 13.3):
<img width="485" alt="Screen Shot 2020-03-23 at 7 46 25 PM" src="https://user-images.githubusercontent.com/1484366/77399206-31557f80-6d66-11ea-95fd-d5f5eadc197b.png">

Browser:
<img width="266" alt="Screen Shot 2020-03-23 at 7 48 57 PM" src="https://user-images.githubusercontent.com/1484366/77399220-374b6080-6d66-11ea-932f-1a2e749b090f.png">

**Comment by hspinks** [comment]
This might be related to #152 as it looks like all content is pushed down on the screen

**Comment by WillGoad** [comment]
Might be a restraints problem

**Comment by WillGoad** [comment]
@hspinks I'm pretty unexperienced with Github what is the process for fixing an issue.

**Comment by epicfaace** [comment]
The carousel dots only show intermittently when I run it on the browser as well -- sometimes I have to refresh a few times for the dots to show. This hints that it might be an issue with the actual Ionic carousel component -- maybe we should use another library to render the carousel.

**Comment by WillGoad** [comment]
That might be best.

**Comment by WillGoad** [comment]
I would like to be assigned to this issue if no one else is already.

**Comment by hspinks** [comment]
@WillGoad you've got it, thanks!

**Comment by patniemeyer** [comment]
@WillGoad This problem may also be worsened by th app not respecting the "safe areas" on iOS.  I'm not sure if our current layout has an easy way to add that but it may fix the problem and improve the layout in general.

**Comment by WillGoad** [comment]
Yeh I’ll try and find the guidelines for borders
