### ISSUE TITLE
Dynamic content delivery that supports offline use

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#24]
One dead simple choice:
1. A YAML file with the headings, titles and images, and control flow of options.
2. Each app store update we bake in the most recent YAML.
3. Check access to our site for updated YAML and remote load it if available on start.
4. All assets baked in for the baked YAML, YAMLs online use remote assets too.

I'm sure there are frameworks though.

Keep it simple in v0.1, or go extensible in the beginning?  Thoughts?

**Comment by hspinks** [comment]
Closed in #588
