### ISSUE TITLE
A more intuitive and simplified content swipe

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#240]

**Comment by viviancromwell** [comment]
here is a potential design direction that is more intuitive, also highly recommended by Material Design as the best choice. is to show a strip of content so no gesture icon is needed.  I am showing an example here.  

In this design.
1) user doesn't need to show > arrow gesture.
2) we can get rid of the dots too.
3) the only thing needed is the close window button. as the entire content strip is overlaying on top of the main screen.

this should be considered in the next iteration.

![A better content swipe](https://user-images.githubusercontent.com/247863/77433776-10f4e780-6d9d-11ea-8a7e-924815ccb27b.png)

cc @hspinks

**Comment by m3teitel** [comment]
Hey, I can help implement this. It should be pretty straight forward with a page view and having the close button in the corner.

**Comment by hspinks** [comment]
Closing as design will update for next version
