### ISSUE TITLE
Final Internal Test Pass for v1.0

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#243]
QA for v1.0:

Write up test plan for mobile app and then add it to `docs/TESTING.md`. It should include the following + add your own elements. This is to focus on manual testing for now and then we'll migrate to automation in the future.
- iOS, Android
- OS: iOS 8 to iOS 13 and Android 4.1.x to 10.0
   Android needs more testing given greater fragmentation
- All user interface elements + hand washing animation in "Protect Yourself"
- No internet connection and poor internet connection
- Aggregate all feedback from the comments on this issue
- Add here

Execute test plan across range of devices, operating systems and try to break it. Please file issues in GitHub and describe scope and severity.

**Comment by viviancromwell** [comment]
@avardhana

**Comment by brunobowden** [comment]
@rmspeers - please take a look at this, I think we can reassign it to you once you comment on it

**Comment by advayDev1** [comment]
I think we should have a combination of at least the following factors:

* Platform
  * Android
  * iOS
* Network connectivity
  * No network
  * Fast normal network
  * Intentionally slow/lossy network
* Notification permission
  * Skip on the app screen
  * Accept on app screen, accept on the OS screen (on Android, OS doesn't ask)
  * Accept on app screen, reject on the OS screen (iOS only)
* Location permission
  * Skip on the app screen
  * Accept on app screen, accept on the OS screen "only once" usage
  * Accept on app screen, accept on the OS screen "when app in use" usage
  * Accept on app screen, reject on the OS screen
* Location services
  * Services disabled at OS level, but you turn them on when the OS asks you to
  * Services enabled at OS level, and you keep them off then the OS asks you to
* Analytics
  * No analytics before ToS screen passed
  * Analytics after ToS screen passed
  * No analytics after settings opted out

**Comment by rmspeers** [comment]
Commenting on this per request. Happy to discuss what a security test plan (which may be separate from what QA is looking at from a feature perspective) looks like.

**Comment by brunobowden** [comment]
@Mohit020888 will be doing this tomorrow

**Comment by brunobowden** [comment]
Still needs more work but @Mohit020888 has covered this for the launch.
