### ISSUE TITLE
What does users want? - early user research

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#244]
We have been getting lots of suggestions from different directions. But we haven't even looked into what users want. There are multiple channels we should do a bit research to get better insights.

1) apps built by other health organizations, what they built, how users respond in-app review
2) China has the most information,  as they are far ahead than everyone else and have built the technology platform. they could provide great insights. ( plus they are open sourcing the tech)

**Comment by avardhana** [comment]
I can get started on consolidating competitive research and looking into China's apps

**Comment by viviancromwell** [comment]
sounds good. I assigned to you, share with me, as I have started bits..,

**Comment by avkvirtru** [comment]
Happy to assist in any ongoing research effort.

**Comment by advayDev1** [comment]
This is not an actionable task.
