### ISSUE TITLE
FYI - join discussion on Slack

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#25]
Hey all, heads up that there is a Slack set up for this project: https://join.slack.com/t/who-app/shared_invite/zt-cq5agryq-GDRTN4bU284Z7PPZZiEIvA

(side note - @SamMousa can you please install the Slack app for this Github repo so we can integrate the two and have all notifications in one place?)

**Comment by brunobowden** [comment]
I installed the Slack App for GitHub
