### ISSUE TITLE
Deployment - feature graphic

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#250]
We need to make a feature graphic for submission to the Play Store. It needs to be 1024px by 500px

Part of #187

**Comment by yourkompas** [comment]
Can do as soon as I see the Android screenshots come through

**Comment by epicfaace** [comment]
finished by @yourkompas 

https://user-images.githubusercontent.com/54385392/77468970-9becd680-6dcb-11ea-928f-ba402f3e1376.png
