### ISSUE TITLE
Meta: decide on one place for volunteer/roster submissions?

### ISSUE THREAD

**Issue by RohanTalip** [WorldHealthOrganization/app#258]
There are currently 2 places where people can submit their information for indicating their interest in contributing to the project.

One is via a [form](https://docs.google.com/forms/d/e/1FAIpQLSetEzaANtzTcrUzEKcjKzwH8HVKRMvMGUQ6GmRlAzBsSTCsRw/viewform) that I *think* submits to this [spreadsheet](https://docs.google.com/spreadsheets/d/1U6bHVExMRXNXh65WUVSmfV_nGlfSV3Ib9hHD2WLwOYY/edit) (I don't have access to the spreadsheet, even though I have requested access).   The form is referenced from the [wiki](https://github.com/WorldHealthOrganization/app/wiki) but probably somewhere else that I don't know about too (maybe in emails sent to people?).

Another is this [spreadsheet](https://docs.google.com/spreadsheets/d/1jt4xrXWUnsh8DmtawNV4XGBj8RAdgn-d7ckgL2qEXPM/edit) that is referenced from the [onboarding](https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md) document.

I suggest that we should just have one location where people submit their information, and that the information is visible at least to people working on this app.  Ideally we would remove links to the other.

Thoughts @asianfoodlab , @brunobowden , @advayDev1 , @csfurmanski ?

See also issue #48 by @csfurmanski

**Comment by myiremark** [comment]
closing the other issue, so there's one place to keep track of this.

**Comment by hspinks** [comment]
Sticking with this one for now: https://forms.gle/FUugWvUVvMcV3dLJA
