### ISSUE TITLE
All pages are blank on Safari

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#263]
Going to https://preview.whoapp.org or https://preview.whoapp.org/about give me an error, "Can't find variable: Intl"

Safari version 9.1.2

Solution: we need to add a polyfill for Intl.

**Comment by hspinks** [comment]
Will this be relevant when run inside the native container with capacitor? That may standardize the environment a bit so we don't need a polyfill. Not sure on that, but worth checking

**Comment by pjayathissa** [comment]
FYI: Safari v 13.0.5 works fine
