### ISSUE TITLE
implement the "about the app" page

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#266]
The design is in figma. very simple stuff.

Feel free to consolidate all of the content there from your side as well. 

attached is a screen shot. The font is smaller.

![About the App - Page (1)](https://user-images.githubusercontent.com/247863/77480810-a1ecb280-6ddf-11ea-8f41-7aac0c324992.png)

**Comment by hspinks** [comment]
@viviancromwell I believe we need to list license info and contributors (correct @advayDev1?). can you include those? see the [current preview](https://preview.whoapp.org/about) for what's included in that

**Comment by myiremark** [comment]
per discussion, will continue and style current preview to match current preview + figma

**Comment by viviancromwell** [comment]
@myiremark @hspinks that is the plan to merge the content you have with the design-related information. I didn't feel I need to pull all of the existing static content into Figma, the engineer can just combine them. If you have a google doc that captures the content you have, I will add mine, then add that link to Figma, I feel this is better than trying to copy the entire static content into the design.  Also the content is likely to change, so it is better to keep it off from the design. thoughts?

**Comment by myiremark** [comment]
Yes, as long as there is content, when changed, is static.

**Comment by advayDev1** [comment]
@viviancromwell can we just put all the legalese right after the donation with the designed part front and center?
