### ISSUE TITLE
Fill in security checks in the RELEASE document

### ISSUE THREAD

**Issue by shankari** [WorldHealthOrganization/app#269]
Review feedback was to file an issue and link it to the RELEASE document.

**Comment by shankari** [comment]
@advayDev1 please assign to Andrew per https://github.com/WorldHealthOrganization/app/pull/257/files#r397437296

**Comment by anebus** [comment]
### Security Checks (Validate Documents Match Reality; Review Changes)
- [ ]  **System Boundary** 
- Diagram of internal services, components, connections to external services and systems.
- _This may match item in Product Check - "fidelity checks with mockups (design)"_

- [ ] **APIs and Interconnection** (external systems and services)
- Data types transmitted to, stored by, or processed by the API or system/service. Data categorization/impact assessment 
- Connectivity Details (Protocols/Ports, Encryption)
- Note Agreements (SLAs or licenses)

- [ ] **Infrastructure** 
- List of IaaS services (compute, network, storage, etc)

- [ ] **Data Flow**
- Identify where data is to be processed, stored, or transmitted
- Delineate how data comes in and out of the system boundary
- Any notes for privileged and non-privileged access

- [ ]  **Cryptography**
- Validate: Data at Rest
- Validate: Internal Transmission
- Validate: External Transmission

**Comment by shankari** [comment]
I should really come up with a better name for _fidelity checks with mockups (design)_. What I was trying to capture was the note below it

> sometimes, engineering slightly changes the mockups for ease of implementation/scalability. Unit or integration tests won't catch this since they are focused on functionality. Design needs to have a final check to verify that such modifications (if any) work with the overall design.

**Comment by anebus** [comment]
Understood. Edited mine to remove that then. System boundary here is a visual system architecture. I'll do a sketch of what I understand 0.2 to look like and folks can comment on it as we build. Intent here would be confirmation that the diagram matches and has not changed by adding or removing components to the system in future releases.

**Comment by shankari** [comment]
@anebus do you have thoughts on where the responses to these questions should be stored.
My proposal is that they should be checked in to GitHub as usual so that they can be tagged along with the other release deliverables.
And then the checkoff process will involve ensuring that all of them have been answered.

Thoughts?

**Comment by anebus** [comment]
@shankari That makes sense to me, also allows for transparency to the person that validated the steps.

**Comment by shankari** [comment]
Update docs, closing
