### ISSUE TITLE
Handle the deployment of the apps in China

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#27]
This requires some investigation if you want to deploy the app in China, you need to deploy to 6-7 different ones to cover the majority of the users. 

potential contact person:
https://twitter.com/shuding_
https://twitter.com/youyuxi

**Comment by hspinks** [comment]
I'm going to close this for now. On this morning's call, it sounded like release in China is not a goal in the near future. We can come back to this if that changes!
