### ISSUE TITLE
Figure out process for getting WHO approval

### ISSUE THREAD

**Issue by shankari** [WorldHealthOrganization/app#274]
As per PR feedback.
@advayDev1 please assign to @brunobowden as per https://github.com/WorldHealthOrganization/app/pull/257#discussion_r397486096

**Comment by brunobowden** [comment]
iOS app store process figured out
Google Play out for review

**Comment by shankari** [comment]
@brunobowden I checked through the release channel and it looks like the Google Play was stuck in Google's Play store review process. What I'm looking to document here is what check-offs (if any) WHO needs to do before they accept the app from us.

Concretely, it looks like the current process is:

```
                  (1)         (2)
App collective -------> WHO -------> App stores
```

I'm trying to document (1) here. Presumably WHO is going to document (2) and we don't have to handhold them for every release.

**Comment by brunobowden** [comment]
@shankari - most of this is fixes in the app and WHO getting comfortable with the process. Once they've been successful with a Google Play submission, then I'll consider this fixed

**Comment by shankari** [comment]
ok, I will remove the WHO checkoffs step from the release process checklist.
