### ISSUE TITLE
Figure out release SCM managment

### ISSUE THREAD

**Issue by shankari** [WorldHealthOrganization/app#279]
Everybody has an opinion, but we need to standardize on one.

Some questions?
- release branches or tags?
- how many branches?
- does it need to support hotfixes?

**Comment by shankari** [comment]
Suggested by @hspinks 

[gitflow model](https://nvie.com/posts/a-successful-git-branching-model/)
uses a develop branch separate from master - essentially the feature branches that people are working on would branch off of (and be merged back into) develop instead of master. then, to get code from develop to master, it would go through the release/\<version\> branch flow

**Comment by epicfaace** [comment]
What we've been following at the moment is that we keep all development on master. When we release a new version, @hspinks has been creating a new tag and then creating a new Release with notes on the Releases page: https://github.com/WorldHealthOrganization/app/releases

**Comment by hspinks** [comment]
We are not following the gitflow model strictly as we are not using a separate dev branch, but we have been using release branches for this, e.g. `release/v0.4.0`. On the release branch is where we have been doing any last changes for distribution, like bumping version number or copying in prod configuration files. Then, as Ashwin notes, we create a new tag for the release
