### ISSUE TITLE
Figure out privacy checklist for release

### ISSUE THREAD

**Issue by shankari** [WorldHealthOrganization/app#280]
We need to have a privacy checkoff. Not sure who should come up with the list for consideration.

**Comment by myiremark** [comment]
Generally, we are using this for guidance:

http://www.oecd.org/sti/ieconomy/oecd_privacy_framework.pdf

To that end, for each of the following categories (at least), we should review and document our thoughts and measures for addressing each.

**Comment by shankari** [comment]
@myiremark maybe my brain is too fried right now, but I'm not seeing any categories listed. Do you mean the ones on page 3? Because those seem to be changes that motivate the need for such a framework.

**Comment by myiremark** [comment]
Its actually on this page:

http://www.oecd.org/internet/ieconomy/oecdguidelinesontheprotectionofprivacyandtransborderflowsofpersonaldata.htm

**Comment by myiremark** [comment]
Updated my comment for clarity

**Comment by shankari** [comment]
Updated #257 with this information
