### ISSUE TITLE
Asset management workflow

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#281]

**Comment by viviancromwell** [comment]
I think a better way to manage assets in the future, is we come up with a directory structure, assets checked indirectly into Github.  Then in github, if there is a specific ticket, just add link to the assets instead of adding the image directly.


@hspinks thoughts.  I can ask @davidkaneda to work on that.

**Comment by viviancromwell** [comment]
something like this. https://github.com/WorldHealthOrganization/app/issues/281

**Comment by davidkaneda** [comment]
I'd lean toward just using Dropbox/Drive if possible. I understand the accessibility benefit of having everything in GitHub for eng, but certain binary files can weigh down Git history, and it also requires graphics contributors to know git. If we just keep in Dropbox/Drive, I'd think we could keep the directory public, so would still be easy to link to(?)

**Comment by dnfield** [comment]
Another option is to use git-lfs, which helps manage binary files separately (but does require users to install additional software).

**Comment by json469** [comment]
I would recommend git-lfs as well (most developers would have had experience or have it) and will save us from the additional effort to synchronise and look after the assets.

I would be happy to help set it up 👍

**Comment by advayDev1** [comment]
Please let us know how you'd like to manage assets going forward.  As long as everything is appropriately licensed, we're happy to have design team simply make PRs pushing assets into a repo directory and eng will link it into the right places as needed.

**Comment by davidkaneda** [comment]
Still don't think it makes sense for how/where designers work (don't think designers should have to create PRs), but as far as where we're hosting production assets for the app, I defer entirely to eng.

**Comment by advayDev1** [comment]
I think we need the following in terms of workflow:
* A location for signed-off assets (wherever you want to store them)
* A consistent way to inform us that signed-off assets are a) newly available and also b) have changed, so eng can make the correct PRs

Can we use bugs against engineering to do this @davidkaneda ?  Whenever designers have new or modified assets you file a new GH issue with the location of new assets, and Eng will take care of getting them into the build?

**Comment by advayDev1** [comment]
SG I’m resolving this now :)
