### ISSUE TITLE
Define OECD Privacy principles

### ISSUE THREAD

**Issue by myiremark** [WorldHealthOrganization/app#283]

**Comment by anebus** [comment]
The Security and Privacy groups use these principals to determine when a change to the app needs review or to update the security documentation.

The privacy principles defined by the OECD consist of the following:

**Collection Limitation**:
Data collection should occur only with the knowledge and consent of a concerned individual (data subject).

**Data Quality**:
Only collect information which is relevant and accurate for a particular aim.

**Individual Participation**:
The concerned individual should know if their information has been collected and must be able to access it if such data exists.

**Purpose Specification**:
The intended use for a particular piece of information must be known at the time of collection.

**Use Limitation**:
Collected data must not be used for purposes other than the ones specified at the time of collection.

**Security Safeguards**:
Reasonable measures must be taken to protect data from unauthorized use, destruction, modification, or disclosure of personal information.

**Openness**:
Individuals should be able to avail themselves of data collection and be able to contact the entity collecting this information.

**Accountability**:
There needs to be a dedicated person/team accountable for making sure these principals are upheld.
