### ISSUE TITLE
Eject from expo or not?

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#29]
The current scaffold uses Expo: https://expo.io/

Expo builds on top of react-native, but we can always downgrade (or "eject") from Expo.  The main benefits of rapid dev in Expo is how quickly you can iterate and distribute to non-eng stakeholders.

(If we ditch React-Native this is not important)

**Comment by myire** [comment]
@advayDev1 I think we can close this as well.

**Comment by hspinks** [comment]
Closing for now as we're using Ionic React
