### ISSUE TITLE
Functioning shortlink for app share

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#291]
https://www.who.int/covid-19-app is the link for now

**Comment by advayDev1** [comment]
Have to make sure WHO supports the shortlink.

**Comment by patniemeyer** [comment]
This was noted in the app store review: 

"... the “Share the app” button does not yet function properly. We’ll need for that to function first if you indeed want this version to go live on the App Store."

I assume what they meant was that it was that the shared content was not correct?  I think we can get the app store id now and generate a real link.

**Comment by theswerd** [comment]
I propose Firebase dynamic links. They work great, allow for easy AB testing, and I can implement them in under 3 hours if I have a google-services.json and google-services.plist file from firebase/google cloud

**Comment by theswerd** [comment]
Should I loop bob lee in on this conversation so he can give me read rights on the console

**Comment by brunobowden** [comment]
@theswerd - @crazybob is a Firebase fan as am I but we're still working on setting up the server side account. Once that's operational, then this seems like a good approach. To be done properly, it should use a who subdomain... but Bob may need to set that up anyway for Firebase.

For the time being, I've asked WHO to create a web page similar to what they do for other apps. I realize this is sub-optimal but will at least get us started:
https://www.who.int/health-topics/hearing-loss/hearwho

**Comment by patniemeyer** [comment]
@advayDev1 We'll need to reference this link from the prompt for app upgrade when that content schema checking PR is merged.

**Comment by hspinks** [comment]
per @crazybob, we can use https://whocoronavirus.org/app as the link from the client side
