### ISSUE TITLE
Update onboarding docs to reflect switch to flutter

### ISSUE THREAD

**Issue by shankari** [WorldHealthOrganization/app#292]
Apparently, the app now uses flutter instead of ionic react.
However, the [onboarding docs](https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md#building-and-running) still refer to ionic react.
They need to be updated with new instructions

**Comment by kavinda1995** [comment]
Those updates have been done i think.

![image](https://user-images.githubusercontent.com/19621533/77757165-b71f4680-7056-11ea-89ed-6d895d9ec411.png)

**Comment by shankari** [comment]
Fair enough.
