### ISSUE TITLE
Implement automated tools to enforce code style

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#30]
I think we should standardize the code style early and set up automated tools to check / correct code style.
We'll be dealing with lots of contributions and verifying them will most likely be the bottleneck. Cognitively it'll be more efficient to have 1 style throughout the codebase.

**Comment by advayDev1** [comment]
One suggestion if we're sticking with typescript: gts (opinionated, and uses prettier underneath)

**Comment by SamMousa** [comment]
Opinionated is good for moving quickly.

**Comment by theswerd** [comment]
Can I build this?

**Comment by SamMousa** [comment]
Fine with me!
