### ISSUE TITLE
UI Overlap on large text

### ISSUE THREAD

**Issue by kassim** [WorldHealthOrganization/app#303]
there's some UI overlap of text overlapping the pager indicator when checking on a Nexus 5 emulator

it doesn't overlap on iPhone 8 but there is a margin issue, I'm not sure if that will block release

<details><summary>Android Nexus 5 (1080x1920 pixels) - click to expand</summary>

![Screenshot_1585136324](https://user-images.githubusercontent.com/11020264/77532950-36b1e780-6e96-11ea-835b-7d24cc727fab.png)

![Screenshot_1585136488](https://user-images.githubusercontent.com/11020264/77532945-33b6f700-6e96-11ea-8f8c-92b53efe39fc.png)

</details>

<details><summary>iPhone 8 simulator - click to expand</summary>

![Simulator Screen Shot - iPhone 8 - 2020-03-25 at 12 45 39](https://user-images.githubusercontent.com/11020264/77533401-17678a00-6e97-11ea-8de8-e3087c8d498d.png)

</details>

**Comment by dnfield** [comment]
I can work on this.

**Comment by hspinks** [comment]
Closing as design has changed
