### ISSUE TITLE
Simplify language in splash-carousel content

### ISSUE THREAD

**Issue by jernst** [WorldHealthOrganization/app#308]
Currently very long sentences with many clauses ("college-level English"). We want this to be accessible to everybody. Suggestions:

* ``COVID-19, also referred to as "Coronavirus", mainly spreads from person-to-person between people who are in close contact with one another (within about 6 feet or two meters) through respiratory droplets produced when an infected person coughs or sneezes.``
=> ``COVID-19, also called "Coronavirus", easily spreads from one person to another when they are in close contact. Keep a distance of least 6 feet, or 2 meters, from others. Stay away from people who cough or sneeze.``

* ``Wash your hands often with soap and water for at least 20 seconds, especially after you have been in a public place, or after blowing your nose, coughing or sneezing.``
=> ``Wash your hands often with soap and water. Scrub for at least 20 seconds. Wash your hands every time after you have been in a public place, or after blowing your nose, coughing or sneezing.``

**Comment by hspinks** [comment]
This is a great suggestion! Currently, we are using the language directly from WHO to simplify the approval process. This is definitely something to keep in mind for future iterations, though.

**Comment by advayDev1** [comment]
Closing because this specific feature no longer exists; however, ensuring that our content remains broadly understandable is imporant.
