### ISSUE TITLE
Document Dependencies

### ISSUE THREAD

**Issue by myiremark** [WorldHealthOrganization/app#313]

**Comment by britannio** [comment]
Just the Flutter dependencies in `pubspec.yaml` which refer to the packages used directly by the app or all services we're using e.g. Fastlane, Netlify, GitHub actions, etc and their respective dependencies?

**Comment by anebus** [comment]
A little of both (others might fall under #312 -- within the boundary of the application #309 (basically, where data might flow to or what could impact confidentiality, integrity, or availability). This describes application connections and lets the security team understand what changes from version to version as a place to review changes. Basic principals are here: #283.

**Comment by britannio** [comment]
The current Flutter package dependencies are below however they're rapidly subject to change as new features are added

- [share](https://pub.dev/packages/share) 
- [url_launcher](https://pub.dev/packages/url_launcher)
- [page_view_indicator](https://pub.dev/packages/page_view_indicator)
- [intl](https://pub.dev/packages/intl)
- [flutter_localizations](https://github.com/flutter/flutter/tree/master/packages/flutter_localizations)
- [pedantic](https://pub.dev/packages/pedantic)

**Comment by brunobowden** [comment]
worthwhile documenting for security review but not a blocker on v1

**Comment by advayDev1** [comment]
I don't think this is an actionable task.  Our code dependencies are listed in our gradle and pubspec files for server and client.
