### ISSUE TITLE
Document Data Flow

### ISSUE THREAD

**Issue by myiremark** [WorldHealthOrganization/app#314]

**Comment by britannio** [comment]
Does this rely on the plans for dynamic content delivery to be finalized? https://github.com/WorldHealthOrganization/app/issues/326

**Comment by brunobowden** [comment]
worthwhile documenting for security review but not a blocker on v1

**Comment by advayDev1** [comment]
Please file a specific bug if something is missing from https://drive.google.com/file/d/1BMEyOnVAvJkr0Rd8XB7DKELWiFKvQZRx/view?usp=sharing
