### ISSUE TITLE
Fastlane Automation

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#318]
https://fastlane.tools/
* GitHub Actions for CI integration
* Meta data for Google Play and App Store
* Meta data for app permissions, e.g. `NSLocationWhenInUseUsageDescription`
* Screenshot automation
* App Store and Google Play binary upload
* Localization support

**Comment by SamMousa** [comment]
Since we have many new contributors looking for stuff to do I have de-assigned myself from this.

If you have experience setting up fastlane feel free to go ahead and comment here and you will be assigned.

**Comment by augustinreille** [comment]
Hey, I'm interested. I already worked with fastlane to deploy and maintain a dozen of apps on both stores.

**Comment by kassim** [comment]
@augustinreille can you join the Slack channel? (see https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md)

**Comment by SamMousa** [comment]
Will assign it to you later today

**Comment by brunobowden** [comment]
@augustinreille - thanks for working on this. It would helpful to get to know you, please email me at github@brunobowden.com

@KrauseFx may be able to help out this week (Fastlane author)

**Comment by joshdholtz** [comment]
👋 Hello! Looking forward to jumping in to help with the fastlane setup 😊 Are there requirements for this issue on what all needs to be done? 

## Thing to consider
- What CI platform are we using? (I usually prefer CircleCI but not sure if there is any other preferred)
- Are we looking to send this to Google Play and the App Store with fastlane? Or are we just looking to build the binaries?
- Do we need to meta data to Google Play and App Store?
- Do we need to take automated screenshots for Google Play and App Store?

I probably have more questions but we will start with these for now 😇

**Comment by hspinks** [comment]
@joshdholtz awesome! really appreciate you jumping in to help. Initial answers to your questions are below, and feel free to shoot with any more 😄 

> What CI platform are we using? (I usually prefer CircleCI but not sure if there is any other preferred)

We're currently using GitHub Actions for CI. We're trying to keep as much as possible on GitHub so we don't have to configure access across multiple services.

> Are we looking to send this to Google Play and the App Store with fastlane? Or are we just looking to build the binaries?

We are sending to the Google Play and App Stores using the WHO accounts, and it looks like they use fastlane internally to send to the stores. So ideally we would hook into their existing processes. I can dig in a bit more to find out what their processes are.

> Do we need to meta data to Google Play and App Store?

I think it's a good idea to keep our metadata in the repo and automated through fastlane. We'll need to localize our app store listings, so process-wise with our localization team, having all of our metadata in source control to send to the app stores seems like a good plan.

> Do we need to take automated screenshots for Google Play and App Store?

I think that would be a huge help! I think we're interested in including custom titles and backgrounds with the screenshots, e.g. using [this functionality](https://docs.fastlane.tools/getting-started/ios/screenshots/#put-your-screenshots-into-device-frames)

**Comment by joshdholtz** [comment]
@hspinks Awesome! Thanks for the quick reply ❤ Getting intro-ed to someone who could hook me up with the credentials I need to sign and upload to both Google Play and App Store would be amazing. That is probably the biggest blocker for me at the moment.

Do you also know if we have access to running macOS GitHub actions with this organization?

**Comment by hspinks** [comment]
@joshdholtz we should have access to macOS GitHub Actions 👍

**Comment by brunobowden** [comment]
@joshdholtz - I've edited the issue description to summarize all the elements. Feel free to edit further. Store permissions is a sensitive issue with WHO, so we'll need to work towards that. In the mean time, can you do develop and test with a personal account? Of course don't check your credentials in to the repo. Feel free to break up the work in to smaller parts and do them in whatever order makes most sense to you.

Part of this is that we want to able to do the whole app store release process automatically without needing any personal access to the app stores. We're working towards CODEOWNERS access to limit this properly but it's still a work in progress. Happy for your pointers on that too.

@sapte91 - FYI for Shilpa, our localization lead
