### ISSUE TITLE
Carousel page indicator overflow

### ISSUE THREAD

**Issue by dnfield** [WorldHealthOrganization/app#320]
The carousel dots at the bottom of the screen do not scale to handle large numbers of pages.

This is confusing when there are additional facts to view but the dots seem to indicate you are at the end.

This screen shows the indicator at the last dot, even though there are more pages:

![flutter_01](https://user-images.githubusercontent.com/8620741/77598194-683ea900-6ebe-11ea-85c9-3f04f6cf9655.png)

Here's what it looks like when you keep swiping to the new page:

![flutter_02](https://user-images.githubusercontent.com/8620741/77598206-6d9bf380-6ebe-11ea-9246-6b9676eeb789.png)

**Comment by richikchanda1999** [comment]
I have solved this issue but I am not a part of the project as of now.
Should I send a PR or is there a way I can contribute as well?

I have already filled the Google Form.

**Comment by hspinks** [comment]
Closing as design has changed
