### ISSUE TITLE
Other Projects

### ISSUE THREAD

**Issue by myiremark** [WorldHealthOrganization/app#324]
We welcome contributions and ideas!

In order to keep a centralized list, please add a comment below.

Other issues will be closed and redirected here in order to keep this streamlined.

Please don't use link shorteners for URLs.

**Comment by myiremark** [comment]
from @ottok:

```
There are also other similar open source app developments in progress. See the list we have compiled at https://gitlab.com/fevermap/fevermap/-/issues/1

Our Fevermap is about collecting fever and other potential Corona virus symptoms from the field to create situational awareness. Stack is a PWA app with Python/Flask backend. Works on all mobile platforms.

You might want to cross-check/benchmark with this, or even collaborate?
```

**Comment by myiremark** [comment]
from @avi33tbtt:

https://github.com/WorldHealthOrganization/app/issues/157

```

    https://docs.google.com/presentation/d/1E2fbiX3KW2VNBMy1C6lNxp_ffgze1s86t8Kd-3bZHEc
    https://github.com/TheSciFiMed/Covid-FLutter/blob/master/README.md
    https://docs.google.com/document/d/1xMH5ysJeDQhHbYjFa8xpVroJpPamuaLDx6PJVpWkmEA
    avi33tbtt@gmail.com
```

**Comment by shankari** [comment]
@myiremark I am maintaining a public list of projects related to COVID-19 contact tracing.
https://github.com/shankari/covid-19-tracing-projects

Would you be willing to submit these to that list through a PR? Having a shared list outside any specific project would make it easier for others to find as well

Thanks!

**Comment by myiremark** [comment]
from @pde:

Google Doc: [Shared Research on Privacy-Preserving Contact Tracing Apps](https://docs.google.com/document/d/1PsM3dMp10PX2mKFc1HLypLbCzeNwAMKM16ug8rQyA10/edit#)

**Comment by hspinks** [comment]
from @123AndGo in #661:

> Singapore's government will be releasing for free and in open source their "BlueTrace" bluetooth tracing technology, which they are using in their official tracing app (TraceTogether). This could be complemented with geolocation, for tracing and for mandatory isolation monitoring.
> 
> I really think this could be a home-run to beat the coronavirus: https://medium.com/@andresdavidgalindoolarte/how-to-beat-the-coronavirus-b21041b8addb
> 
> Some links about Singapore's technology:
> 
> Video of how Singapore’s tracing app works: https://youtu.be/buj8ZTRtJes
> 
> BlueTrace’s project website: https://bluetrace.io/
> 
> TraceTogether official website: https://www.tracetogether.gov.sg/
> 
> I guess you are already aware and are reviewing to integrate this technology but if not, it is really important that you can review it.
> 
> Thank you!

**Comment by hspinks** [comment]
From @i5qme2b944w3 in https://github.com/WorldHealthOrganization/app/issues/661#issuecomment-606829183:

> Other open-source projects (e.g. covid-watch.org) have been implementing decentralized contact-tracing which avoids this problem.

**Comment by fabiosantoro** [comment]
**SYMPTOMATIC MODEL (map of sympoms) FEATURES**:
https://github.com/fabiosantoro/app/blob/master/Governments%20Symptomatic%20Map%20App%20COVID19%20AutoQuarantena-Selfquarantine%2003-04-20.pdf
**WIREFRAME DRAFT :**
https://github.com/fabiosantoro/app/blob/master/wireframe-SymptoMapSelfQuarantine.pdf

**Comment by fabiosantoro** [comment]
**ADMIN map backend sample (only for Governments or National Health Institutions):**
![backend symptomatic map](https://user-images.githubusercontent.com/62201413/78511528-99ac5400-779d-11ea-8c04-c28d50385dfb.jpg)
![heatmap](https://user-images.githubusercontent.com/62201413/78511543-b183d800-779d-11ea-8001-e668be144897.jpg)

**Comment by fabiosantoro** [comment]
**CLIENT Wireframe hypothesis to manage the daily collection of symptoms of all citizens**
**MOST IMPORTANT FEATURES:**
1) UPLOAD ALL FAMILY MEMBERS
2) DAILY SYMPTOMS INTENSITY
3) LOAD NEW SYMPTOMS
4) MEDICINES ASSUMEND & PREVIOUS PATHOLOGIES


![sympto1](https://user-images.githubusercontent.com/62201413/78511731-52bf5e00-779f-11ea-86bb-fee6ef800c44.jpg)
![sympto2](https://user-images.githubusercontent.com/62201413/78511732-53f08b00-779f-11ea-88c7-29ae4f755b60.jpg)
![sympto3](https://user-images.githubusercontent.com/62201413/78511733-53f08b00-779f-11ea-8a1e-93be19790e30.jpg)
![sympto4](https://user-images.githubusercontent.com/62201413/78511734-54892180-779f-11ea-8f51-1fce49f8747c.jpg)
![sympto5](https://user-images.githubusercontent.com/62201413/78511735-5521b800-779f-11ea-8d36-bb112dcdfaf0.jpg)
![sympto6](https://user-images.githubusercontent.com/62201413/78511738-5652e500-779f-11ea-8e2c-c52e1e578f2e.jpg)
![sympto7](https://user-images.githubusercontent.com/62201413/78511740-57841200-779f-11ea-9b0f-f2a2eb02847d.jpg)

**Comment by advayDev1** [comment]
I don't think this constitutes an issue.
