### ISSUE TITLE
Carousel progress indicator is difficult to distinguish from text if text is long

### ISSUE THREAD

**Issue by dnfield** [WorldHealthOrganization/app#325]
On a smaller phone screen, some of the longer text information can end up overflowing into the page view dots.  It becomes difficult to tell that there's more text to scroll down to view.

One way to solve this would be to add an elevation to the progress dots. Another way might be to put them behind a gradient or a frost effect into the text (effectively making the text slide under them).

**Comment by KhaleelShaheenDC** [comment]
I worked on this issue at this PR:
https://github.com/WorldHealthOrganization/app/pull/360

**Comment by samueladekunle** [comment]
Hello @dnfield, as your PR on this issue been accepted?

**Comment by dnfield** [comment]
I removed the code for this from my pr until a design is settled on

**Comment by hspinks** [comment]
Closing as design has changed
