### ISSUE TITLE
Dynamic Content Flutter Implementation

### ISSUE THREAD

**Issue by myiremark** [WorldHealthOrganization/app#326]

**Comment by patniemeyer** [comment]
After talking to Shilpa and Clement today we were thinking that we might hold off on implementing the dynamic content loading mechanism for just a bit until we have a real requirement that utilizes it.  This would keep us on the standard localization file scheme for the first few releases and give us a bit of time to evaluate what is needed.  That said it's never too early to start looking into requirements for this.

**Comment by advayDev1** [comment]
Let's please separate the concerns of static vs. dynamic and degree of localizability.  As of this moment (and yes it changes often), the ability to serve content dynamically from a server is a  requirement for immediately next version.

**Comment by hspinks** [comment]
Closed in #588
