### ISSUE TITLE
wish: Progressive Web App ?

### ISSUE THREAD

**Issue by rzr** [WorldHealthOrganization/app#330]
May I suggest to consider also PWA technology :

- It's easier to deploy (no store approvals)
- work also offline
- portable between system
- rely on browser security privacy model

More:
https://en.wikipedia.org/wiki/Progressive_web_application

**Comment by kassim** [comment]
see https://github.com/WorldHealthOrganization/app/pull/311

**Comment by myiremark** [comment]
Thanks for your suggestion, closing as duplicate as this is definitely a consideration, and there are other issues / PRs dealing with it.
