### ISSUE TITLE
Soap emoticon not available on nexus 5

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#331]
We should check when it was added and in which OS versions are available.

![image](https://user-images.githubusercontent.com/547021/77637774-793af900-6f56-11ea-9f6e-0a89a36350d0.png)

**Comment by kassim** [comment]
avail on Android 9 and up

so we might need to embed an emoji font if we want to depend on this
personally I would have expected image assets instead of emojis

**Comment by PieterAelse** [comment]
Emoji's can look different on any platform and OS-version, simple image would be better IMO 👍

**Comment by gspencergoog** [comment]
One resource that might be helpful are these (free) icons from from FontAwesome: fontawesome.com/icons?d=gallery&q=covid-19

There's a Flutter package that can trivially embed them, too: pub.dev/packages/font_awesome_flutter

**Comment by m3teitel** [comment]
Hey, if no one is working on this yet, I can take a look and make the changes. I think the fontawesome icons might be a bit too monochrome but we can take some from here: https://icons8.com/icons. They're all free to use with credit.

**Comment by json469** [comment]
If emoticons are limited to only these (and few other) screens, local image asset wouldn't be a bad idea. Images will now be unified which could go opposite to native-experience?

Either way I'm happy to help out on this one as well 😄

**Comment by jpelgrim** [comment]
I agree that custom images, animations or videos are best to better communicate the task. (Specifically for people who aren't very skilled readers). I saw there already were some UI/UX designers who volunteered? This would be the part they could contribute best I think! Create meaningful graphics, animations and/or videos.

**Comment by kassim** [comment]
as an action on this, I would suggest we turn all of these emoji usages into image assets of the same emojis, as it is most likely these will be replaced by image assets in the future, but we can maintain the same design while fixing the bug, and preparing for future changes

**Comment by SamMousa** [comment]
Please sync up with the design team first; I think a deliberate choice for emoji's was made for this first release.

**Comment by kassim** [comment]
that's why I'm suggesting just creating image assets of the same emojis, it won't change the design

**Comment by SamMousa** [comment]
There's no universal look for these emoji's, they are platform dependent. 
I'm fine with you doing that, but realize there's a chance it will not be used.

**Comment by yourkompas** [comment]
We will be using custom images in the public release. Please use the image assets of the same emojis as suggested by @kassim if possible!

**Comment by kassim** [comment]
note: Twitter emoji usage was suggested during the presentation of the new design to have consistency across platforms

**Comment by DeepakRitu** [comment]
> that's why I'm suggesting just creating image assets of the same emojis, it won't change the design - but will fix the bug
> 
> edit:
> asked in Slack https://who-app.slack.com/archives/C010A0RAP1N/p1585312179097200

Hi

**Comment by SamMousa** [comment]
At this time there are still broken emoji's in the preview. Adding a blocker label since this cannot be punted and there is no clear decision on a path forward.

**Comment by kassim** [comment]
Here's an example of how it could work with SVG embed of Twitter's emoji

https://github.com/WorldHealthOrganization/app/compare/master...kassim:svg-emoji?expand=1

<img src="https://user-images.githubusercontent.com/11020264/77862995-66a71500-721f-11ea-9925-786ca67450da.png" width="300">

if it works for you I'll create a PR

**Comment by kassim** [comment]
the soap emoji in particular is removed with this upcoming PR https://github.com/WorldHealthOrganization/app/pull/614

but there are emojis elsewhere that are too new 
see https://github.com/WorldHealthOrganization/app/issues/523

these could be replaced with images in-line with the text using WidgetSpan

**Comment by hspinks** [comment]
the goal of using emojis was to avoid the issue of image licensing by letting each platform handle turning a unicode character into an image... switching to using images will re-open the license question (some emoji image libraries are open source, but we'd need to choose one compatible with our license).

since the design was updated so that emojis are no longer central to the meaning of each page, I'm going to remove the `P0` tag and `v1.0` milestone here for now...
