### ISSUE TITLE
Decide on flutter code style

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#334]
Flutter comes with a standard coding style: https://flutter.dev/docs/development/tools/formatting

1. I propose using the standard `flutter format` command.

@theswerd @patniemeyer you have flutter experience, any reason not to go this way?

2. I propose reformatting the whole client now, it would only change 16 files, 8 if we exclude generated files.

Advantage of formatting the whole code base now is that our CI becomes simpler (we can enforce encoding for all files instead of just the changed ones).

If accepted we need to add a new CI step to the test flow that runs:
```
flutter format -n --set-exit-if-changed ./lib 
```

**Comment by mit-mit** [comment]
Hi, Dart & Flutter product team member here. I'd really recommend that you chose to auto-format with `flutter format` (which can also conveniently be done on Save in our [supported IDEs](https://flutter.dev/docs/get-started/editor)). That way you don't have to spend time discussing formatting preferences in code reviews, and in these times any time saving is well worth taking.

The suggestion above to enforce format checks in CI is also a very good one, from my experience.

**Comment by SamMousa** [comment]
Anyone up for making a PR?

**Comment by theswerd** [comment]
I got it!

**Comment by SamMousa** [comment]
@theswerd did you get to it yet? --> it'd be great if we have this before reviewing some other PRs

**Comment by advayDev1** [comment]
@hspinks i think we should also add a husky precommit check to ppl don't find out they misformatted after they push a pr.  do you want to add that to your new system?

**Comment by advayDev1** [comment]
I'm dumb, this has nothing to do with the new actions system. This was resolved by #1090
