### ISSUE TITLE
Face emoji instead of mouth in protect yourself section

### ISSUE THREAD

**Issue by quaintdev** [WorldHealthOrganization/app#343]
The mouth emoji looks a bit misleading in the protect yourself section where we have mentioned do not touch mouth, nose and eyes. Shouldn't we be using a face emoji or the one with mask instead? 

Maybe the wording can change to "Don't touch your face"

**Comment by gspencergoog** [comment]
One resource that might be helpful are these (free) icons from from FontAwesome: https://fontawesome.com/icons?d=gallery&q=covid-19

There's a Flutter package that can trivially embed them, too: https://pub.dev/packages/font_awesome_flutter

**Comment by britannio** [comment]
It's not 

> One resource that might be helpful are these (free) icons from from FontAwesome: https://fontawesome.com/icons?d=gallery&q=covid-19
> 
> There's a Flutter package that can trivially embed them, too: https://pub.dev/packages/font_awesome_flutter

The new icons aren't available until my pr for the package is merged https://github.com/fluttercommunity/font_awesome_flutter/pull/83
