### ISSUE TITLE
[travel_advice.dart] add automated tests

### ISSUE THREAD

**Issue by britannio** [WorldHealthOrganization/app#350]
https://github.com/WorldHealthOrganization/app/issues/342

**Comment by Sayegh7** [comment]
I would like to work on this if it's still needed to add tests for it in addition to the ones that would be added to the `carousel_page.dart`

**Comment by britannio** [comment]
> I would like to work on this if it's still needed to add tests for it in addition to the ones that would be added to the `carousel_page.dart`

@Sayegh7 go for it although it might create merge-conflicts with other pull requests that haven't been merged. Also, I don't think that the design has been finalized yet so these pages are subject to change.

**Comment by advayDev1** [comment]
Let's not file separate tasks for each test
