### ISSUE TITLE
Broken Link in ONBOARDING.html on GH Pages

### ISSUE THREAD

**Issue by JMcKiern** [WorldHealthOrganization/app#355]
Publishing the markdown files to GitHub Pages seems to break one of the relative links.

On the [ONBOARDING](https://worldhealthorganization.github.io/app/ONBOARDING.html) page, scroll down to the "Contributor Guidelines" link under the "[Building and Running](https://worldhealthorganization.github.io/app/ONBOARDING.html#building-and-running)" header. Clicking this link will take you to https://worldhealthorganization.github.io/app/CONTRIBUTING.md not a compiled html page like the other links.

Additionally, https://worldhealthorganization.github.io/app/CONTRIBUTING.html returns a 404.

**Comment by tdh8316** [comment]
Maybe https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md ?

**Comment by JMcKiern** [comment]
What do you mean?

**Comment by sgrapi** [comment]
Hi! 
I have been analyzing the code of these pages:

https://worldhealthorganization.github.io/app/CONTRIBUTING.md
https://worldhealthorganization.github.io/app/CONTRIBUTING.html

Perhaps it is not compiled because the page could be stored or saved in another folder or the name link or file is changed and now the link it doesn't work.

**Comment by neo30fer** [comment]
Hi!

I have been doing some research, and I found out that GiHub does not allow to manually trigger a rebuild, but you can push a commit. I mean, you can try this:

# Empty commit
git commit -m 'rebuild pages' --allow-empty

# Push to the branch whose pages are selected to be published
git push origin <branch-name>

I think maybe that could tackle this issue. Of course, there could be some issue with GitHub internal jobs/tasks, so you should ask them about this issue.

Source: https://stackoverflow.com/questions/24098792/how-to-force-github-pages-build

I hope this can help to solve this.
