### ISSUE TITLE
What user information do we capture in the initial release

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#37]

**Comment by viviancromwell** [comment]
since we are not capturing geo location in the initial release. 

But we will capture feedback, so we should have a log 

1) email address
2) feedback

**Comment by viviancromwell** [comment]
cc @advayDev1 as fyi.

**Comment by hspinks** [comment]
@viviancromwell how are you thinking about capturing user feedback for this v0.1? this could be as simple as a button that opens the user's preferred email client with an email pre-populated with our feedback email and the user's device & app version info (fastest time to implement)

**Comment by viviancromwell** [comment]
> @viviancromwell how are you thinking about capturing user feedback for this v0.1? this could be as simple as a button that opens the user's preferred email client with an email pre-populated with our feedback email and the user's device & app version info (fastest time to implement)

we have agreed to launch mail client on the device for this release. thank you.
