### ISSUE TITLE
Cut off text

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#376]
Several screens in iOS app show cut off text. This is also an issue for translation to other languages which can be 50% larger than English

Device: iPhone 11 Pro Max
Is: 13.3.1
WHO app: v0.1.1 IIRC

![15588C12-C5DE-4FD6-AC69-7F87A6CAE7DF](https://user-images.githubusercontent.com/679339/77730788-bd61e400-6fbe-11ea-8b3a-5be0b1ab9d27.png)
![686B9315-A89A-44CD-B4D2-655DA893D78E](https://user-images.githubusercontent.com/679339/77730796-c0f56b00-6fbe-11ea-9e1a-124cab0d7804.png)
![A657DE15-1F29-4241-B890-C30802455B95](https://user-images.githubusercontent.com/679339/77730798-c2269800-6fbe-11ea-9632-81fd7fb444a9.png)

**Comment by hungrymonkey** [comment]
I posted a duplicated issue https://github.com/WorldHealthOrganization/app/issues/388

**Comment by Domirop** [comment]
I think that the solution is use MediaQuery. I can do this issue

**Comment by Domirop** [comment]
Is the error to be solved exactly on the "WhoMythBuster" screen and is it a rendering error?

**Comment by Domirop** [comment]
Is the error to be solved exactly on the "WhoMythBuster" screen and is it a rendering error? because, i solve this error

**Comment by Domirop** [comment]
I think that the solucion is simple. I want to solve this issue

**Comment by Domirop** [comment]
I think that the solution is simple. I want to solve this issue

**Comment by hspinks** [comment]
Closing as design updated
