### ISSUE TITLE
Trailing ellipsis make end of text unclear

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#377]
Trailing ellipses suggest hidden text that’s not displayed. Normally associated with “more” button. In this case, there is no more text.

Device: iPhone 11 Pro Max
Is: 13.3.1
WHO app: v0.1.1 IIRC

![C0EF9FBE-4739-4973-A28E-CFEDD84AEBB9](https://user-images.githubusercontent.com/679339/77731116-8809c600-6fbf-11ea-8d6c-2e8a8ec2edfd.png)

**Comment by advayDev1** [comment]
Given that our UI is almost completely being changed - do we want to work on these old UI bugs @brunobowden ?

**Comment by hspinks** [comment]
Closing as design has been updated
