### ISSUE TITLE
Flutter licenses list duplicates

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#378]
This appears to have for identical licenses that only differ by Copyright data. I think this might be auto generated. It would be nice if this was more concise, e.g. copyright line contains multiple entries then single copy of license specific to that dependency.

In screenshot, notice duplicate Khronos Group license. The only difference I can see is that the first mentions “Copyright (c) 2013 - 2016” and the second “ Copyright (c) 2013 - 2017”

![72797F92-C1E5-4AF0-9931-85F32EB63AFA](https://user-images.githubusercontent.com/679339/77731368-02d2e100-6fc0-11ea-896d-8a7e8e7d090a.png)

**Comment by advayDev1** [comment]
Indeed it is auto-generated.

**Comment by advayDev1** [comment]
We don't control the process, and I don't think it affects users at all.
