### ISSUE TITLE
About missing version information

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#379]
It’s essential that the About link includes version information for debugging. Ideally it should also include language, OS details and other information essential for debugging.

**Comment by hungrymonkey** [comment]
We can always detect the OS without a plugin
https://api.flutter.dev/flutter/material/ThemeData-class.html
https://api.flutter.dev/flutter/foundation/TargetPlatform-class.html

We need to add a dependency and add permissions for more information.
https://pub.dev/packages/device_info
https://pub.dev/documentation/device_info/latest/

**Comment by PieterAelse** [comment]
And what to do for Web? As `device_info` plugin doesn't support web..

**Comment by hspinks** [comment]
Closing in favor of #580
