### ISSUE TITLE
Slack link expired

### ISSUE THREAD

**Issue by rajatdutta** [WorldHealthOrganization/app#380]
Hi,
   I want to join the community on slack, but the link has expired.
@SamMousa  please provide a new link. 

Thanks
Raj

**Comment by ravishankarahirwar** [comment]
Yes, I am also facing the same issue, I want to join the community as a developer but unable to join it, because the link is not working

**Comment by advayDev1** [comment]
**To everyone who has jumped in wanting to help:** We are humbled at the outpouring of support we have received from all over the world and are eager to have you contribute and apologize that we are still in the early process of figuring out how to manage all the contributions. Please bear with us while we get an initial version out the door and split out into smaller teams working in parallel, when we can then on-board more volunteers. Until then, please keep filing issues, and fill out the [volunteer form here](https://forms.gle/FUugWvUVvMcV3dLJA) and we’ll get back in touch.

**Comment by ravishankarahirwar** [comment]
Thank you @advayDev1 for the update, Best of luck of the first version of the app. It is really needed as soon as possible.

**Comment by advayDev1** [comment]
Please fill out the volunteer form!  We'd like to get back in touch after Monday.

**Comment by maxto024** [comment]
Faced the same slack invite link is no longer active.
@advayDev1  can you please try to update the slack invite link  on the onboarding document 
https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md

I filled the volunteer form 

Thanks

**Comment by oddlyfunctional** [comment]
@advayDev1 Thanks for the update! I filled the volunteer form and will be waiting. If there is anything we can do to help for now, please let us know! I'll have a lot more free time to help this weekend than from Monday, I bet the same applies to other devs.
