### ISSUE TITLE
Serve dynamically updated content from our servers when network is available

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#385]
Ticket to track the v1.0 requirement; this should be part of an overall strategy for serving content to the app that includes offline content, dynamic content served from the cloud, and internationalization strategy. Other issues will be opened for the specific subtasks

**Comment by dhruvilp** [comment]
Hi @hspinks, if no one is working on these, you can assign this one and 384 to me. 
Question: what's the base-url url and endpoints?
