### ISSUE TITLE
Support localized push notifications

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#387]
Ticket to track the v1.0 requirement; includes the asking for user notifications permission request flow on the client, ability to bucket users by locale (level of granularity TBD), the back end of registering devices for pushes and sending them, and handling pushes in the client. We will create additional issues for each subtask.

**Comment by Chinmay-KB** [comment]
Firebase Cloud Messaging can be used to achieve it without much backend work. I would like to work on this issue

**Comment by advayDev1** [comment]
Push notifications have been implemented, any remaining issues should have specific issues.
