### ISSUE TITLE
Set up app instrumentation and basic analytics

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#389]
Ticket to track the v1.0 requirement; instrumentation and analytics will be used for product improvement and should include aggregated data about feature usage and crash reporting. Individual issues will be created for each subtask

**Comment by attrib75** [comment]
Admittedly, I'm a Microsoft stack user, but they have a great mobile analytics Saas solution called App Center [https://appcenter.ms](https://appcenter.ms) .  It could be an easy way to get analytics, which are also exportable.  There is a plugin for flutter  
https://pub.dev/packages/appcenter

**Comment by advayDev1** [comment]
@epicfaace plz close if this is v1 complete

**Comment by epicfaace** [comment]
Let's keep this open until @myiremark has a chance to test on iOS that everything is working properly

**Comment by epicfaace** [comment]
This has been tested on iOS. Closing
