### ISSUE TITLE
what is the content structure for "protect yourself"

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#39]

**Comment by viviancromwell** [comment]
@brunobowden do you have a point of contact at WHO what the content structure might be when user clicks on "Protect yourself", trying to figure out what to include in V0.1

**Comment by SamMousa** [comment]
I think protect yourself would show the tips (again) as seen in the prototype. Those are the things anyone can do.

**Comment by viviancromwell** [comment]
I think I am getting lots of input from another thread. closing on this.
