### ISSUE TITLE
🐛 CarouselView close/X button touch ripple effect overdrawn by page content of PageView

### ISSUE THREAD

**Issue by JulianAssmann** [WorldHealthOrganization/app#390]
The touch ripple effect of the close button of the CarouselView widget is overdrawn by the content of the PageView in the same widget:

![image](https://user-images.githubusercontent.com/15306765/77735250-82859d80-700a-11ea-81c5-ccc676c05362.png)

**Comment by JulianAssmann** [comment]
I'm working on this issue

**Comment by hspinks** [comment]
Closing as design has changed
