### ISSUE TITLE
Avoid crowded places icon is not matching its meaning.

### ISSUE THREAD

**Issue by ravishankarahirwar** [WorldHealthOrganization/app#391]
If you look into the icon of crowded places, it looks like a pedestrian is not allowed in the area. I am requesting to you kindly change this icon so It will give the right message to the audience.
For a reference please have a look: https://www.iconfinder.com/icons/5730692/avoid_caution_crowded_people_prevent_social_distancing_icon

#129

**Comment by pawan-maurya** [comment]
I am trying to represent social distance and avoid crowd places both with this icon. 
![who-avoid-crowded-places-icon](https://user-images.githubusercontent.com/19765392/77767075-8941fe00-7066-11ea-9411-5326272b936e.png)

**Comment by hspinks** [comment]
Closing as design has changed
