### ISSUE TITLE
Add MacOS support to the app to ease developing/testing

### ISSUE THREAD

**Issue by PieterAelse** [WorldHealthOrganization/app#392]
As MacOS support for Flutter is working good, it's easy to use MacOS for development with the benefits of:
- Not having to run a simulator/emulator
- or on a real device
- UI can be developed/tested more easily as your window can be resized.

And as is rather easy to add, I've gone ahead and did it in PR https://github.com/WorldHealthOrganization/app/pull/363

**Comment by advayDev1** [comment]
We will not be adding complexity to the code for platforms that our users won't have.
If you have a mac, you should test on iOS simulator.
