### ISSUE TITLE
Pls I'd like to join the slack channel and also contribute to this Noble cause

### ISSUE THREAD

**Issue by JAtoms** [WorldHealthOrganization/app#394]
@viviancromwell 
Hello, I don't know the best way to communicate to you, but am very much interested to contribute to this cause in any way.

**Comment by JMcKiern** [comment]
See [ONBOARDING](https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md).

**Comment by advayDev1** [comment]
**To everyone who has jumped in wanting to help:** We are humbled at the outpouring of support we have received from all over the world and are eager to have you contribute and apologize that we are still in the early process of figuring out how to manage all the contributions. Please bear with us while we get an initial version out the door and split out into smaller teams working in parallel, when we can then on-board more volunteers. Until then, please keep filing issues, and **fill out the [volunteer form here](https://forms.gle/FUugWvUVvMcV3dLJA) and we’ll get back in touch.**

**Comment by JAtoms** [comment]
I wish to extend my gratitude to the prompt response. I am always available anytime. Thanks
