### ISSUE TITLE
Beta distribution channel

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#397]
Several options exist for beta deployment, all supported by fastlane:

https://docs.fastlane.tools/actions/#beta

Since we're building for android and ios I think going with testflight is not optimal.

If you have experience with any of the listed tools please let us know your experience below.

We can also configure fastlane to deploy both to testflight and google play console.

**Comment by arasu01** [comment]
AppCenter can be used for beta distribution. 
It well organised into groups and support both platforms(iOS and Android)

https://appcenter.ms

**Comment by kassim** [comment]
if using Android App Bundles to build we should make sure the distribution service supports that 

Google Play does and I just checked now that MS's App Center does too. Last time I checked Firebase doesn't.


one negative of Google Play is we wouldn't have the best admin access (as it would probably need to be on WHO's account)

**Comment by shankari** [comment]
@SamMousa you may want to make a distinction between updating UI content and native code updates (e.g. to the plugins you use). The [App Store terms and conditions include](https://developer.apple.com/app-store/review/guidelines/):

> Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps. 

There are multiple options (as you point out) for UI-only updates and testing. But for native code updates, given these restrictions, I can't see how there can be options other than TestFlight, which is blessed by Apple.

**Comment by kassim** [comment]
@shankari that text isn't referring to distributing packages for testing. It's more describing the sort of scenario where you'd be able to add entire new features by having your app pull data from elsewhere. 

E.g. using CodePush to update a React Native app. Because it's implemented in JS/HTML you can have your app download an entirely new app and run it. 

Testflight isn't a requirement for beta app distribution

**Comment by hspinks** [comment]
We've used TestFlight for iOS and Google Play alpha/beta for Android. Closing this issue for now, but @SamMousa feel free to re-open if you think we should explore something different longer-term
