### ISSUE TITLE
Translate app content into Dutch

### ISSUE THREAD

**Issue by jpelgrim** [WorldHealthOrganization/app#398]
Add Dutch translations to the app

Related to #21 #224

**Comment by jpelgrim** [comment]
☝🏻 I'm picking this up. PR on its way!

**Comment by sapte91** [comment]
Hi @jpelgrim! Thank you so much for your support of this project (and for the PR). We're thrilled that you want to contribute to localization of the app! Just so you're aware: We’ll primarily be sourcing and managing translations from Lingo24, our translation management system, and we're only focusing on WHO's official languages (English, French, Spanish, Arabic, Russian and Chinese) for the next week or so.

We definitely need translation volunteers going forward - as our set of supported languages and locales grows, there will be lots of opportunity to contribute! Our projected needs for the next two months are in native speaker LQA and translators for languages that we cannot support on Lingo24. We apologize though that we are still in the early process of figuring out how to manage all the contributions so stay tuned for more details coming soon. Until then, please fill out the volunteer form below and we’ll get back in touch shortly.

https://forms.gle/DTqvaqh4mE7bDe5U7
