### ISSUE TITLE
Translate app content into Italian

### ISSUE THREAD

**Issue by gcarmix** [WorldHealthOrganization/app#401]
Add Italian translations to the app

Related to #21 #224

**Comment by gcarmix** [comment]
I can pick up the issue, I'm italian

**Comment by orchardbirds** [comment]
Don't forget to create a `messages_it.dart` file in `app/client/flutter/lib/generated/intl/`

**Comment by gcarmix** [comment]
> Don't forget to create a `messages_it.dart` file in `app/client/flutter/lib/generated/intl/`

Yes, but I've seen that is generated automatically, could you tell me how to generate it?

**Comment by orchardbirds** [comment]
Ah then I'm afraid I don't know

**Comment by dna-f** [comment]
Maybe I can help
Add the following dependency to the pubspec.yaml:
intl_translation: ^0.17.9

Then, after adding the translated intl_it.arb file to the corresponding folder, execute the following command from the terminal:
flutter packages pub run intl_translation:generate_from_arb --output-dir=lib/generated/intl --no-use-deferred-loading lib/generated/l10n.dart lib/l10n/intl_*.arb

It should work ;)

**Comment by dna-f** [comment]
Ops ... don't forget to add 
Locale('it', ''),
at line 254 of the file l10n.dart so that it becomes like this
Locale('es', ''), Locale('ar', ''), Locale('zh', ''), Locale('en', ''), Locale('ru', ''), Locale('fr', ''), Locale('it', ''),

**Comment by gcarmix** [comment]
thank you @dna-f, it works!

**Comment by sapte91** [comment]
Hi everyone! Thank you so much for your support of this project (and the PRs). We're thrilled that you want to contribute to localization of the app! Just so you're aware: We’ll primarily be sourcing and managing translations from Lingo24, our translation management system, and we're only focusing on WHO's official languages (English, French, Spanish, Arabic, Russian and Chinese) for the next week or so. 

We definitely need translation volunteers going forward - as our set of supported languages and locales grows, there will be lots of opportunity to contribute! Our projected needs for the next two months are in native speaker LQA and translators for languages that we cannot support on Lingo24. We apologize though that we are still in the early process of figuring out how to manage all the contributions so stay tuned for more details coming soon. Until then, please fill out the volunteer form below and we’ll get back in touch shortly.

https://forms.gle/DTqvaqh4mE7bDe5U7

@gcarmix @dna-f @orchardbirds
