### ISSUE TITLE
docs/ONBOARDING.md: Slack invite has expired

### ISSUE THREAD

**Issue by alessio** [WorldHealthOrganization/app#406]
The Slack [invite URL](https://join.slack.com/t/who-app/shared_invite/zt-cx6ycppt-ccqPJ7ZSGy3~77gSByexJw) available in the [ONBOARDING.md](https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md) page does not work. The invite seems to have expired.

Some partners of mine and I would like to join and synchronise with the rest of the team.

Thanks for considering.

**Comment by artellador** [comment]
Same for https://github.com/WorldHealthOrganization/app/wiki Slack invitation link

**Comment by tinyoakstudio** [comment]
Hey Guys! Is there a working link to the slack? Many thanks!

**Comment by cbgrey** [comment]
Came here to leave the same feedback. Want to get involved.

**Comment by hspinks** [comment]
Thank you to all who have come here with enthusiasm for getting involved. We are humbled at the outpouring of support we have received from all over the world, are eager to have you contribute, and apologize that we are still in the early process of figuring out how to manage all the contributions.  Please bear with us while we get an initial version out the door and split out into smaller teams working in parallel, when we can then on-board more volunteers.  Until then, please keep filing issues, and fill out the [volunteer form here](https://forms.gle/FUugWvUVvMcV3dLJA) and we’ll get back in touch.
