### ISSUE TITLE
SLACK JOINING LINK FOR WHO COVID-19 APP NOT WORKING

### ISSUE THREAD

**Issue by hs663964** [WorldHealthOrganization/app#408]
PLZ SHARE LINK TO JOIN SLACK FOR PROJECT
LINK:
https://who-app.slack.com/join/shared_invite/zt-cx6ycppt-ccqPJ7ZSGy3~77gSByexJw
NOT WORKING

**Comment by SamMousa** [comment]
Please don't use caps.

**Comment by hs663964** [comment]
ok
