### ISSUE TITLE
allow users to send feedback

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#41]

**Comment by viviancromwell** [comment]
For V0.1 we decided it will just launch a mail client.

**Comment by viviancromwell** [comment]
Need to follow up with Ursula on if there is an email to receive feedback.

**Comment by viviancromwell** [comment]
done.

**Comment by epicfaace** [comment]
Reopening this because we need to actually implement this functionality on v0.1 -- launch a mail client. What is the email address we should use for this?

**Comment by hspinks** [comment]
I'm moving this to the vNext milestone as it doesn't look like we'll have an email for feedback in time

**Comment by epicfaace** [comment]
We'll need to remove the Feedback button in v0.1 though -- Apple may reject an app that has a nonfunctional button.

**Comment by advayDev1** [comment]
#989 will do the quick soln for v1; #1015 will do the longer-term solution
