### ISSUE TITLE
fix english typos

### ISSUE THREAD

**Issue by orchardbirds** [WorldHealthOrganization/app#410]
There are small spelling mistakes, grammar mistakes etc. present in the english version

**Comment by SamMousa** [comment]
Are you up for fixing them? Note that #404 already fixes one of them.

**Comment by orchardbirds** [comment]
Yes, I've caught some more that I can easily fix

**Comment by jnimis** [comment]
Hi I'm new here, but interested in helping out! (shared Slack invite doesn't work, so I looked for the first issue I could help with)

**Comment by orchardbirds** [comment]
@SamMousa I think maybe the relevant MR (https://github.com/openai/gym/pull/1854) should be submitted before the translations, just because of a small change to each of the intl_*.arb files, but I could be wrong :)
