### ISSUE TITLE
Using Hero animations in carousels

### ISSUE THREAD

**Issue by HuzefaGadi** [WorldHealthOrganization/app#414]
Flutter has got great animation support with widgets like Hero etc. we can make the courosals with those animation to manipulate the images on each of those screens. that way it will look continuous and will give a good UI experience.

**Comment by HuzefaGadi** [comment]
I can take this up @SamMousa

**Comment by hspinks** [comment]
Thanks for your interest @HuzefaGadi! The design of the app has changed, so I'm closing this for now
