### ISSUE TITLE
Translate app content into Portuguese

### ISSUE THREAD

**Issue by robsonsilv4** [WorldHealthOrganization/app#419]
Add Portuguese translations to the app.

Related to [#21](https://github.com/WorldHealthOrganization/app/issues/21).

**Comment by robsonsilv4** [comment]
I'm working on this issue, I'm Brazilian.

**Comment by LueZavala** [comment]
Hello! I can help translating Spanish! Please let me know where the documents are.. I am new here.
Willing to help. Thanks!

**Comment by rosariopfernandes** [comment]
If needed, I'd be happy to review the changes. I also speak Portuguese :)

**Comment by carvalhojgp** [comment]
I'm brazilian too and willing to help.

**Comment by rubenmarcus** [comment]
Is there anyway i can help?

**Comment by pacm28** [comment]
I can help also, I'm Portuguse

**Comment by robsonsilv4** [comment]
I already submitted the [PR](https://github.com/WorldHealthOrganization/app/pull/441).
And @rosariopfernandes suggested small fixes, thanks :)

If someone also could review the text, would help.

**Comment by sapte91** [comment]
Hi everyone! Thank you so much for your support of this project (and the PR). We're thrilled that you want to contribute to localization of the app! Just so you're aware: We’ll primarily be sourcing and managing translations from Lingo24, our translation management system, and we're only focusing on WHO's official languages (English, French, Spanish, Arabic, Russian and Chinese) for the next week or so. 

We definitely need translation volunteers going forward - as our set of supported languages and locales grows, there will be lots of opportunity to contribute! Our projected needs for the next two months are in native speaker LQA and translators for languages that we cannot support on Lingo24. We apologize though that we are still in the early process of figuring out how to manage all the contributions so stay tuned for more details coming soon. Until then, please fill out the volunteer form below and we’ll get back in touch shortly.

https://forms.gle/DTqvaqh4mE7bDe5U7

@robsonsilv4 @rosariopfernandes @pacm28 @rubenmarcus @carvalhojgp
