### ISSUE TITLE
Chat bot interface for self diagonose

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#42]
Tencent mini app

**Comment by viviancromwell** [comment]
this will be a low priority for the initial release, I will take an AI to talk to Alex Ng and cc Daniel and Bruno. 

@brunobowden

**Comment by viviancromwell** [comment]
Chris, I added the screen shot. https://github.com/WorldHealthOrganization/app/issues/42

**Comment by hspinks** [comment]
closing as a non-planned feature for now
