### ISSUE TITLE
Drawer Icon

### ISSUE THREAD

**Issue by jemis67** [WorldHealthOrganization/app#422]
today about 85-90 percent people use right hand.so drawer icon should be on right side and we can user endDrawer instead of drawer in flutter code.

**Comment by Chinmay-KB** [comment]
But most people are more familiar with left-hand drawer, isn't it? For an app like this, there shouldn't be a learning curve at all

**Comment by Sarankumar18** [comment]
Left Hamburger should be the legit and easy to drag

**Comment by jemis67** [comment]
Most of leading  app use  right hamburger examples:WhatsApp,Instagram, gana etc.
so it's right move to switch easy to use UI,for left hamburger you need to stretch your thumb for opning menu and for right hamburger its getting easier.i am hoping that you are understanding my view.
________________________________

**Comment by Nizar-Albahri** [comment]
I agree with @Chinmay-KB  and @Sarankumar18, left burger icon is the most commonly used.
@jemis67, WhatsApp doesn't have a drawer neither Instagram (at least on Android), WhatsApp has an "option/context" menu on right. Plus you shouldn't be stretching your thumb, the drawer should appear on swiping as well.

**Comment by Chinmay-KB** [comment]
In the current state the app doesn't need neither hamburger nor overflow button. It will depend on the features/screens which will be added further

**Comment by jemis67** [comment]
Maybe most commonly used is not easy to use.skip hamburger icon for current discussion,my point is that menu shuld be on right.for menu icon it's not  always hamburger,sometime its triple dots.profille icon or anything else.flutter provide facility of enddrawer  then we shuld atleast try once.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kassim** [comment]
it depends on the context, so why not wait for that to come up dependent on design

an overflow menu (3 dots) would certainly be best on the right

**Comment by nodyhack** [comment]
> it depends on the context, so why not wait for that to come up dependent on design
> 
> an overflow menu (3 dots) would certainly be best on the right

That's The Nice Idea 💡 👏👏

**Comment by avkvirtru** [comment]
Can someone with permissions please label this issue with "design" for prospective designers to find and help with?

**Comment by hspinks** [comment]
Closing as the current app design does not use a hamburger menu
