### ISSUE TITLE
Page View Indicator is hidden after 10 pages

### ISSUE THREAD

**Issue by Sayegh7** [WorldHealthOrganization/app#423]
Example screenshots of Travel Advice Carousel:

Page 9:
![Screenshot_20200327-153015](https://user-images.githubusercontent.com/13800170/77761098-263d7080-7040-11ea-9c18-197c442f854d.png)

Page 10:
![Screenshot_20200327-153020](https://user-images.githubusercontent.com/13800170/77761121-2e95ab80-7040-11ea-8e34-ea9eb72148ba.png)

**Comment by britannio** [comment]
Duplicate of https://github.com/WorldHealthOrganization/app/issues/320

**Comment by Sayegh7** [comment]
Alright, will close it then
