### ISSUE TITLE
Slack invite does not work

### ISSUE THREAD

**Issue by mooncatventures-group** [WorldHealthOrganization/app#424]
It does not seem possible  to join the  slack  channel at this time

Mooncatventures LLC is a small  mobile development company  in Michigan
We would very much  be willing to give whatever it takes for this effort

**Comment by britannio** [comment]
Duplicate of https://github.com/WorldHealthOrganization/app/issues/406

**Comment by mooncatventures-group** [comment]
Thanks,  I  will refer  to 406
