### ISSUE TITLE
Add COVID-19 Live Statistics Tracker in the app

### ISSUE THREAD

**Issue by kaiiyer** [WorldHealthOrganization/app#426]
Adding a real-time visualization of COVID-19 Tracker would help people get to understand the figures of affected, deceased and recovered patients. We can use colors for indicating region wise number of patients under observation(say red for high and green for low). 
A graph could explain more than long para of facts so I believe it would be beneficial for literate as well as illiterate people around the globe.

**Comment by Sarankumar18** [comment]
As per your guidelines , even though there is lot of text content Visual graphics make more understandable and more useful for uneducated people which lives in rural areas.

**Comment by ZacharyEilers** [comment]
Is there an API for that data?

**Comment by kaiiyer** [comment]
@SamMousa How about we get started ?

**Comment by brunobowden** [comment]
Implemented in app

**Comment by Sarankumar18** [comment]
That's cool
