### ISSUE TITLE
CarouselSlide close button Ink is on the wrong surface

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [WorldHealthOrganization/app#432]
The ink of the close button of every `CarouselSlide` is covered by the content `Card` **below** it. This should not be the case.

![screenshot][]

 [screenshot]: https://i.imgur.com/FAjkFg8.png

**Comment by SamMousa** [comment]
Screenshot upload failed!

**Comment by Sarankumar18** [comment]
There is overlapping happens , So you can do give the first priority to the Close Button , I mean in the app stage

**Comment by Chinmay-KB** [comment]
I can work on this issue

**Comment by SamMousa** [comment]
It already has an assignee @Chinmay-KB .

**Comment by Sarankumar18** [comment]
ok , If any help need always welcome
