### ISSUE TITLE
Add CI to test Flutter Warnings

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [WorldHealthOrganization/app#437]
Currently, we are not checking for lints. 

This can be easily done by running `flutter analyze` in CI.  
I could create a PR that integrates this into the existing test workflow and rename the workflow accordingly.

**Comment by SamMousa** [comment]
We are:

https://github.com/WorldHealthOrganization/app/blob/master/.github/workflows/flutter-test.yml#L28

**Comment by creativecreatorormaybenot** [comment]
@SamMousa Oh well, this was added in the meantime. The pace of this got me 😄
