### ISSUE TITLE
Copywriting  for the mobile app need WHO's approval

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#44]

**Comment by yourkompas** [comment]
Stay up to date with the latest Coronavirus disease (COVID-19) Pandemic information from the World Health Organization. 
Stay aware of the latest information on the COVID-19 outbreak, available on the WHO website and through your national and local public health authority. Most people who become infected experience mild illness and recover, but it can be more severe for others. Take care of your health and protect others.

**Comment by csfurmanski** [comment]
Here is a brief edit to generalize on copy from @yourkompas 

Stay aware of the latest information on the COVID-19 outbreak available on the WHO mobile app. Most people who become infected experience mild illness and recover, but it can be more severe for others. Learn how to protect yourself and others, hear what experts are saying and find out how you can help.

**Comment by csfurmanski** [comment]
Keywords:
WHO, World Health Organization, COVID-19, SARS-CoV-2
