### ISSUE TITLE
"Share" button does not work on web preview

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#442]
I get the following error:

```
MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)
```

**Comment by PieterAelse** [comment]
I will pick this up in a few hours! 👍

**Comment by PieterAelse** [comment]
@epicfaace (cc @SamMousa ) 
What do we want to do as a fallback? Options could be simply showing a message (SnackBar), using Clipboard or just launching the url (see mentioned PR for example).

My proposal would be to combine it;  show a Snackbar with some message like "The info and link are copied to your clipboard!" and a button in the snackbar for "Open link" which opens the link.
Then it's up to the user to paste the stuff somewhere and/or open the link.

**Comment by epicfaace** [comment]
I like your idea!

**Comment by advayDev1** [comment]
No more web preview ; no more bug ;)
