### ISSUE TITLE
the slack link is no longer active

### ISSUE THREAD

**Issue by deddikation** [WorldHealthOrganization/app#445]

**Comment by Nizar-Albahri** [comment]
Same here, I'm getting:
"This invite link is no longer active"
when opening the link provided here:
https://github.com/WorldHealthOrganization/app/blob/master/docs/ONBOARDING.md

**Comment by fenixsolorzano** [comment]
I'm also unable to get slack invite

**Comment by Nizar-Albahri** [comment]
> I'm also unable to get slack invite

onboarding was just updated, slack is closed until initial app release.

**Comment by t-k-c** [comment]
Okay

Le ven. 27 mars 2020 à 6:26, Nizar Al-Bahri <notifications@github.com> a
écrit :

**Comment by fenixsolorzano** [comment]
@Nizar-Albahri I'm trying to get in contact to provide my whole team (Design, Backend, Mobile Development) to work in this project, can you get in contact please: jonathan@intellbits.com
