### ISSUE TITLE
Do we have a way to allow users to switch language later

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#45]

**Comment by myiremark** [comment]
I think yes, in the current design (which may have absolutely nothing to do with the final design), I'd put a button in the top right corner with a pop up modal to select language.

**Comment by viviancromwell** [comment]
> I think yes, in the current design (which may have absolutely nothing to do with the final design), I'd put a button in the top right corner with a pop up modal to select language.

thanks for the suggestion. given we wont have i18n translation in place, I will design this post v.01
