### ISSUE TITLE
Translate app to hindi

### ISSUE THREAD

**Issue by Chinmay-KB** [WorldHealthOrganization/app#452]
As a native hindi speaker, I can add the hindi translation to the app
It'll be beneficial given the size of India

I can work on this enhancement

**Comment by Tonystarkisbest** [comment]
I can help you too

**Comment by sanjog12** [comment]
I am also a native Hindi speaker, I can help too in translating, making it suitable for Indian users, and also an intermediate app developer(flutter).

**Comment by Sahil255** [comment]
मैं भी आपकी मदद कर सकता हूँ
I can help you too

**Comment by sapte91** [comment]
Hi @Sahil255 @Tonystarkisbest @Chinmay-KB! Thank you so much for your support of this project. We're thrilled that you want to contribute to localization of the app! Just so you're aware: We’ll primarily be sourcing and managing translations from Lingo24, our translation management system, and we're only focusing on WHO's official languages (English, French, Spanish, Arabic, Russian and Chinese) for the next week or so. 

We definitely need translation volunteers going forward - as our set of supported languages and locales grows, there will be lots of opportunity to contribute! Our projected needs for the next two months are in native speaker LQA and translators for languages that we cannot support on Lingo24. We apologize though that we are still in the early process of figuring out how to manage all the contributions so stay tuned for more details coming soon. Until then, please fill out the volunteer form below and we’ll get back in touch shortly.

https://forms.gle/DTqvaqh4mE7bDe5U7
