### ISSUE TITLE
WHO COVID-9 Project -Access to workshop on Slack

### ISSUE THREAD

**Issue by kacimi03hamza** [WorldHealthOrganization/app#455]
hello 

I'm volunteering for the development of the Project launched by WHO.
 please grant me access to the workspace on Slack.

best regard

**Comment by britannio** [comment]
https://github.com/WorldHealthOrganization/app/issues/406

**Comment by kacimi03hamza** [comment]
ok understod. so teams membres dose not do Meeting on slack anymore

**Comment by advayDev1** [comment]
Thank you to all who have come here with enthusiasm for getting involved. We are humbled at the outpouring of support we have received from all over the world, are eager to have you contribute, and apologize that we are still in the early process of figuring out how to manage all the contributions.  Please bear with us while we get an initial version out the door and split out into smaller teams working in parallel, when we can then on-board more volunteers.  Until then, please keep filing issues, and fill out the [volunteer form here](https://forms.gle/FUugWvUVvMcV3dLJA) and we’ll get back in touch.
