### ISSUE TITLE
Cleaner Routing using Generated routes

### ISSUE THREAD

**Issue by Chinmay-KB** [WorldHealthOrganization/app#464]
Right now navigation is done by pushing routes. Pushing routes can become quite explicit and sharing logic between them becomes difficult. It is recommended as a standard practice to use named route to navigate rather.

I would like to be assigned this

**Comment by danagbemava** [comment]
I would like to help with this

**Comment by jg-l** [comment]
Second this. Something like this approach will open up possibilities of different transitions.

Reference: https://blog.gskinner.com/archives/2020/03/flutter-simplify-your-pageroutes.html

**Comment by advayDev1** [comment]
If a specific refactor of the client UI is planned, we should have a design proposal.  cc @patniemeyer @theswerd
