### ISSUE TITLE
Writing

### ISSUE THREAD

**Issue by purpledrosophila** [WorldHealthOrganization/app#465]
Hi, I hope this isn't inappropriate to put here; I just want to ask since the Slack is closed to new contributors. I noticed your docs folder is very small, and you didn't have a docs channel listed in your Slack channels in the onboarding page, so I was hoping I might still be able to help in either documenting the app, translating content, or adding informational content about COVID-19. If I should wait until the Slack is available again, I'm perfectly willing to do so.

**Comment by advayDev1** [comment]
Thanks - please sign up in the Volunteer Form and we'll get back to you.  Things are changing so fast right now that the docs would out-dated as son
