### ISSUE TITLE
Team Roster

### ISSUE THREAD

**Issue by csfurmanski** [WorldHealthOrganization/app#48]
Working draft of current team roster needs updating please; first draft has been taken from the initial intake form plus some threads on Slack but is not complete.  Apologies if I missed you; please add yourself or correct information if needed. 

https://docs.google.com/spreadsheets/d/1jt4xrXWUnsh8DmtawNV4XGBj8RAdgn-d7ckgL2qEXPM/edit?usp=sharing

**Comment by RohanTalip** [comment]
Where was the initial intake form?  Is it now deprecated?  i.e. should the spreadsheet now be considered the place to update?  (Allowing anyone to edit the spreadsheet doesn't seem like a good idea - e.g. I am able to edit it)
