### ISSUE TITLE
WHO logo flickers a lot

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#482]
https://deploy-preview-481--who-app-preview.netlify.com/#/

Scroll up and down the home menu.

**Comment by PieterAelse** [comment]
@advayDev1 I've opened a PR to improve the situation, for what I can see. But it's not a complete fix yet. For that the image might just be too large. I've added some suggestions to the PR description which might further improve the performance.

If you see the PR as an improvement, feel free to assign this ticket to me. If not, let's see what more could be done.

**Comment by hspinks** [comment]
@advayDev1 is this still relevant?
