### ISSUE TITLE
Vector Safety Animations

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#485]
Vector animations would be a great improvement for the initial safety advice screens. The benefit of vector animations is quality and size compared to gif or video. Design should be in consultation with the #design team on Slack.

I've heard back from @neurowave, who co-founded Rive animation with @luigi-rosso. Looks like they can help.

Animation goals:
* universally understandable across cultures
* understandable if they can't read the text
* localize by ethnicity or cultural practices

Animations, maybe a few seconds each? 
1) Washing hands
2) Avoid touching your face (eyes, mouth and nose)
3) Cover your mouth and nose with your bent elbow or tissue when you cough or sneeze
4) Social distancing
5) Avoid crowded places
6) Stay at home if you feel unwell - even with a slight fever and cough

WHO advice: https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public
Code: https://github.com/WorldHealthOrganization/app/blob/master/client/flutter/lib/pages/protect_yourself.dart
Text: https://github.com/WorldHealthOrganization/app/blob/master/content/flows/v1/protect-yourself.ww.en.yaml

**Comment by luigi-rosso** [comment]
Here's a high res preview of the animations:
https://cdn.rive.app/who/WHO%20%20App_Rive_file.mp4

With their respective names:
https://cdn.rive.app/who/WHO%20App_animations_full.mp4

Note that the Stay one was updated to include a line indicating the distance between the two people, you can see that in the app:
![image](https://user-images.githubusercontent.com/454182/77855133-5f422600-71a3-11ea-9e10-74d50cf7e2bf.png)

**Comment by brunobowden** [comment]
@luigi-rosso - though we could always make use of more animations. Feel free to close this one and then create new issues for other work that you'd like to do. I'm mindful of not imposing on your generosity.

**Comment by advayDev1** [comment]
Closing out in favor of any specific further animations to be added as distinct tasks.

Thanks so much for the hand washing animation - its fantastic!
