### ISSUE TITLE
Make mobile preview webpage

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#496]
Right now, to view the mobile preview from the latest master on a website, you can go to chrome devtools, right click -> inspect element, click “toggle device toolbar” icon and then select a device:

![image](https://user-images.githubusercontent.com/1689183/77828812-1d0ddb80-70f4-11ea-9bca-d84d9f285e32.png)

We should make a web page that just does this by default, though, (i.e., just shows https://preview.whoapp.org in a properly sized iframe with a border) so that users don’t have to go through the chrome devtools process

**Comment by dhruvilp** [comment]
@epicfaace I can do this if no one has done it. One question: where should I make it available (ex: https://preview.whoapp.org/#/mobileview) or add a button somewhere for mobileView?

**Comment by epicfaace** [comment]
@dhruvilp I was thinking the simplest way to do this would be to make a HTML file in the `docs` directory that embeds https://preview.whoapp.org/#/mobileview/ -- which is deployed to GitHub Pages.

It might be nice to embed the mobile view directly in preview.whoapp.org though, but I'm not sure how easy it would be to add a custom HTML page like this directly in Flutter -- do you have an idea of how that would work / how much custom code that would require?

**Comment by dhruvilp** [comment]
Based on dry run for existing codebase:
1. We could either use "FlutterWebView" --> display (https://preview.whoapp.org/#/) which requires adding new dependency to pubspec OR you could do _HTML_ embedding and place it at https://preview.whoapp.org/#/mobiledemo.html etc.
2. Do this: https://dartpad.dev/7913863abb64c2625a961c9d380aa610 (which is I would recommend at the moment).

Dry run screenshot:
![screenshot of mobile webview demo](https://i.ibb.co/kh6cFVT/Screen-Shot-2020-03-28-at-4-43-23-PM.png)

**Comment by dhruvilp** [comment]
@epicfaace I have tested (2nd option) on my end. It works so smoothly. Do you want me to make PR? I need access though.

**Comment by advayDev1** [comment]
We have decided to end web preview, as we reduce complexity to match our end-users' platforms (iOS and Android).
