### ISSUE TITLE
Dynamic content API v1 proposal

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#497]
Simple proposal for dynamic content backend part.

- Deploy to whoapp.org via netllify, from a `prod` branch.
- Use netlify redirects to implement a simple public rest api, for example:
`/api/news` => `/content/news.yaml`
`/api/advice` => `/content/advice.yaml`

Since changing the endpoints means updating the app via using clean endpoints will be better than using actual content paths.

Optionally we could have 1 endpoint that lists the URLs for the other, making it even cleaner, for example: `GET /api/endpoints` could return a mapping from keys to endpoints.

Netlify will support all this very easily and it will work via CI.

**Comment by advayDev1** [comment]
cc @crazybob - I'm not sure how much value there is in creating this - permanent - API to support for future versions when we def want to take into account, for example, region to provide locally relevant content in the future.

Once we put this out there, we have to support this v1 client forever.

**Comment by advayDev1** [comment]
Our news page for example is just 3 URLs which themselves point to current articles.

**Comment by SamMousa** [comment]
Then we just do the fixed endpoints and we're good, either way is fine; I don't have a clear view on the content so wasn't sure we needed this. Having a few fixed endpoints is of course even easier simpler!

This is only relevant if we're not doing dynamic code on the server side for v1 (which I understood).

**Comment by advayDev1** [comment]
Actually the proposal in standup was to punt the whole thing if needed.  Let's see how far @patniemeyer gets.

**Comment by hspinks** [comment]
@advayDev1 @SamMousa @crazybob - in the discussion with Product last night, it seemed like the News & Press section should not even consider individual articles, but instead open the WHO's website in a webview displaying those pages

<img width="216" alt="Screen Shot 2020-03-28 at 11 42 42 AM" src="https://user-images.githubusercontent.com/1484366/77830949-660c6280-70e9-11ea-80e7-8311426b314f.png">

E.g. each of those links is:

* [Situation Reports](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/)
* [Rolling Updates](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/events-as-they-happen)
* [News Articles](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/media-resources/news)
* [Press Briefings](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/media-resources/press-briefings)

**Comment by SamMousa** [comment]
It's fine if its punted, but if we need something simple then this is an option.

**Comment by patniemeyer** [comment]
@SamMousa Hitting a rest API would simplify things a bit for the client but would require that we have that endpoint working with a high degree of availability for Monday and that we keep it up going forward.  I had been assuming we'd do this statically to start, but since we will probably want a service for the location based content soon maybe using a service for both is fine and gives us more flexibility.  The service itself could just return URLs to a CDN, so it wouldn't have a huge load.  @crazybob  What do you think?

**Comment by advayDev1** [comment]
Closing.  Its implemented right now.  There's a separate proposal in #1068 if we need to revamp the API.
