### ISSUE TITLE
Consistent use of App Name across UI

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#499]
We should figure out what we're going to call the app, then consistently name it. For example, when you click the share button, it says "Check out the official COVID-19 Guide App". Before release, we need to find all occurrences of the app name, maybe refactor the name out into a constant `APP_NAME`, and then set the app name.

**Comment by ZacharyEilers** [comment]
I'm working on this right now

**Comment by hspinks** [comment]
Closing in favor of #599
