### ISSUE TITLE
[UI Issue] Questions Answered ExpansionTile trailing icon isn't changing after expansion

### ISSUE THREAD

**Issue by dhruvilp** [WorldHealthOrganization/app#506]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Issue:**
Your Questions Answered --> ExpansionTile is supposed to change (+) to (-) or (x) icon once expanded but is not doing it.

**Suggested fix:**
Utilize _onExpansionChanged_ field from "ExpansionTile" widget and update trailing icon value based on it.

**Screenshot Evidence:**
![Screenshot](https://i.ibb.co/Cpy7v4b/Screenshot-20200328-130627.png)

**Comment by PieterAelse** [comment]
Can be assigned to me, I'll pick this up.
