### ISSUE TITLE
Can you drop this link in your Slack please?

### ISSUE THREAD

**Issue by pde** [WorldHealthOrganization/app#516]
(Would have done so myself, but I see new invitations are closed at present)

Google Doc: [Shared Research on Privacy-Preserving Contact Tracing Apps](https://docs.google.com/document/d/1PsM3dMp10PX2mKFc1HLypLbCzeNwAMKM16ug8rQyA10/edit#)

**Comment by myiremark** [comment]
Thanks for your interest and suggestion!

Closing this issue to maintain a centralized list at:

https://github.com/WorldHealthOrganization/app/issues/324
