### ISSUE TITLE
some Emojis not diplaying at learn fact page

### ISSUE THREAD

**Issue by Baksman** [WorldHealthOrganization/app#523]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by gcarmix** [comment]
These are not showing, because some of them are available only for the latest OS versions,
let's try to choose emoji's available also in older releases, or import an up to date package of emoji in the project

**Comment by VlasovD** [comment]
Additional details.
As of now emojis are not displaying at these questions
- "What can I do to protect...?"
- "What are the treatment...?" 
- "How do I help children...?" 
Android 8.0.0 App v0.7.1 (14)

**Comment by advayDev1** [comment]
Please attach a screenshot of what it looks like along with your platform version

**Comment by advayDev1** [comment]
How bad is this from a product and design prioritization? @davidkaneda @asianfoodlab

**Comment by davidkaneda** [comment]
Can we just replace them? Separately, since there are a fair amount of emojis throughout, do we want to investigate swapping them with something consistent, ala [twemoji](https://twemoji.twitter.com)?

**Comment by VlasovD** [comment]
**Platform: Samsung Galaxy A7, Android 8.0.0**
![Screenshot_20200421-114751](https://user-images.githubusercontent.com/16258539/79846028-97b1da00-83c6-11ea-8f36-a396a7d46772.jpg)
![Screenshot_20200421-114709](https://user-images.githubusercontent.com/16258539/79846040-9a143400-83c6-11ea-8895-cc2533fe3e14.jpg)
![Screenshot_20200421-114732](https://user-images.githubusercontent.com/16258539/79846048-9bddf780-83c6-11ea-9c44-7e83b5ad40bf.jpg)
![Screenshot_20200421-114653](https://user-images.githubusercontent.com/16258539/79846054-9e405180-83c6-11ea-9696-c109d5814339.jpg)

**Comment by VlasovD** [comment]
**Reproduced on iPad mini Retina (iOS 9.0.2)**
![IMG_0130](https://user-images.githubusercontent.com/16258539/79985849-dd989c00-84b3-11ea-9e40-d6949736cf43.PNG)

**Comment by VlasovD** [comment]
For **Android 5.1.1** amount of broken emojis is much higher. Almost in every Q&A. Example below

<details>
<summary>Screenshots</summary>

![Screenshot_2020-04-23-16-47-13](https://user-images.githubusercontent.com/16258539/80106198-3898c480-8582-11ea-9b9c-e45f7bb88994.png)

</details>
