### ISSUE TITLE
Translate app to Tagalog (tl_PH)

### ISSUE THREAD

**Issue by dustincatap** [WorldHealthOrganization/app#528]
As a native speaker of the language, I can do the translations.

Related to #21

**Comment by piabianca09** [comment]
Hello, I'd like to help with the tl_PH translations. Pilipino din po. :)

**Comment by dustincatap** [comment]
@piabianca09 thanks! Any help is appreciated.

**Comment by piabianca09** [comment]
@dustincatap yes. you can contact me thru my email - bonillapiabianca@gmail.com

**Comment by Sarankumar18** [comment]
I would also like to help with the translations..

**Comment by sapte91** [comment]
Hi everyone! Thank you so much for your support of this project. We're thrilled that you want to contribute to localization of the app! Just so you're aware: We’ll primarily be sourcing and managing translations from Lingo24, our translation management system and we're only focusing on WHO's official languages (English, French, Spanish, Arabic, Russian and Chinese) for the next week or so. 

We definitely need translation volunteers going forward - as our set of supported languages and locales grows, there will be lots of opportunity to contribute! Our projected needs for the next two months are in native speaker LQA and translators for languages that we cannot support on Lingo24. We apologize though that we are still in the early process of figuring out how to manage all the contributions so stay tuned for more details coming soon. Until then, please fill out the volunteer form below and we’ll get back in touch shortly.

https://forms.gle/DTqvaqh4mE7bDe5U7

@Sarankumar18 @piabianca09 @dustincatap
