### ISSUE TITLE
[Proposal] Use .vscode or .workspace file for project configurations

### ISSUE THREAD

**Issue by dustincatap** [WorldHealthOrganization/app#537]
#### This is assuming the IDE that is being used for client/Flutter is Visual Studio Code.

I think it is a great idea to create project configurations using `.vscode` or `.workspace`. There are instances that this could be useful like:
- Extensions being used in the project.
- Different launch configurations.
- Code snippets.
- Dart/Flutter project-specific settings (i.e. ignored files to format, line length).

**Comment by advayDev1** [comment]
We don't enforce IDE requirements.  We will however introduce auto-formatting that will work at the pre-commit and CI level , so it doesn't depend on IDEs.
