### ISSUE TITLE
Create FAB for share buttons.

### ISSUE THREAD

**Issue by iambaljeet** [WorldHealthOrganization/app#554]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by Canarygo1** [comment]
I could resolve that issue

**Comment by iambaljeet** [comment]
Pull request submitted for the same.

https://github.com/WorldHealthOrganization/app/pull/555

**Comment by hspinks** [comment]
Closing as sharing is not a hallmark action of the app, and most share buttons have been removed from the design
