### ISSUE TITLE
Chinese version has a few issues

### ISSUE THREAD

**Issue by klliu** [WorldHealthOrganization/app#556]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [X ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [X ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Test environment:
Samsung Galaxy Tab A, Android 7.1.1, Simplified Chinese

Test Steps:
1) Install the WhoApp from trunk;
2) Start the WhoApp, click on different buttons;
3) From the attached screens, you can find a few issues below:
a. Some English strings are not translated;
b. The translation doesn't make sense;
c. The translation is totally wrong;
d. All three questions in NoTranslation1.png are same(|English version has same problem).

![WrongTranslation1](https://user-images.githubusercontent.com/9298452/77851878-80a61080-71a9-11ea-86f1-7755b4e798bf.png)
![WrongTranslation2](https://user-images.githubusercontent.com/9298452/77851883-8ac80f00-71a9-11ea-9665-85390930cd94.png)
![SomeNotTranslated](https://user-images.githubusercontent.com/9298452/77851888-961b3a80-71a9-11ea-94de-710030116b73.png)
![NoTranslation1](https://user-images.githubusercontent.com/9298452/77851900-9fa4a280-71a9-11ea-81e7-c7dc6349773e.png)

**Comment by sapte91** [comment]
Hi @klliu! Thank you so much for your support of this project. We're thrilled that you want to contribute to localization of the app! The translations you currently see in the app are machine translations and we're aware they're not 100% accurate. Just so you're aware: We’ll primarily be sourcing and managing translations from Lingo24, our translation management system, and we're only focusing on WHO's official languages (English, French, Spanish, Arabic, Russian and Chinese) for the next week or so. 

We definitely need translation volunteers going forward - as our set of supported languages and locales grows, there will be lots of opportunity to contribute! Our projected needs for the next two months are in native speaker LQA and translators for languages that we cannot support on Lingo24. We apologize though that we are still in the early process of figuring out how to manage all the contributions so stay tuned for more details coming soon. Until then, please fill out the volunteer form below and we’ll get back in touch shortly.

https://forms.gle/DTqvaqh4mE7bDe5U7

**Comment by klliu** [comment]
Hi @sapte91,

Thank you for letting me know the localization plan! 

Just completed the form, hope I can help at some point to the project.
