### ISSUE TITLE
Review app required permissions in AndroidManifest.xml

### ISSUE THREAD

**Issue by patniemeyer** [WorldHealthOrganization/app#56]
Review the permissions requested in: client/ionic/android/app/src/main/AndroidManifest.xml

**Comment by RohanTalip** [comment]
Does this need to be in the v0.1 milestone?

**Comment by myiremark** [comment]
@crazybob do we need any of the permissions in:

https://github.com/WorldHealthOrganization/app/blob/master/client/ionic/android/app/src/main/AndroidManifest.xml?

**Comment by myiremark** [comment]
@shankari

**Comment by brunobowden** [comment]
we must remove all unnecessary permissions for the first public release. We can always add them back selectively later on
