### ISSUE TITLE
Adding Dark Mode support, but WHO image is JPG instead of PNG with transparent background

### ISSUE THREAD

**Issue by dylanmaryk** [WorldHealthOrganization/app#567]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

I am adding Dark Mode support to the app, but the home screen looks wrong because the image at the top has a white instead of transparent background. Would it be possible to get this image as a PNG file with a transparent background?

![Simulator Screen Shot - iPhone 8 Plus - 2020-03-29 at 20 13 28](https://user-images.githubusercontent.com/605735/77856873-752f0580-71fa-11ea-8746-844690fc8ea6.png)

**Comment by vestial** [comment]
The top part has now changed to this, do you still need it?
![screenshot](https://user-images.githubusercontent.com/30844375/77960819-358b1b00-72d9-11ea-909b-a8e284a04e90.png)

**Comment by dylanmaryk** [comment]
The image at the top is a PNG now, so that's perfect, thank you!
