### ISSUE TITLE
Client: use a single SharedPreferences instance.

### ISSUE THREAD

**Issue by sheriffyusuf** [WorldHealthOrganization/app#569]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Refactor code to declare only one instance of sharedpreferences in lib/api/user_preferences.dart

**Comment by advayDev1** [comment]
@patniemeyer @theswerd reopen if you disagree, but I don't think this matters because the underlying implementation is effectively a singleton https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences/lib/shared_preferences.dart#L29
