### ISSUE TITLE
Render error in screen "who_myth_busters.dart"

### ISSUE THREAD

**Issue by Domirop** [WorldHealthOrganization/app#571]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

I found a render error while scrolling at this screen.

Test device: Pixel 3a

Screenshot: 
![imagen](https://user-images.githubusercontent.com/59377864/77862016-ad414300-7210-11ea-88b9-24931c106f49.png)
![imagen](https://user-images.githubusercontent.com/59377864/77862039-cfd35c00-7210-11ea-8413-578fac369438.png)

**Comment by britannio** [comment]
Pull the latest changes on the master branch. That screenshot is outdated.
