### ISSUE TITLE
Review text sizing / scaling in the tiles on the Home screen

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#576]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Looks like something might have changed since #505, see if there is better way to size text on the page

**Comment by hspinks** [comment]
@theswerd was this addressed in #590? if so, feel free to close

**Comment by brunobowden** [comment]
@theswerd - please close if this was addressed in #590

**Comment by theswerd** [comment]
👍 Resolved
