### ISSUE TITLE
Privacy policy link

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#58]
https://www.who.int/about/who-we-are/privacy-policy.

Link to the website.

**Comment by shankari** [comment]
Isn't this a dup of https://github.com/WorldHealthOrganization/app/issues/282?

**Comment by brunobowden** [comment]
@shankari - TOS is Terms of Service, aka License Agreement to limit liability and not steal copyright data. The Privacy Policy is separate and how WHO will respect people's privacy.
