### ISSUE TITLE
Add copyright text and version number to the bottom of the Home screen

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#580]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by britannio** [comment]
PR incoming

**Comment by hspinks** [comment]
See #590 and #623
