### ISSUE TITLE
Safe Hands Challenge - YouTube video

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#582]
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

WHO was interested in using the Director General's video for the Safe Hands Challenge. Need to figure out the design of this in contrast to the animation (which can be more easily localized). Perhaps the video is limited to English and only connections with sufficient bandwidth.
https://www.youtube.com/watch?v=y7e8nM0JAz0

Ideally the animation should have the animation use the numbers from this video. That could be paired up with the localized text.

**Comment by Domirop** [comment]
I would like to help

**Comment by britannio** [comment]
https://github.com/britannio/app/blob/e64e3bea4ac3fbccea276ffd51af61c5e7fd7f0a/client/flutter/lib/listViewPage.dart#L54
This might be a starting point if the youtube_player_flutter package is used.

**Comment by brunobowden** [comment]
punt for now

**Comment by advayDev1** [comment]
If this is still part of any upcoming design changes, bugs should be filed for those specific new client features.
