### ISSUE TITLE
Add full Mythbusters screen content

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#585]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Use YAML format agreed upon

**Comment by Dr-Legend** [comment]
@hspinks can I work on this?

**Comment by hspinks** [comment]
Closing for RC1 - any additional changes will require a separate ticket
