### ISSUE TITLE
Create News & Content screen

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#586]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Should be a static page with 4 buttons that open webviews to the WHO website's index pages for each category. Use these URLs:
* [Situation Reports](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/)
* [Rolling Updates](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/events-as-they-happen)
* [News Articles](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/media-resources/news)
* [Press Briefings](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/media-resources/press-briefings)

**Comment by Samaritan1011001** [comment]
I can work on this. I have been working with Flutter over the past two years and have developed and deployed apps. 

Can I be assigned to do this and be added to the design doc as well? Thank you.

**Comment by hspinks** [comment]
@Samaritan1011001 thanks for your interest in working on this, but it looks like this has already been implemented.

Closing in favor of #522
