### ISSUE TITLE
There is a problem with the arrow back button click area of ​​some pages

### ISSUE THREAD

**Issue by Moosphan** [WorldHealthOrganization/app#603]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**the screenshot like that**:

<img src="https://user-images.githubusercontent.com/31280310/77877292-f08ac880-7287-11ea-9a57-d65082aa745d.jpg" width = "270" height = "600" div align=left />

**Comment by Samaritan1011001** [comment]
Would you please explain a bit more? 
Which device are you using and when does it not work?

**Comment by Dr-Legend** [comment]
is it about the splash area?

**Comment by Moosphan** [comment]
@Dr-Legend @Samaritan1011001 I has found the problem and give a PR just now.

**Comment by britannio** [comment]
@Moosphan This can be closed now.

**Comment by Moosphan** [comment]
OK
