### ISSUE TITLE
Translate app to Swahili

### ISSUE THREAD

**Issue by moseuh** [WorldHealthOrganization/app#610]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [ ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by barakcodes** [comment]
I'm working on this I will be done as early as today

**Comment by advayDev1** [comment]
Closing in favor of #908
