### ISSUE TITLE
Adding provider for state management

### ISSUE THREAD

**Issue by hsul4n** [WorldHealthOrganization/app#616]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
If you are proposing a specific refactor of the client code, please open a new issue describing the change in design and why it is superior to the current solution.

cc @patniemeyer @theswerd
