### ISSUE TITLE
Translate app to  Ukrainian

### ISSUE THREAD

**Issue by minikin** [WorldHealthOrganization/app#622]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by minikin** [comment]
I'd like to do it.

**Comment by advayDev1** [comment]
Closing in favor of #908 where all such per-language requests will be centralized.
