### ISSUE TITLE
Localization: "Local asset bundle for en_US not found"

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#624]
When running the app I get these errors in the flutter console:

```
I/flutter (24524): Local asset bundle for en_US not found: Unable to load asset: assets/content_bundles/your_questions_answered.en_US.yaml
```

It appears to be looking for `assets/content_bundles/your_questions_answered.en_US.yaml`, but we only have a file named `assets/content_bundles/your_questions_answered.en.yaml`.

**Comment by advayDev1** [comment]
Pretty sure this is intentional.  It is how we fallback on client-side.

**Comment by advayDev1** [comment]
by design

**Comment by patniemeyer** [comment]
I will remove the log messages when I add proper tests for the loading mechanism.
