### ISSUE TITLE
Need Smooth, no flicker onboarding pages

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#625]
This should all be one flow, sliding from page to page if possible.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/11729521/77916893-a9ccac80-724e-11ea-9bd3-6804319d0086.gif)

**Comment by britannio** [comment]
https://pub.dev/packages/animations#shared-axis

**Comment by theswerd** [comment]
I am going to use a pageview
