### ISSUE TITLE
Users cannot tell which links/buttons leave the app

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#629]
It might be nice to clarify when the user is clicking on an external link so they know they will be leaving the app for their web browser. For example, the "Latest Numbers" and "Donate" buttons look the same as the other buttons, but maybe we could add an icon to distinguish them from other buttons that merely perform page navigations.

![image](https://user-images.githubusercontent.com/1689183/77920591-ad6f2c00-726c-11ea-89a8-cdb6ea81581d.png)

![image](https://user-images.githubusercontent.com/1689183/77920724-d55e8f80-726c-11ea-85d8-853c9bf8e392.png)

**Comment by 24thsaint** [comment]
Something like this?
![Screenshot_1585582463](https://user-images.githubusercontent.com/8315544/77931669-09729880-72df-11ea-91fa-686f7066ca21.png)
![Screenshot_1585582466](https://user-images.githubusercontent.com/8315544/77931672-0b3c5c00-72df-11ea-9851-f155ba0d5d59.png)

**Comment by vestial** [comment]
I think an AlertDialog like this will be helpful:

![warning](https://user-images.githubusercontent.com/30844375/77959868-9ca7d000-72d7-11ea-90ee-f478c899e81b.png)

**Comment by avkvirtru** [comment]
An alert dialog is only helpful if, as a user, I tapped on a link by mistake. For everyone intentionally trying to get at the information, it only adds an extra step. The extra friction isn't worth it, imo.

**Comment by SamJakob** [comment]
I think perhaps place the link icon directly to the left or right or the title - or use an external link icon link this one ( <img src="https://user-images.githubusercontent.com/37072691/78060952-58bed480-7384-11ea-97ef-9afc36e2d86a.png" width="10px"> )

**Comment by SamJakob** [comment]
Also in this specific case, I think rather than open them in the web browser, links should be opened with Chrome Custom Tabs 
![performance](https://user-images.githubusercontent.com/37072691/78063397-0e3f5700-7388-11ea-8f80-c5fea78fea6c.gif)

**Comment by advayDev1** [comment]
@davidkaneda let us know how you want to deal with this, or plz close

**Comment by davidkaneda** [comment]
This was much more of an issue when "Recent Numbers" was linking out. For stuff like "Donate" I think it's fine-
