### ISSUE TITLE
Investigate viability of Ionic React for native functionality beyond v0.1

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#63]
For v0.1 and initial launch, Ionic React is the fastest way to get a meaningful MVP on the App Store that will handle distribution of necessary information and triaging. Downstream product requirements may necessitate more native functionality (e.g. background location fetch, etc) that is handled better by fully-native solutions like React Native rather than PWA

**Comment by advayDev1** [comment]
Per today's standup, there is still a product uncertainty over whether we need to support a pure webapp in the future.  If we decide to do that to expand reach, we should stick with Ionic React and not React Native to avoid having to develop both a React and ReactNative codebase for which there would be likely little code-sharing.

**Comment by hspinks** [comment]
agreed. will try to push on web app support needs

**Comment by sstur** [comment]
Hey guys, I'd be keen to help out with this effort, either in React Native or in React/Ionic. I filled out the volunteer form but let me know if you can add me to your design prototype or your Slack and I'll jump right in with some PRs. Thanks!
sstur@me.com

**Comment by advayDev1** [comment]
@sstur I too do not know how to send a PM on GitHub, so use the slack link in https://github.com/WorldHealthOrganization/app/blob/master/ONBOARDING.md thanks! Good to have React experts here.

**Comment by sstur** [comment]
Oh, awesome, thanks for the quick response!

**Comment by advayDev1** [comment]
Its a quick turnaround time kind of project :D
