### ISSUE TITLE
Translate app to Turkish

### ISSUE THREAD

**Issue by akayibrahim** [WorldHealthOrganization/app#638]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by akayibrahim** [comment]
I'd like to work on this.

**Comment by advayDev1** [comment]
Closing in favor of #908 where all such per-language requests will be centralized.
