### ISSUE TITLE
Translate app to German

### ISSUE THREAD

**Issue by JulianAssmann** [WorldHealthOrganization/app#639]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [✔️] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [✔️] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by JulianAssmann** [comment]
I'd like to work on this (native german speaker).

**Comment by advayDev1** [comment]
Closing in favor of #908
