### ISSUE TITLE
Stand up initial server side setup to serve static content

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#64]
For dynamic content in the app

**Comment by vpaulino** [comment]
What is the backend tech stack chosen? Databases tech? Messaging stack? Push notifications?

**Comment by sstur** [comment]
/subscribe
I'd be curious to be part of the discussion for this (I'm partial to Prisma.io and GraphQL and can try to sell the team on that ; )

**Comment by 24thsaint** [comment]
Seeing initial server setup to be Java. Is this final? Or is it still open for contributions (eg. a NodeJS backend)?

**Comment by hspinks** [comment]
Closed in #595
