### ISSUE TITLE
Create Settings screen to design spec with ability to opt out of analytics

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#640]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by ShivamSinghania** [comment]
Assign this one to me. 
Analytics is currently enabled by default, has legal approved that ? That is we want opt-out & not opt-in ?

**Comment by patniemeyer** [comment]
@advayDev1 @crazybob Did this requirement return?  I thought we pushed this past 1.0.

**Comment by dhruvilp** [comment]
@hspinks Implemented Settings Page + plus support for 6 official languages made PR #654

**Comment by ShivamSinghania** [comment]
Waiting on #621 & #658 to be merged first.
