### ISSUE TITLE
Implement push notification registration on client

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#642]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Consume API configured in #595 to register devices for push notification delivery. This is the generic, non-locale-aware version of #641

**Comment by BakhtaverSingh** [comment]
This is for a ANDROID or i phone?
I can help for android with firebase and node js

**Comment by hspinks** [comment]
for some reason, I can't assign @cbgrey to this, but both he and @patniemeyer are tag teaming this one today!
