### ISSUE TITLE
Update all image assets in app to final, approved assets

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#643]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Blocked on awaiting final assets

**Comment by Domirop** [comment]
@hspinks I want resolve this issue. Can you asigned it me?

**Comment by hspinks** [comment]
@Domirop thanks for your interest. This is mostly blocked by needing image assets, so we will handle on our end as we receive them

**Comment by hspinks** [comment]
@advayDev1 does #655 close this, or are there more images that we want swapped out before full design review?

**Comment by hspinks** [comment]
Closing for RC1 - any updated image assets needed from here should be filed as separate tickets
