### ISSUE TITLE
Publish dynamic content on App Engine

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#644]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Make sure server is serving the correct content ~or turn off the flag enabling dynamic content being fetched from the client~

**Comment by advayDev1** [comment]
This will be in the content subdirectory of appengine, https://whocoronavirus.org/app cc @patniemeyer 

How about we softlink all of this from the client bundle for now?

**Comment by hspinks** [comment]
Feature flag turned off in #708

**Comment by crazybob** [comment]
Where in Git is the content I need to host?

**Comment by crazybob** [comment]
Not seeing yaml files.

**Comment by myiremark** [comment]
https://github.com/WorldHealthOrganization/app/tree/master/client/flutter/assets

I'll move this to content dir and sym link.

**Comment by hspinks** [comment]
Closed in #840
