### ISSUE TITLE
Create About screen

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#645]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Includes app credits and links to TOS and Privacy Policy

**Comment by creativecreatorormaybenot** [comment]
I can do the credits part if needed. FYI, I have already implemented the fetching capability in #552. I understand that there is a UI spec for this. If I could get access to it, I could work on it.

**Comment by Domirop** [comment]
@hspinks I want resolve this issue. Can you asigned it me?

**Comment by advayDev1** [comment]
Hey folks, if it is assigned please don't reassign.

**Comment by advayDev1** [comment]
Closed by #707
