### ISSUE TITLE
Improve Russian translation

### ISSUE THREAD

**Issue by minikin** [WorldHealthOrganization/app#646]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
THis is not actionable,
