### ISSUE TITLE
Network Security: TLS 1.2 min, SSL and ingress restrictions Terraform

### ISSUE THREAD

**Issue by myiremark** [WorldHealthOrganization/app#649]
Adding the network security requires allocating a global static IP address and load balancer. Once added, the load balancer allows you to apply the TLS and SSL restrictions. This is configured for the WHO GCP production server but needs to be added to Terraform.

Google Setup:
1. Reserve IP Address [Ref](https://cloud.google.com/load-balancing/docs/negs/setting-up-serverless-negs#ip-address)
   - Network Service Tier: Premium
   - IP Version: IPv4
   - Type: Global
1. Load Balancer [Ref](https://cloud.google.com/load-balancing/docs/negs/setting-up-serverless-negs#creating_the_load_balancer)
   - Type: Layer 7 HTTPS
      - Backend:
         - Backend: Serverless network endpoint group
         - Protocol: HTTPS
         - New Serverless network endpoint group
            - Service: App Engine
         - Enable Cloud CDN:
            - Select "Use origin settings based on Cache-Control headers" to reduce chance of mistaken caching of private data
      - Frontend:
         - Protocol: HTTPS
         - IP: as reserved above
         - TLS: minimum TLS 1.2
         - Profile: modern (incase we support a web app in the future)
1. http => https redirect
   - https://cloud.google.com/load-balancing/docs/https/setting-up-http-https-redirect#partial-http-lb
1. Cloud Armor on the same backend
   - No configuration, so I presume it's applying standard defaults
1. App Engine:
   - App Engine Firewall [ref](https://console.cloud.google.com/appengine/firewall?project=who-myhealth-staging)
   - Ingress limited to load balancer only and disable custom domain [Ref](https://cloud.google.com/appengine/docs/standard/python/application-security#ingress_controls). Example as command line but needs to be implemented in Terraform:
```
gcloud beta app services update default --ingress internal-and-cloud-load-balancing
```
After setup, we'll need to manually update the DNS records with the static IP addresses.

## Problem
TLS 1.0 and 1.1 are enabled on https://staging.whocoronavirus.org/. This is returning a B rating from SSL labs:
https://www.ssllabs.com/ssltest/analyze.html?d=staging.whocoronavirus.org&latest

## Testing

Need to check SSL Lab status on all the domains: staging and production

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by myiremark** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=staging.whocoronavirus.org

**Comment by myiremark** [comment]
Proxying outbound traffic from CDN --> app in TLS 1.2 is a viable potential solution

**Comment by advayDev1** [comment]
Supposedly we can ask Google support and they will restrict TLS versions for us: https://stackoverflow.com/a/55192541

**Comment by brunobowden** [comment]
FYI @marcmcl

**Comment by brunobowden** [comment]
@epicfaace - FYI for you

**Comment by brunobowden** [comment]
Test deployment on https://staging-ipv4.whocoronavirus.org/app has TLS 1.0 and 1.1 disabled. Now reports "A" rating from SSL Labs. This issue will remain open until it's implemented in Terraform. FYI @marcml.

SSL Labs still warns on several more minor issues:
1. Lack of [DNS CAA](https://en.wikipedia.org/wiki/DNS_Certification_Authority_Authorization)
1. Session resumption (caching)	No (IDs assigned but not accepted)
1. Weaker TLS 1.2 ciphers still supported:
```
# TLS 1.2 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK	128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK	256
(P) This server prefers ChaCha20 suites with clients that don't have AES-NI (e.g., Android devices)	
```
1. Unsupported on Android 4.3 and below + older browsers. This fits perfectly with our Android minimum spec of Android 4.4.
```
# Not simulated clients (Protocol mismatch)
Android 2.3.7   No SNI 2	Protocol mismatch (not simulated)
Android 4.0.4	Protocol mismatch (not simulated)
Android 4.1.1	Protocol mismatch (not simulated)
Android 4.2.2	Protocol mismatch (not simulated)
Android 4.3	Protocol mismatch (not simulated)
Baidu Jan 2015	Protocol mismatch (not simulated)
IE 6 / XP   No FS 1   No SNI 2	Protocol mismatch (not simulated)
IE 7 / Vista	Protocol mismatch (not simulated)
IE 8 / XP   No FS 1   No SNI 2	Protocol mismatch (not simulated)
IE 8-10 / Win 7  R	Protocol mismatch (not simulated)
IE 10 / Win Phone 8.0	Protocol mismatch (not simulated)
Java 6u45   No SNI 2	Protocol mismatch (not simulated)
Java 7u25	Protocol mismatch (not simulated)
OpenSSL 0.9.8y	Protocol mismatch (not simulated)
Safari 5.1.9 / OS X 10.6.8	Protocol mismatch (not simulated)
Safari 6.0.4 / OS X 10.8.4  R	Protocol mismatch (not simulated)
```
New "A" rating from SSL Labs (only deployed on test domain):
<img width="1023" alt="Screen Shot 2020-11-03 at 8 27 24 AM" src="https://user-images.githubusercontent.com/679339/98012926-83578c80-1dae-11eb-87de-8b676adcb7d2.png">
