### ISSUE TITLE
Stand up initial client side setup to populate app with dynamic content

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#65]
Using server side setup from #64, integrate dynamic content into the app. Should bake the initial content directly into app bundle for offline functionality, but server side content can override

**Comment by advayDev1** [comment]
@hspinks #24 was originally vNext, while this is v1, please clarify timeline for dynamic content

**Comment by hspinks** [comment]
@advayDev1 good catch, moved to vNext

**Comment by hspinks** [comment]
Closed in #588
