### ISSUE TITLE
Add Turkish translation

### ISSUE THREAD

**Issue by kbuyukburc** [WorldHealthOrganization/app#650]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by kbuyukburc** [comment]
I am a native Turkish speaker. I can translate intl_en_US.arb . Do I need anything else to approve pull request?

**Comment by advayDev1** [comment]
Dupe of #638
