### ISSUE TITLE
Page header overflowing on smaller phones

### ISSUE THREAD

**Issue by tomgilder** [WorldHealthOrganization/app#651]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

On iPhone 5 the page header looks like this:

![Simulator Screen Shot - iPhone 5s - 2020-03-30 at 21 59 20](https://user-images.githubusercontent.com/756862/77954569-7a15b700-72d7-11ea-92b5-a6c9a279a955.png)

I'm fixing now, PR shortly.

**Comment by patniemeyer** [comment]
We have a `contentScale()` factor that you could use if you want.

**Comment by tomgilder** [comment]
@patniemeyer I saw it, but it only looks at device height and not width - and width is all that matters in this case, didn't want to break anything using that method at this stage

**Comment by Samaritan1011001** [comment]
Hey @tomgilder and @patniemeyer 

I figured using Flexible made more sense here and it's solves our problem. It basically renders it's child based on the available space and this is can be complimented with a FittedBox on the Text which fits the text in the available space. 
It works well on small screens as well as the web

I created a PR for the same. Let me know what you think.

**Comment by tomgilder** [comment]
@Samaritan1011001 I feel that the logo needs reducing in size on smaller phones, it just looks wrong being the same size, maybe we need to ask a designer...

**Comment by Mawulijo** [comment]
I just wrapped the Image in Expanded Widget and placed a sizedBox of width 4.0 between the Column and the Expanded wrapping the Image.

**Comment by patniemeyer** [comment]
@Samaritan1011001 which PR?
