### ISSUE TITLE
Integrate Singapore's BlueTrace Bluetooth Tracing Technology

### ISSUE THREAD

**Issue by 123AndGo** [WorldHealthOrganization/app#661]
Singapore's government will be releasing for free and in open source their "BlueTrace" bluetooth tracing technology, which they are using in their official tracing app (TraceTogether). This could be complemented with geolocation, for tracing and for mandatory isolation monitoring.

I really think this could be a home-run to beat the coronavirus: https://medium.com/@andresdavidgalindoolarte/how-to-beat-the-coronavirus-b21041b8addb

Some links about Singapore's technology:

- Video of how Singapore’s tracing app works: https://youtu.be/buj8ZTRtJes

- BlueTrace’s project website: https://bluetrace.io/

- TraceTogether official website: https://www.tracetogether.gov.sg/

I guess you are already aware and are reviewing to integrate this technology but if not, it is really important that you can review it.

Thank you!

---
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by i5qme2b944w3** [comment]
May not be compatible with this project's goal of respecting privacy, but there are other implementations of contact-tracing that avoid this problem.

The TraceTogether project is designed around a trusted central authority (Singapore's Ministry of Health) which has access to personally identifiable data (phone numbers) of all users. (That said, it looks like the central authority does not get access to full contact-trace data until a user opts to hand them over, e.g. upon being diagnosed with the coronavirus.) A single global trusted authority for this data is probably a privacy (and maybe legal?) issue, and also probably politically unpalatable for some.

Other open-source projects (e.g. [covid-watch.org](https://covid-watch.org)) have been implementing decentralized contact-tracing which avoids this problem. More resources listed in #324.

**Comment by 123AndGo** [comment]
Thank you for the response. I understand your point. 

The covid watch technology also seems very promising, although i haven't been able to compare both technologies in detail.

I think the most important aspect is to be able to use a Bluetooth-based technology and not just geolocation. Bluetooth-based contact tracing has more advantages than geolocation-only contact tracing.

**Comment by hspinks** [comment]
Thanks for the suggestions! I've added these comments to #324
