### ISSUE TITLE
Label all string change PRs from today for Loc team

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#662]

**Comment by britannio** [comment]
https://github.com/WorldHealthOrganization/app/pull/630 might be relevant as it changes `commonWorldHealthOrganizationCoronavirusApp`

**Comment by hspinks** [comment]
ok, I believe I have done this for all PRs going back to #615. I erred on the side of caution, so if there were ones I was unsure about, I tagged them for @sapte91 to triage later. closing for now, will continue to be vigilant on any new PRs opened
