### ISSUE TITLE
feat: fetch user pref for data collection in Settings Page

### ISSUE THREAD

**Issue by dhruvilp** [WorldHealthOrganization/app#668]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**TODO:**
In `app/client/flutter/lib/pages/settings_page.dart` fetch user preferences on data collection & 
1. _GET_ `bool _switchValue = [user_pref_value];` **line 23**
2. _SET_ new pref and update shared_pref: **line 47**

**Comment by advayDev1** [comment]
closing for #674
