### ISSUE TITLE
feat: turn on/ogg Google Analytics in Settings

### ISSUE THREAD

**Issue by dhruvilp** [WorldHealthOrganization/app#670]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**TODO:**
In `app/client/flutter/lib/pages/settings_page.dart`
1. Add logic to turn ON/OFF Google Analytics` **line 44**

**Comment by advayDev1** [comment]
Closed for #674
