### ISSUE TITLE
Analytics flow

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#674]
The currently approved plan is:
- All google analytics off on first start.
- Once someone acks the ToS and PP, analytics is turned on for that run and for future runs.
- Analytics is turned off based on the settings opt out, which is saved.

We have a settings page checked in
 We have Google Analytics checked in that is always off as submitted.
We have a tos page checked in.

This bug hooks them together.

**Comment by advayDev1** [comment]
TODO:
In app/client/flutter/lib/pages/settings_page.dart

Add logic to turn ON/OFF Google Analytics` line 44

**Comment by advayDev1** [comment]
TODO:
In app/client/flutter/lib/pages/settings_page.dart fetch user preferences on data collection &

GET bool _switchValue = [user_pref_value]; line 23
SET new pref and update shared_pref: line 47

**Comment by ShivamSinghania** [comment]
I am already working on this to close #640 .

**Comment by advayDev1** [comment]
Great!
