### ISSUE TITLE
Create strategy for triage survey definition

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#68]
Overall tech design of how we are defining the survey questions that will be a part of the Diagnosis & Triage goal of the app. Should be able to be baked into the app bundle for offline functionality, but also with the ability to be overridden with updates from the server. This task should include a plan for the relevant data structures, internationalization, etc

**Comment by epicfaace** [comment]
It may be good to define the actual data structure using [JSON Schema](https://json-schema.org/). We could serialize the data structure of what we want to collect in a local JSON file that is stored offline, then update them as needed from the server.

We could use a library such as [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form) for rendering the forms from JSON Schema -- note that I maintain this library, meaning that I have lots of experience making complex forms with it.

You can see some examples of forms rendered from schemas in the [playground here](https://rjsf-team.github.io/react-jsonschema-form/).

We could use react-i18n in conjunction with this library for internationalization.

Note that this library currently only works for web, though. This would mean that it would be fine with Ionic React, but would require us to embed a WebView if we were to use React Native (which is ugly, but feasible and works offline).

**Comment by advayDev1** [comment]
+ @crazybob as well

**Comment by SamMousa** [comment]
Have a look at survey-react it does what we need and has i18n.
Forms and surveys are not the same thing even though they are very similar.

**Comment by sapte91** [comment]
Hi everyone,

Before discussing implementation details, let’s agree on key capabilities of the tool that impact the survey and response tech design/definition. I’ve read through The Who App Synthesis and Kickoff docs and pulled some ideas together. 

[https://docs.google.com/document/d/1j2bYVIK5sQ-suixbNfYzT8VnwUyeJfst8apP2Npfqjo/edit?usp=sharing](Capabilities listed in this doc)

I think we'd focus on a subset of capabilities for v0 (maybe tackle only one survey taking method to start?) but build with all in mind. 

Please review for correctness and completeness. We should also run this by the Product team.

**Comment by SamMousa** [comment]
I don't see conversational mode as a big pro for our app. Unlike the WeChat example our app isn't chat related. Unless it's a free form conversation I don't see an advantage to doing a closed question survey via chat.

Survey by voice needs clarification: voice entry or just reading questions and options out loud?

**Comment by cristianlorand** [comment]
Hi everyone,
I would have a few suggestions for the triage function:
1. Splitting the questionnaire into 2 categories: general/informational questions related to patient with his past interaction (was he in risk of contacting COVID-19 or any other virus) and second medical relevant questions (symptoms matrix similar to common cold questionnaire, temperature, BP, SpO2, etc.);
2. Build this functionality as interface/base class with inheritance where the assessment logic can immediately incorporate new data and research approved by WHO to better asses the risk factor of the patient;
3. Make it a score/percentage based, including location of the patient, environmental factor(s) (ex: pollution based lung degradation), data which is deemed important by WHO or is considered to impact the patient;
For point 2, the mobile app can be used to asses the vital signs where user lacks the equipment to perform the investigation.

This self assessment can be made interactive where required, like temperature checked 3 times in a time span of a day, or same with BP (parameters needs confirming by WHO) and the app will notify user when to perform the checks and only after that the score is calculated. This could increase accuracy of the triage.
This could relieve pressure significantly on the medical systems around the world especially in "hot" zones.

I can assist with the design and implementation of these features, collaborate with contributors who are already involved in this project

**Comment by cristianlorand** [comment]
Hi everyone,
@hspinks , @SamMousa .. Is this thread still active or of interest to the team ? Sorry for asking, just didn't see any activity on it.
If it still is, we could work on it in parallel with other users who are willing and have the time and integrate the work once the core team is ready to review and integrate.

**Comment by SamMousa** [comment]
At this point all efforts are focused in getting to a first release; after that we'll go over all other issues and assign them a priority. Until then there's no capacity to get new contributors onboarded.

Please be patient a little longer until we get our processes in order!

**Comment by fabiosantoro** [comment]
[wireframe1-SymptoSELFQuarantine.pdf](https://github.com/WorldHealthOrganization/app/files/4432575/wireframe1-SymptoSELFQuarantine.pdf)


https://github.com/fabiosantoro/app/blob/master/Governments%20Symptomatic%20Map%20App%20COVID19%20AutoQuarantena-Selfquarantine%2003-04-20.pdf

**Comment by hspinks** [comment]
Update: we are currently exploring integrations with existing symptom checkers subject to algorithm approval from WHO. Closing this issue for now pending that exploration
