### ISSUE TITLE
Add "share this app" functionality

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#69]
Should use native share sheets - look into Ionic's [Social Sharing](https://ionicframework.com/docs/native/social-sharing) and [Action Sheet](https://ionicframework.com/docs/native/action-sheet) components. Should be a modular component that can be reused in the app

**Comment by theswerd** [comment]
Is there any string you want me to put as the current share string. @hspinks

**Comment by advayDev1** [comment]
You did it, but in Flutter :)

**Comment by hspinks** [comment]
Added in Flutter v0.1!
