### ISSUE TITLE
Change Protect Yourself Page

### ISSUE THREAD

**Issue by jasonTelanoff** [WorldHealthOrganization/app#691]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Change the Protect Yourself page to match the Figma. I think it's only the header's weight.

**Comment by hspinks** [comment]
Closed in #692
