### ISSUE TITLE
Update Travel Advice Page

### ISSUE THREAD

**Issue by jasonTelanoff** [WorldHealthOrganization/app#695]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Update Travel Advice Page to match Figma by changing text colors.

**Comment by hspinks** [comment]
Closed in #696
