### ISSUE TITLE
Change HomePage button height

### ISSUE THREAD

**Issue by jasonTelanoff** [WorldHealthOrganization/app#697]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Change the HomePage button height to match Figma and make the Donate Now button more accessible.

**Comment by hspinks** [comment]
Closed in #698
