### ISSUE TITLE
Investigate ionic's use of runtime dependencies for developer infra

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#70]
Generally, type definitions, the typescript compiler, and similar are `devDependencies`.  Tracking issue to investigate why they are `dependencies` in ionic and ensure we are not shipping all of these libraries to end users.   If this is intentional, close as by design.

**Comment by mhartington** [comment]
Hey there! Mike from the ionic team...

We don't modify the package.json too much from what you get with create-react-app (aside from adding ionic and the router).

Here are the deps from an app created using 

```bash
npx create-react-app my-app --typescript
```

```json
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.0",
    "typescript": "~3.7.2"
  },
```

**Comment by RohanTalip** [comment]
Please ignore the recent commit / issue that mention this issue: I got the issue number wrong.
