### ISSUE TITLE
Fix typos and add missing question in q&a content

### ISSUE THREAD

**Issue by sapte91** [WorldHealthOrganization/app#702]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [ X] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [X ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by hspinks** [comment]
Closed in #703
