### ISSUE TITLE
Create firebase android app for org.who.WHOMyHealth

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#721]

**Comment by advayDev1** [comment]
And we can still keep org.who.WHOMyHealth (google) and int.who.WHOMyHealth (ios) associated together right?

**Comment by epicfaace** [comment]
Yes

**Comment by hspinks** [comment]
Closing since it was communicated on Slack that this was done! @epicfaace if that isn't right, please reopen this issue
