### ISSUE TITLE
Deployment: text assets needed for app store listings for v1.0

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#727]
## iOS
- [ ] Name (0-30 chars)
- [ ] Subtitle (0-30 chars)
- [ ] Privacy Policy URL (#58)
- [ ] [Primary Category](https://developer.apple.com/app-store/categories/)
- [ ] Keywords (0-100 chars)
- [ ] Description (0-4000 chars)
- [ ] Contact info: first name, last name, email, phone number
- [ ] Fill out questionnaire for Age Rating

OPTIONAL for iOS
- [ ] Promotional Text (0-170 chars) (appears above description)
- [ ] Copyright text (such as  "2008 Acme Inc.")
- [ ] Secondary Category

App Store should add the following keywords:
* Coronavirus
* COVID
* COVID-19
* WHO
* World Health Organization
* Organisation Mondiale de la Santé
Google Trends data shows "Coronavirus" as being the most popular
https://trends.google.com/trends/explore?date=today%203-m&q=Coronavirus,COVID,WHO,COVID-19,World%20Health%20Organization

## Android

- [ ] Title (0-50 chars)
- [ ] Description (0-80 chars)
- [ ] Full description (0-4000 chars)
- [ ] [Application Category](https://support.google.com/googleplay/android-developer/answer/113475), Tags
- [ ] Fill out questionnaire to get content rating
- [ ] Contact email
- [ ] Privacy Policy URL

OPTIONAL for Android
- [ ] Promo video (YouTube URL)
- [ ] Website URL
- [ ] Contact phone

(copied from #188 for v1.0)

**Comment by brunobowden** [comment]
@crazybob - please upload the marketing text to the App Store, we should share doc with WHO for their approval

**Comment by crazybob** [comment]
@jessicahladd Here's the original description: https://docscgoogle.com/document/d/1CjzP_Va0s6KtdTT_PYe4uu9QWsEFBiCu1xVqYKDIFco/edit

Mind updating it to match the current functionality?

**Comment by crazybob** [comment]
This is just something I wrote—feel free to make it your own.

**Comment by effieseiberg** [comment]
Hello, see https://docs.google.com/document/d/1d2klHX5O60XKk-ADJG91te4-_xM2R47Nv1d5zvTuZ5Q/edit?usp=sharing for updated Android and iPhone app store copy. (Please let me know if there are any access issues or other questions!)

**Comment by brunobowden** [comment]
Just finished going through this WHO.
