### ISSUE TITLE
Deployment: image assets needed for app store listings

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#728]
## iOS

Screenshots ([exact dimensions of all possible screenshots here](https://help.apple.com/app-store-connect/#/devd274dd925)):

- [x] 1 screenshot for iPhone 5.5" display (1242 x 2208 pixels (portrait) or 2208 x 1242 pixels (landscape))
- [x] 1 screenshot for iPhone 6.5" display (1242 x 2688 pixels (portrait) or 2688 x 1242 pixels (landscape))
- [x] 1 screenshot for iPad Pro (3rd Gen) 12.9" display (2048 x 2732 pixels (portrait) or 2732 x 2048 pixels (landscape))
- [ ] 1 screenshot for iPad Pro (2nd Gen) 12.9" display (2048 x 2732 pixels (portrait) or 2732 x 2048 pixels (landscape))
- [x] App Store Icon (1024 x 1024)

OPTIONAL for iOS
- [ ] Up to 10 screenshots and 3 [App Previews](https://help.apple.com/app-store-connect/#/dev4e413fcb8) for each device size

## Android

All files need to be JPEG / PNG ([more info on exact requirements](https://support.google.com/googleplay/android-developer/answer/1078870)).

- [x] 2 screenshots overall, which can be across any of the form factors (Phone / Tablet). Would be good to get 1 phone screenshot and 1 tablet screenshot.
  - Min length for any side: 320px. Max length for any side: 3840px.
- [x] High-res icon, 512 x 512 32-bit PNG, has to be less than 1024 KB
- [x] Feature graphic, 1024px by 500px (#250) - https://user-images.githubusercontent.com/54385392/77468970-9becd680-6dcb-11ea-928f-ba402f3e1376.png

OPTIONAL for Android
- [ ] Promo graphic, 180 w x 120 h

(copied from #187 for v1.0)

**Comment by Moosphan** [comment]
<details>
<summary>HUAWEI Mate8</summary>

![754EEB521BE803EAA1EC71C116F0DF1F](https://user-images.githubusercontent.com/31280310/78204484-333ce280-74cc-11ea-9f50-c5eeea74d545.jpg)
![131E20C6BF158E165A818500BB1FBD87](https://user-images.githubusercontent.com/31280310/78204487-36d06980-74cc-11ea-9408-607c0c4cd2fc.jpg)
![3A1FC46CE09ADDA63C5F950723A1F426](https://user-images.githubusercontent.com/31280310/78204491-3afc8700-74cc-11ea-8013-2264713d3612.jpg)
![8B2FED0DBE8B2AF55FE2D8A21F8209CB](https://user-images.githubusercontent.com/31280310/78204565-6b442580-74cc-11ea-81d0-44f5de25e2a3.jpg)
![00D10E68FD0338479E0E78EEF33E800C](https://user-images.githubusercontent.com/31280310/78204572-70a17000-74cc-11ea-9a8f-a756ca0398a2.jpg)
![AFC8C4202540E26A3331129E757FBE77](https://user-images.githubusercontent.com/31280310/78204577-7434f700-74cc-11ea-8063-6b4eb9d5d071.jpg)
![F097DFD8C8537EE7DB125E771FFCE0D7](https://user-images.githubusercontent.com/31280310/78204583-76975100-74cc-11ea-923d-9c8eb3575684.jpg)
![C7E8F6F244F97A00B6D21D9E9029E131](https://user-images.githubusercontent.com/31280310/78204595-7d25c880-74cc-11ea-9da1-6a62b7b84dc7.jpg)
![7F954A02411A7F8BB7FAD83264EE92B3](https://user-images.githubusercontent.com/31280310/78204599-8151e600-74cc-11ea-8cb8-60774de46636.jpg)
![679219A35EFC83FBA9EB64B2EECD4149](https://user-images.githubusercontent.com/31280310/78204602-84e56d00-74cc-11ea-9e23-2330b7536d18.jpg)

</details>

**Comment by nLoops** [comment]
<details>
<summary>iPhone 11 pro max - 6.5</summary>

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-02 at 08 50 17](https://user-images.githubusercontent.com/33456094/78219232-6af15d80-74bf-11ea-9043-9dd846fc3fa7.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-02 at 08 50 22](https://user-images.githubusercontent.com/33456094/78219237-6e84e480-74bf-11ea-9b07-4af7e95ed23c.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-02 at 08 50 40](https://user-images.githubusercontent.com/33456094/78219240-70e73e80-74bf-11ea-957f-9d8beb89a3b6.png)
</details>


<details>
<summary>iPhone 8 plus - 5.5</summary>

![Simulator Screen Shot - iPhone 8 Plus - 2020-04-02 at 08 57 37](https://user-images.githubusercontent.com/33456094/78219577-1b5f6180-74c0-11ea-8cb7-4db2036f1834.png)

![Simulator Screen Shot - iPhone 8 Plus - 2020-04-02 at 08 58 03](https://user-images.githubusercontent.com/33456094/78219591-1f8b7f00-74c0-11ea-8bc9-827bcaaa3899.png)

![Simulator Screen Shot - iPhone 8 Plus - 2020-04-02 at 08 58 13](https://user-images.githubusercontent.com/33456094/78219596-20bcac00-74c0-11ea-93ad-8645f7239ae0.png)
</details>

<details>
<summary>iPad 12.9</summary>

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-04-02 at 09 04 05](https://user-images.githubusercontent.com/33456094/78220139-426a6300-74c1-11ea-96f8-dc8e9a80a40c.png)

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-04-02 at 09 04 19](https://user-images.githubusercontent.com/33456094/78220154-46968080-74c1-11ea-85c1-b228a7b2c901.png)

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-04-02 at 09 04 28](https://user-images.githubusercontent.com/33456094/78220162-49917100-74c1-11ea-82aa-c36e99064668.png)

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-04-02 at 09 04 38](https://user-images.githubusercontent.com/33456094/78220164-4b5b3480-74c1-11ea-93c8-80a0cc2c8e7d.png)

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-04-02 at 09 04 53](https://user-images.githubusercontent.com/33456094/78220170-4c8c6180-74c1-11ea-815d-3979e21b201e.png)

</details>

<details>
<summary>App store icon</summary>

![Icon](https://user-images.githubusercontent.com/33456094/78220973-cb35ce80-74c2-11ea-9df1-d85e749b789c.png)

</details>

**Comment by britannio** [comment]
We'd prefer these without the debug banner right?

**Comment by Moosphan** [comment]
@britannio OK, I will hide it. And the latest version looks a bit off from the design.

**Comment by Techno-Disaster** [comment]
<details>
<summary>Redmi K20 Pro, all pages screenshots</summary>
<br>

![Screenshot_20200403-010321_COVID-19](https://user-images.githubusercontent.com/52817235/78294612-48efed80-7548-11ea-83f4-241750c9f8e4.png)
![Screenshot_20200403-010326_COVID-19](https://user-images.githubusercontent.com/52817235/78294696-6de46080-7548-11ea-961f-5a791993d88c.png)
![Screenshot_20200403-010330_COVID-19](https://user-images.githubusercontent.com/52817235/78294701-7046ba80-7548-11ea-805f-a6b1062d09eb.png)
![Screenshot_20200403-010345_COVID-19](https://user-images.githubusercontent.com/52817235/78294705-7177e780-7548-11ea-86a4-cec594c127d8.png)
![Screenshot_20200403-010351_COVID-19](https://user-images.githubusercontent.com/52817235/78294711-7472d800-7548-11ea-80e0-835d2b21237b.png)
![Screenshot_20200403-010358_COVID-19](https://user-images.githubusercontent.com/52817235/78294719-776dc880-7548-11ea-9b56-17c189b79bfd.png)
![Screenshot_20200403-010412_COVID-19](https://user-images.githubusercontent.com/52817235/78294723-79d02280-7548-11ea-89a3-72c38c875361.png)
![Screenshot_20200403-010419_COVID-19](https://user-images.githubusercontent.com/52817235/78294730-7ccb1300-7548-11ea-8be8-bf510bfa56f7.png)
![Screenshot_20200403-010447_COVID-19](https://user-images.githubusercontent.com/52817235/78294735-7dfc4000-7548-11ea-8af9-f1570d4b99c0.png)
![Screenshot_20200403-010457_COVID-19](https://user-images.githubusercontent.com/52817235/78294745-82285d80-7548-11ea-98ec-3946cbbf31d2.png)
![Screenshot_20200403-010505_COVID-19](https://user-images.githubusercontent.com/52817235/78294752-85bbe480-7548-11ea-86fe-8d4f2dab38b5.png)
![Screenshot_20200403-010519_COVID-19](https://user-images.githubusercontent.com/52817235/78294762-894f6b80-7548-11ea-94bb-55ad8c91a4ac.png)
![Screenshot_20200403-010532_COVID-19](https://user-images.githubusercontent.com/52817235/78294771-8c4a5c00-7548-11ea-9603-7be9bbbcf2ba.png)
![Screenshot_20200403-010831_COVID-19](https://user-images.githubusercontent.com/52817235/78294776-8d7b8900-7548-11ea-8213-fc0b1bfd2efd.png)

</details>

**Comment by augustinreille** [comment]
I would suggest, for later releases, to use [fastlane tools](https://fastlane.tools/) as [snapshot](https://docs.fastlane.tools/getting-started/ios/screenshots/) for ios and [screengrab](https://docs.fastlane.tools/getting-started/android/screenshots/) in order to automatically upload screenshots with fastlane (#318).

**Comment by brunobowden** [comment]
@augustinreille - we're all keen to move to Fastlane, just need a developer to step and implement the support for it

@hspinks - since you have experience with this, please can you create the updated screenshots, thank you. My hope is that we can use Fastlane for the next release and in particular localization.

**Comment by advayDev1** [comment]
Kristina is working on marketing screenshots, Hunter is backup for non-marketing screenshots if needed.

**Comment by crazybob** [comment]
@jessicahladd Let's come up with some marketing messages for the screenshots here: https://docs.google.com/document/d/1CjzP_Va0s6KtdTT_PYe4uu9QWsEFBiCu1xVqYKDIFco/edit

Then we can ask Kristina or another designer to turn them into screenshots.

Check out Present's screenshots for an example of what we have in mind: https://apps.apple.com/us/app/present/id1241060084

**Comment by brunobowden** [comment]
Marketing screenshots have been uploaded and they look nice.
