### ISSUE TITLE
Deployment: update repo with changes from WHO

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#730]
WHO has made several changes (some through XCode, some involving Android release configs) since they have deployed. We need to update the repo (or the release branch) with these changes so that we have these changes in source control.

Also, make a "cut" script that swaps in dev with prod config.

**Comment by hspinks** [comment]
@epicfaace thanks for noting this - can you document those changes either here or in Slack?

**Comment by epicfaace** [comment]
I was sent a patch file -- I will apply them to a PR and link it to this

**Comment by brunobowden** [comment]
@epicfaace - please work with @patniemeyer to get this merged in. @patniemeyer will do the build and upload to App Store.

**Comment by hspinks** [comment]
Removing this from the `v1.0` milestone as our current process seems to be sufficient to get this to the app stores (see https://github.com/WorldHealthOrganization/app/pull/745#issuecomment-609111615)

**Comment by advayDev1** [comment]
We now have a full build in the private repo, which from here on it we will use the app-build repo.
