### ISSUE TITLE
Add automated tests to server

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#731]
The server code doesn't have any tests currently.

Unlike the frontend, the server's endpoints has more stable requirements for functionality, so it would be good to add automated tests to prevent regressions in functionality.

**Comment by ayushr2** [comment]
I am looking into this!

**Comment by ayushr2** [comment]
I will hold off from making a PR until v1 is launched since this is non-urgent. I made a local PR in my forked repo for the time being.
