### ISSUE TITLE
"Get Started" WHO Logo includes non-localizable text and needs transparency...

### ISSUE THREAD

**Issue by patniemeyer** [WorldHealthOrganization/app#739]
This page needs to be updated to use localizable text and the graphic-only `mark` image asset.

**Comment by patniemeyer** [comment]
Dan Leuck @dleuck is working on this.  (I'm unable to assign or tag him here)

**Comment by dleuck** [comment]
It's done. I posted the svg files to the design channel. Let me know if they should be posted or checked in elsewhere.

**Comment by hspinks** [comment]
Per discussion on Slack, moving this to `vNext` and removing `P0` - we will re-prioritize after v1 launch

**Comment by advayDev1** [comment]
Uncertain what this task is about.  I think we eliminated this screen from the app.

If not, please re-open.
