### ISSUE TITLE
Localize iOS permission request screens

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#743]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

See https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html#//apple_ref/doc/uid/TP40009254-102276

**Comment by hspinks** [comment]
@sapte91 bringing this to your attention. These strings are baked into the iOS plist files and displayed as part of the system permissions requests justifying why we are requesting the permission. We don't have a locked English language string for this, but when we do, we'll need to keep this on the `l10n` radar. Also, on the `i18n` front, we'll need to implement the recommended way to localize the strings in those plist files (see link in original issue comment)

**Comment by epicfaace** [comment]
Here's a guide on where to store localized strings for this: https://medium.com/@guerrix/info-plist-localization-ad5daaea732a
