### ISSUE TITLE
Onboarding screens - design review feedback

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#748]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Includes:
* [ ] Center text vertically in buttons
* [ ] Make font weight for text in buttons semibold (font weight `600`)
* [ ] Make button background color `#008DC9`
* [ ] Buttons should align vertically between all onboarding screens
* [ ] Make screen background color white (`#FFF`) for all screens
* [ ] Use logo image asset with transparent background **needs asset**
* [ ] Tighten letter spacing in heading text (approximately `-0.1em` from where it is now)
* [ ] Increase line height of subheading text (should be 16pt font / 22pt line height)
* [ ] Implement updated designs for Notifications and Location permissions pages (see Figma & attached screenshots)

Notifications:
![Interim  Onboarding Notification Permissions](https://user-images.githubusercontent.com/1484366/78091795-c964f180-7382-11ea-98c7-0c8b413ce4bf.png)

Location:
![Interim  Onboarding Location Permissions](https://user-images.githubusercontent.com/1484366/78091791-c538d400-7382-11ea-8741-3fcd33deb17e.png)

**Comment by britannio** [comment]
Note to self
- [ ]  Center text vertically in buttons
- [ ]  Make font weight for text in buttons semibold (font weight `600`)
- [ ]  Make button background color `#008DC9`
- [ ]  Buttons should align vertically between all onboarding screens
- [ ]  Make screen background color white (`#FFF`) for all screens
- [ ]  Use logo image asset with transparent background **needs asset**
- [ ]  Tighten letter spacing in heading text (approximately `-0.1em` from where it is now)
- [ ]  Increase line height of subheading text (should be 16pt font / 22pt line height)
- [ ]  Implement updated designs for Notifications and Location permissions pages (see Figma & attached screenshots)
