### ISSUE TITLE
Global header - design review feedback

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#749]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Includes:
* [ ] Main title font should be SF Pro Display (hopefully this is the default system font on iOS - comment here if not)
* [ ] Main title font color should be `#1A458E`, font weight black (`900`)
* [ ] Decrease letter spacing on on main title font (decrease by approximately `0.1em`)
* [ ] Subheader font color should be `#3C4245`, font size `18pt`, font weight bold (`700`)

**Comment by jamesblasco** [comment]
I would like to work on this. Let me know if I can assign this task

**Comment by britannio** [comment]
https://flutter.dev/docs/resources/platform-adaptations#typography  SF is the default on IOS, not sure if SF and SF Pro Display are the same though.

**Comment by jamesblasco** [comment]
Hey, is this letter spacing okey or too much?
<img width="293" alt="Captura de pantalla 2020-04-01 a las 19 32 21" src="https://user-images.githubusercontent.com/19904063/78167895-845ac100-744f-11ea-8866-5561cc405204.png">

**Comment by jamesblasco** [comment]
@britannio I uploaded what I already have before I realised it was assigned to you. Sorry about that

**Comment by britannio** [comment]
> @britannio I uploaded what I already have before I realised it was assigned to you. Sorry about that
np

**Comment by hspinks** [comment]
@jamesblasco all good, it's yours now 😄
