### ISSUE TITLE
Visual diff testing framework

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#75]
Each PR would generate screenshots of each main screen, and show the diffs (if any) to master.
Each difference can be approved in the PR.

I've used https://percy.io/ for this (for web apps) - any other suggestions?

**Comment by epicfaace** [comment]
Since we're using testing with jest, we could also write tests that take screenshots and then save them as a snapshot, through https://github.com/americanexpress/jest-image-snapshot.

**Comment by advayDev1** [comment]
Please investigate or close @pwicherski
