### ISSUE TITLE
Update card text style on Protect Yourself page

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#753]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Text in cards on the Protect Yourself page should be:
* [ ] Color `#3C4245`
* [ ] Font size `16pt`
* [ ] Line height `22pt`

**Comment by brunobowden** [comment]
punt for v1

**Comment by advayDev1** [comment]
Outdated design review feedback.
