### ISSUE TITLE
When a question is expanded on the Questions page, update title style

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#755]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

When a ExpansionTile is expanded, update the style of the title to reflect that it's expanded. In the "expanded" state, the title and close icon should change color to `#1A458E`

**Comment by brunobowden** [comment]
punt for v1

**Comment by advayDev1** [comment]
Not part of the most recent design review
