### ISSUE TITLE
Update question-answer accordion styles

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#756]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

In `questions_index.dart` for both the Questions and the Get the Facts (fka Mythbusters) pages:
* [ ] ExpansionTile titles should be SF Pro Text font, Bold font weight (`700`), and color `#3C4245`
* [ ] Body text (children of the ExpansionTiles) should be SF Pro Text font, Regular font weight (`400`), and color `#3C4245`
* [ ] Body text style should change on HTML elements - e.g. the `<b>` tag should make text bolder
* [ ] Increase the padding on each ExpansionTile row

**Comment by jamesblasco** [comment]
@hspinks SF font is copyrighted to be used only on the iOS platform. For Android would you suggest to use Roboto?

**Comment by jamesblasco** [comment]
I forgot to link the issue. This is issue is fixed in [#802](https://github.com/WorldHealthOrganization/app/pull/802)

**Comment by hspinks** [comment]
Thanks @jamesblasco! Closing per #802
