### ISSUE TITLE
Travel Advice screen - design review feedback

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#757]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Includes:
* [ ] Make all text on the page font size `16pt` and line height `22pt`
* [ ] Format the red section to match design with multiple paragraphs and increased padding (see screenshot)

![News   Press](https://user-images.githubusercontent.com/1484366/78094786-3e87f500-738a-11ea-9f5c-168bae9db8c4.png)

**Comment by hspinks** [comment]
Dropping this to a `P1` since #808 addresses the most drastic problem on the page

**Comment by brunobowden** [comment]
punt to after v1

**Comment by advayDev1** [comment]
Outdated design review feedback.
