### ISSUE TITLE
News & Press screen - design review feedback

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#758]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Includes:
* [ ] Spacing between the icon and text should be `12px`
* [ ] Chevron color should be `#D1D5DC`
* [ ] Dividers between rows should extend to the right of the screen, be slightly darker, and be centered vertically between rows

**Comment by brunobowden** [comment]
punt to after v1

**Comment by advayDev1** [comment]
Outdated design review feedback.
