### ISSUE TITLE
Change Questions screen title to Questions & Answers

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#761]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Per feedback. Will this text fit in the header bar?

**Comment by theswerd** [comment]
@hspinks I have a PR out to update the questions page ui (#760), should I add this on to it?

**Comment by hspinks** [comment]
@theswerd nice! Yeah, go ahead and include it there (assuming the title fits)

**Comment by hspinks** [comment]
(Also as an explanation for removing `string-change` - let's please put that label only on the PRs that make the string changes to make it easier on the translation team to track down exactly where the strings are changed)
