### ISSUE TITLE
Tap status bar to autoscroll to the top of the page

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#767]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Bug bash suggestion:

> On any given screen with long content, the expected interaction pattern of tapping the status bar to go to the top and the view doesn't work. This is a nice efficiency for users to get back to the "Back" arrow for self-location and navigation.

**Comment by jamesblasco** [comment]
This feature is not yet available for iOS13 on the stable branch of Flutter. It is now on master [#16820](https://github.com/flutter/engine/pull/) and it will take some months before being available. 

Maybe this feature should be postponed for when it is fully supported by flutter.

(Notice that this tap status bar behaviour is only used on iOS)

**Comment by britannio** [comment]
I'm an Android user so I presume this is an IOS pattern.
>This is a nice efficiency for users to get back to the "Back" arrow for self-location and navigation

On IOS you can swipe from the side to go back.

**Comment by advayDev1** [comment]
Is this an interaction you want to support?

**Comment by davidkaneda** [comment]
This is the default pattern for iOS, so obviously it would be nice, but assuming it's not worth it if we have to go off flutter master or do something hacky.

**Comment by jamesblasco** [comment]
It is already on 1.17.0-dev.3.1, and stable 1.17 is expected to be released this month, I think it is worth the wait. Also this problems is only on iOS 13 and it should work correctly in previous versions

**Comment by jamesblasco** [comment]
With the new Flutter version released yesterday this should be fixed
