### ISSUE TITLE
Analytics: send events for all buttons pressed and pages viewed (if analytics enabled)

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#769]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Currently, we only send events for tiles pressed on the Main screen. We want to capture all different pages viewed and buttons pressed

**Comment by Samaritan1011001** [comment]
I observed the following places to be missing to collect analytics:

- On load of all pages like you mentioned (However, one question I have is, isn't collecting on press of a tile equivalent to the user viewing the page it routes to?) 

- Travel advice page has a link to a webpage 

- News and Press tile needs collection on tap of the tile and 4 links to webpages in its screen

- Settings tile also needs a collection on tap

Just putting these here so anyone working on this can refer. If no one is assigned, I can take it up.

**Comment by guillermo-varela** [comment]
Hi @hspinks and @Samaritan1011001, I hope this one helps: https://github.com/WorldHealthOrganization/app/pull/968 🙂
