### ISSUE TITLE
If you skip notifications or Locations, you keep getting onboarding over and over

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#771]

**Comment by dna-f** [comment]
Hi @advayDev1 , that's probably due to the way the onboarding is pushed (during the home page initState)
I add a few comments on this other issue, if it can help
https://github.com/WorldHealthOrganization/app/issues/776

**Comment by dna-f** [comment]
Sorry, I misunderstood the problem

**Comment by hspinks** [comment]
Assigning to @advayDev1 to see if we can consistently reproduce

**Comment by stevan-milovanovic** [comment]
I tested this use case with code from current master branch [app version 0.1.1(2)] and I could not reproduce described behaviour.
