### ISSUE TITLE
Localization in app isn't working

### ISSUE THREAD

**Issue by sapte91** [WorldHealthOrganization/app#772]
Pat caught an issue where our languages aren't listed in the xcode project. 

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [ X] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ X] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by patniemeyer** [comment]
This specific issue was fixed in PR #773.  However we need to track the languages we want to support and keep that file in sync.  (That file limits what is available to the app).
