### ISSUE TITLE
Localization is unstable on app launch...

### ISSUE THREAD

**Issue by patniemeyer** [WorldHealthOrganization/app#776]
There seems to be a bug in flutter localization on iOS where the app launches with the wrong language code briefly and then immediately redraws with the correct one. e.g. if you log the language from the locale in our home page’s build method it initially starts with a (seemingly) random one and then immediately switches to the desired one. I have looked briefly to see if I can find this issue reported but am not finding it. I am hoping it might be fixed in a later (beyond current ‘stable’) build of Flutter or that we are making some mistake in configuration. If anyone has time to research this issue we would appreciate any info. (Please note that localization is not active in the current build but we have a PR in that fixes it).

If I add this: 
```
Locale locale = Localizations.localeOf(context);
print("language = ${locale.languageCode}");
```
to the home page build method  I see this on startup:
```
flutter: language = ru
flutter: language = en
flutter: language = en
```
Additionally our onboarding screens *capture* this incorrect language because the seem to be pushed during this window and don’t get rebuilt.

I see this in the simulator and on device.  I’m not sure if you have to change your language once to see it.

We are using the standard flutter_localizations package e.g. https://flutter.dev/docs/development/accessibility-and-localization/internationalization with the localizy plugin that generates a static API from the keys. (edited)

**Comment by dna-f** [comment]
I usually wrap the MaterialApp inside a StreamBuilder that receives the locale from a business logic bloc that evaluates the last user choice or the device locale.
The MaterialApp is then built using it:
locale: locale != null ? Locale(locale, '') : null,
      supportedLocales: [
        const Locale('en', ''),
        const Locale('it', ''),
        // ... other locales the app supports
      ],

**Comment by dna-f** [comment]
The on boarding screen is pushed during the initState of the home screen with the call to _pushOnboardingIfNeeded
We could add a root screen that switches between the onboarding content (if not already done) and the home content

**Comment by dna-f** [comment]
I added a bootstrap setup for the app that takes care of locale (and potentially more)
https://github.com/dna-f/app/tree/handle-locale-at-startup
Added a few dependencies

**Comment by britannio** [comment]
> We could add a root screen that switches between

https://github.com/WorldHealthOrganization/app/pull/794

**Comment by dna-f** [comment]
Yes @britannio! I agree that #794 could be the right solution for the onboarding screen issue.
Even my branch solves implicitly the same issue, as it set the locale on the material app before navigating to the root screen (home)

**Comment by patniemeyer** [comment]
@advayDev1 @theswerd @hspinks 
Update: I have not found a solution to this problem but -

1) While the language switch is definitely happening it does not actually seem to be tripping up our onboarding pages right now.  I was confused by us not having localized them yet 🤦‍♂ .  However I'm concerned that this is the luck of timing (our startup takes a while) and we may see it on other devices later.  I am tempted to add a short delay before pushing the onboarding screens, but this would look worse.

2) Note that there is an updated version of the intl_utils that the plugin uses and it has changed the ordering of the languages such that English seems to appear first. (I don't know if that was intentional or random).  The effect of this is that in the worst (broken) case a user would get English onboarding and the rest of the app localized.  Just FYI for testing.

**Comment by dna-f** [comment]
Hi @patniemeyer, I've made a bit of refactoring on app bootstrap on my branch, to handle locale at startup and other future services setup, like firebase_messaging, dynamic_links, cache and so on.
Locale is now passed down to the MaterialApp before building it.
Do you think that this could be useful?

**Comment by dleuck** [comment]
I ran into this issue while working on localized SVGs. I ended up deferring a check on locale until the first call for a localized resource.

**Comment by patniemeyer** [comment]
@dna-f It's hard for me to see what this does because you have introduced a lot of restructuring but it looks like the gist of it is that you are using the `flutter_device_locale` package to get the locale and pass it to the MaterialApp instead of relying on the BuildContext to provide it.  Do you have reason to believe that the technique that that package uses is more stable than what Flutter is doing natively?  Because the problem is timing related it is hard to know if that package addresses it without doing a more discrete test but I am interested.  Would you have time to do a test and introduce just the `flutter_device_locale` package enough to log the reported locale in the build method alongside my example above?  That would tell us if it is really different under the same timing.  (I only see the issue on a cold start).  And if so it would be only a few line change to drop in... Thanks.

**Comment by patniemeyer** [comment]
> I ran into this issue while working on localized SVGs. I ended up deferring a check on locale until the first call for a localized resource.

Yah, the problem that we have is that we want to push the onboarding screens immediately on launch and so there is a race condition with the locale info settling.

**Comment by patniemeyer** [comment]
I'm going to remove this as a P0 blocker for the moment.  Planning to leave it alone until we get an actual report of the problem or a real fix.  If we get a report we can add the short delay.

**Comment by dna-f** [comment]
> Would you have time to do a test and introduce just the `flutter_device_locale` package enough to log the reported locale in the build method alongside my example above?

Certainly! 
But we should do that before calling the runApp method, because we need to await the Future.
What about the language choose? 
When the user will change the language, we will need to rebuild the app widget. That's why I added a Bloc and a StreamBuilder around the Material app: to allow setting a new locale from any other screen and rebuild the whole app. Should we keep it? 
Will we save the user locale choice (from the languages screen) inside the shared pref and recover it from there on the next run?

**Comment by dna-f** [comment]
Done on this new branch. Very basic fix ;)
https://github.com/dna-f/app/tree/fix-locale-startup
Tested on: 
• Android device [device it] -> [ru] (the first one within the supported languages)
   Home page in 'ru' but onboarding screen in english, because labels like 'legalLandingPageButtonGetStarted' are not translated to ru inside their corresponding arb file.
• iOS simulator [device en] -> [en] ... everything ok

**Comment by jamesblasco** [comment]
hello @patniemeyer, I think I found the current issue that is making this problem. https://github.com/flutter/flutter/issues/39032

Apparently there is a bug in Flutter that on iOS 13 the windows.locale (the mobile native locale) starts null, while on android it returns the correct locale. See https://github.com/flutter/flutter/issues/39032

I tried the workaround commented in the issue and it works:
```dart
// Add this before runApp()
WidgetsFlutterBinding.ensureInitialized();
print(window.locale) //null
while (window.locale == null) {
   await Future.delayed(const Duration(milliseconds: 1));
}
print(window.locale) //en_US
```

It doesn't look to impact the app launch.
When null it starts as ru by default because it is the first language in the supportedLocales of AppLocalizationDelegate. It would be better to put Locale.fromSubtags(languageCode: 'en'), as the first language too.

**Comment by Samaritan1011001** [comment]
@patniemeyer I am not sure of the changing language in IOS problem. But, for the on-boarding screens not changing the language is simply due to the localized key, values being absent in all the translation files meaning they are not translated although the code for it to work exists.

For example the "Get Started" text on the legal landing page has this localization key: `legalLandingPageButtonGetStarted` which is simply not present in any of the language `.arb` files

![image](https://user-images.githubusercontent.com/10944487/78201973-aad12a00-7458-11ea-859c-193576ff61bf.png)


Similarly the translations for the other texts in the onboarding screens are absent too.

**Comment by patniemeyer** [comment]
> hello @patniemeyer, I think I found the current issue that is making this problem. [flutter/flutter#39032](https://github.com/flutter/flutter/issues/39032)
> 
> Apparently there is a bug in Flutter that on iOS 13 the windows.locale (the mobile native locale) starts null, while on android it returns the correct locale. See [flutter/flutter#39032](https://github.com/flutter/flutter/issues/39032)
> 
> I tried the workaround commented in the issue and it works:
> 
> ```dart
> // Add this on main before runApp()
> WidgetsFlutterBinding.ensureInitialized(); //in Who app this is already added
> print(window.locale) //null
> while (window.locale == null) {
>    await Future.delayed(const Duration(milliseconds: 1));
> }
> print(window.locale) //en_US
> ```
> 
> It doesn't look to impact the app launch.
> When Locale is null, it sets as ru by default because it is the first language in the supportedLocales of AppLocalizationDelegate. It would be better to put Locale.fromSubtags(languageCode: 'en'), as the first language too.

@jamesblasco I think this is the best option for now.  I'm not sure if `window.locale` is equivalent to `Platform.locale` but they both seem to be null during this time.  This will cause a blank screen for a short period but seems like the least invasive option until the Flutter people fix this.

**Comment by dna-f** [comment]
@jamesblasco should we add any check to exit the loop in case of something going wrong?
A sort of max delay?

  final waitMax = const Duration(seconds: 1);
  final stopwatch = Stopwatch()..start();

  print(window.locale); //null
  while (window.locale == null) {
    await Future.delayed(const Duration(milliseconds: 1));
    final elapsed = stopwatch.elapsed;
    if(elapsed > waitMax) {
      break;
    }
  }
  stopwatch.stop();
  print(window.locale); //en_US

**Comment by dnfield** [comment]
I have a patch for this in Flutter, but it will likely take a while to roll through to a usable channel for this app.  For now, this can be worked around by using a platform channel when on iOS to request the current locale from the device, as explained here: https://flutter.dev/docs/development/platform-integration/platform-channels#step-4-add-an-ios-platform-specific-implementation

Alternatively, you could draw a splash screen or animation until the locale initializes (and you can check that properly by adding an observer to the WidgetsBinding that overrides `didChangeLocales`), e.g. something like

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (WidgetsBinding.instance.window.locale == null) {
    Completer<Locale> completer = Completer<Locale>();
    WidgetsBinding.instance.addObserver(LocaleObserver(completer));
    // completer.future is now a `Future` that will complete when the locale is available.
  }
}

class LocaleObserver extends WidgetsBindingObserver {
  LocaleObserver(this.completer);

  final Completer<Locale> completer;

  @override
  void didChangeLocale(List<Locale> locale) {
    WidgetsBinding.instance.removeObserver(this);
    completer.complete(WidgetsBinding.instance.window.locale);
  }
}

**Comment by dnfield** [comment]
Actually, I have a better idea on how to fix this.  Going to test it locally and will open a PR if it's working.

**Comment by dnfield** [comment]
We can just send the message on the same channel Flutter uses for this earlier on in the application lifecycle.  Flutter will end up sending all locales available later - the logic can be expanded to do that as well, but this will at least get us the primary locale on startup.
