### ISSUE TITLE
About app page and other symlink features are broken when developing on windows.

### ISSUE THREAD

**Issue by Samaritan1011001** [WorldHealthOrganization/app#779]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

There is an error message that shows up in the about screen. 

Error message: 

`type 'String' is not a subtype of type 'int' of 'index'`

Screenshot:

![Screenshot_1585721462](https://user-images.githubusercontent.com/10944487/78104982-bd465780-73b5-11ea-8f9e-317a23c357a4.png)

Steps to reproduce:

- Starting fresh (clone repo)

- cd app/client/flutter

- flutter run

The problem seems to be at line 76  in `about_page.dart` where the fetched content is returning a path instead of the actual credit.yaml file

Replace contents of `assets/credits.yaml` with the contents of `content/credits.yaml` resolves the problem

**Comment by mit-mit** [comment]
I cannot repro this on current master:

![Screenshot_1585728672](https://user-images.githubusercontent.com/13644170/78114200-2bfcd280-7401-11ea-96cc-994ce98d818d.png)

**Comment by britannio** [comment]
It's broken for me too but somehow it works for others. I'm on Windows testing on an Android 10 device. What fixes it for is moving the credits.yaml file into the assets folder and updating the reference where the file is parsed.

The error is caused because it's reading `assets/credits.yaml` which contains this:
```
../../../content/credits.yaml
```
and instead of redirecting to the `credits.yaml` file in `/content` it's trying to parse that string directly .

**Comment by mit-mit** [comment]
Oh, good catch @britannio. Symlinks work very poorly on Windows, and should be avoided. I created a PR.

**Comment by mit-mit** [comment]
@britannio @Samaritan1011001 if you have access to a Windows machine would you mind helping with a quick test of https://github.com/WorldHealthOrganization/app/pull/791 on Windows? Just:

```
git clone --single --branch aboutcredits https://github.com/mit-mit/app.git
cd app/client/flutter/
flutter run
```

and verify that this resolves the issue on Windows?

**Comment by britannio** [comment]
@mit-mit I'm on it

**Comment by britannio** [comment]
@mit-mit I can confirm that your fix works on Windows.

**Comment by advayDev1** [comment]
I don't think we should not use symlinks b/c windows doesn't support them.  Our server also uses symlinks for the content and we should not duplicate them/

If someone wants to solve this by for example making copies of the files for all symlinks during thhe build process, I'm cool with that.

**Comment by mit-mit** [comment]
I already solved this in #791, but the PR wasn't taken

**Comment by matthewblain** [comment]
FYI while the underlying Flutter issue is being worked on, you can develop to a good extent on Windows:
* Make sure symlinks are enabled in the OS and Git. 
* Workaround to build: Comment out the - assets/ line in client/pubspec.yaml.

In this configuration, the builds etc will work, as will the app, but the credits will be blank.

**Comment by brunobowden** [comment]
@matthewblain - please document this in client/README.md so other Windows
developers know what to do.
