### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by viviancromwell** [WorldHealthOrganization/app#79]
I’m sure you all are already thinking of this on the design/product side but some feedback from my parents: the most basic parts of our app would ideally be usable to someone who can’t read one of our speced languages (poor eyesight included), using large graphics that, on a standalone basis, represent all of the needed prophylactic steps.   The original mocks have something like that, with graphics for covering coughs and washing hands on each start of the app, before you get to the more complex features. (edited) 

This is one of the few issues raised around accessibility. While we may not be able to address all in the initial review. we should definitely consider

**Comment by advayDev1** [comment]
Copying in some text from #78 

> Each time the app starts, before you get to the more complex parts, the app would remind the user with graphics for covering coughs, washing hands, etc. on each start of the app, before you get to the more complex features. For those persons with more bandwidth, an animated version could be used as well.

For the ability to reach the greatest userbase, IMO pictograms are absolutely key (and I understand your point that showing it everytime is possibly not the right thing to do, but on first launch seems to be the most important info we can impart to the world.)

**Comment by hspinks** [comment]
Closing this issue in favor of tickets addressing specific accessibility concerns
