### ISSUE TITLE
Change HTML keys in l10n files to include HTML in the name

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#809]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

E.g. `travelAdviceContainerText` -> `travelAdviceContainerHtml` once #808 is merged

**Comment by advayDev1** [comment]
@patniemeyer Can we close this given your refactor of dynamic content?  Does every field that could have unescaped html in it now labeled with an html suffix?

**Comment by patniemeyer** [comment]
Yes, every key in the dynamic content bundles that can contain HTML is named with the HTML suffix. (Including "protect yourself", even though it is is not yet using html in that field).
