### ISSUE TITLE
CI - require branches to be up to date before merging

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#820]
Doing this would not only ensure that branches merged into master would pass the build, but it would also create a button on all PRs that allows one to merge master into that branch -- which is more convenient than needing to do so from the command line.

![image](https://user-images.githubusercontent.com/1689183/78190224-9df50c00-7441-11ea-90c8-e2bcfc43af16.png)

This would involve modifying branch protection rules as follows:

![image](https://user-images.githubusercontent.com/1689183/78190205-93d30d80-7441-11ea-8bd3-39ce95c654d8.png)

**Comment by SamMousa** [comment]
Does that button appear for prs that don't have "allow maintainers to edit" enabled?

**Comment by epicfaace** [comment]
> Does that button appear for prs that don't have "allow maintainers to edit" enabled?

I don't think so, because maintainers wouldn't be able to edit those branches.

**Comment by SamMousa** [comment]
Then we should tell people to enable that when creating PRs, maybe even use the labeler to mark PRs that don't have it as faulty. Enabling the linear history before enforcing editable PRs can significantly hamper development.

**Comment by epicfaace** [comment]
> Then we should tell people to enable that when creating PRs, maybe even use the labeler to mark PRs that don't have it as faulty.

Right -- we should probably add this to the PR template. I don't think this would be a huge issue, though, given that the setting to "allow maintainers to edit" is enabled by default.

**Comment by SamMousa** [comment]
@advayDev1 @hspinks @patniemeyer you guys have opinions on this?

I think it'll be a bit too strict for now.

**Comment by advayDev1** [comment]
I agree this is not needed at this time.

**Comment by advayDev1** [comment]
Closing for now.  Let's reopen later as needed.
