### ISSUE TITLE
Use fontSize instead of textScaleFactor

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#822]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Using `textScaleFactor` seems to blow up the accessibility settings on the phone. Use font sizes instead where possible, and/or factor in [`textScaleFactorOf`](https://api.flutter.dev/flutter/widgets/MediaQuery/textScaleFactorOf.html) when setting our own scale factor. Our text sizing should take into account the accessibility settings on the user's phone. This issue applies to all screens / all text, where possible to fix.

**Comment by brunobowden** [comment]
@avkvirtru @tomgilder - PTAL and see if #826 is the right fix for this. Also, please consider if this is a fix we should prioritize for v1. Looking forward to getting other accessibility fixes in for the future

**Comment by advayDev1** [comment]
We still need to use auto_text_size

**Comment by brunobowden** [comment]
auto_text_size makes a lot more sense long term

**Comment by britannio** [comment]
auto_text_size is great for preventing overflows although ideally, UI components should scale to fit a range of sizes.

**Comment by advayDev1** [comment]
Let's get @britannio 's PR in.  We will separately do auto-size of tiles in overflow bugs.

**Comment by hspinks** [comment]
> auto_text_size is great for preventing overflows although ideally, UI components should scale to fit a range of sizes.

Agree - I actually think we should limit the use of `auto_text_size` and instead focus on build components that are more responsive to different content and screen sizes. `auto_text_size` could be an easy solve for #651 though

**Comment by avkvirtru** [comment]
@brunobowden @tomgilder I found 4 new issues with text resizing in `v0.5.0`:

1. Screen names don't resize at larger fonts (~7 MB gif):
![Screen-names-fonts-dont-resize-Screen-Recording-2020-04-06-at-11 59 39-AM](https://user-images.githubusercontent.com/44370126/78596297-5fc06980-7800-11ea-8a0f-34c753ba6a30.gif)

2. News subheadings don't wrap when fonts large enough ![News subheadings don't wrap when large enough - Simulator Screen Shot - iPhone 8 - 2020-04-06 at 12 00 55](https://user-images.githubusercontent.com/44370126/78596328-6ea71c00-7800-11ea-923d-9408083d8e0e.png)

3. About links don't resize <img width="1254" alt="About links text size - Screen Shot 2020-04-06 at 12 01 54 PM" src="https://user-images.githubusercontent.com/44370126/78596354-7b2b7480-7800-11ea-8e11-ca9d998c373d.png">

4. Travel Advice warning ignores font size entirely ![Travel Advice warning ignores font size - Simulator Screen Shot - iPhone 8 - 2020-04-06 at 11 46 52](https://user-images.githubusercontent.com/44370126/78596383-8a122700-7800-11ea-86b1-badb339ad8ba.png)

I've appended all of these to the running iOS accessibility audit as well as rows 50-53: https://docs.google.com/spreadsheets/d/1rSoKi-ggkeMlxIftM2D_AABFafA5cBmuJRae2ZDYUsE/edit#gid=0
