### ISSUE TITLE
Set iOS system permission dialog explanation text

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#824]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

This [looks like](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/requesting-permission/) it's just for the Location permission, not push notifications. I propose:

> Your location is used to deliver you the most relevant information and push notifications to your area

This will need to be localized per #743

**Comment by stevan-milovanovic** [comment]
I can help with this issue

**Comment by brunobowden** [comment]
Closed by #845
