### ISSUE TITLE
Enable French language for users defaulting to French language outside of France

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#828]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

#816 adds `fr_FR`, which I believe only will load for French users in France. Let's enable a general `fr` like we do for `en_US`/`en`

**Comment by kassim** [comment]
So I just tested on Android 6 (API 23) with fr_CA as my device setting. According to Android's own documentation it shouldn't resolve to fr_FR on versions before Android 7 (see https://developer.android.com/guide/topics/resources/multilingual-support) and yet, it does. 


I just checked in the Flutter code and it does this itself - see basicLocaleListResolution https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/app.dart#L1122

**Comment by hspinks** [comment]
@kassim thanks for the info here. I think we may still want a language symlink to determine which version of the language is the "default" version? But open to other thoughts on this, too

**Comment by dhruvilp** [comment]
Just wondering, isn't #654 accomplish this? @hspinks

**Comment by kassim** [comment]
ok then, added the symlink (and the necessary generated code from the IDE plugin) in the PR ^

**Comment by advayDev1** [comment]
So is the title of this bug a problem?

**Comment by kassim** [comment]
No. The problem described by the title is not actually present.

The linked PR implements explicitly stating the correct fallback locale.
