### ISSUE TITLE
Clean up final small visual/content issues found in last triage

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#829]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Batching the following changes:
* [ ] Change "Coronavirus" to "COVID-19" on the Onboarding - Notifications screen
* [ ] Tile title font size should match between Latest Numbers, Questions & Answers, Travel Advice, and News & Press homepage tiles (font size ~80% of titles on Protect Yourself and Get the Facts tiles)
* [ ] Header subtitle on the main screen should read "Information and Tools" instead of "Virus response and tools"
* [ ] Increase the font size on the "Donate Here" button, and capitalize the "Here" word
* [ ] Replace "Coronavirus" with "COVID-19" in the subtitle on the "Get the Facts"
* [ ] Increase font size and line height on the text with the red background on the Travel Advice page

**Comment by devamhdz** [comment]
can i help with this issue?

**Comment by harchani-ritik** [comment]
@hspinks  "Increase font size and line height on the text with the red background on the Travel Advice page"? I already have a PR #800 with this change. Should I push the other required changes also in this PR?

**Comment by jamesblasco** [comment]
@hspinks I think changing text issues should be addressed in separated issues as the translation team should take care of that for all languages no?

**Comment by Techno-Disaster** [comment]
@advayDev1 can you assign me this issue, so that i can send the PR?

**Comment by hspinks** [comment]
Closed in #830 and #858
