### ISSUE TITLE
Deployment: don't hard-code version numbers in build.gradle

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#837]
Right now, when we version bump, we also have to bump the values in build.gradle (see https://github.com/WorldHealthOrganization/app/pull/836 for example).

We shouldn't have to do this because build.gradle should read from `local.properties`, which is autogenerated after every flutter run / flutter build.

We should confirm this works and come up with a workflow that allows us to use this.

**Comment by kassim** [comment]
It already works (tested by simply deleting the `if` code blocks). Nothing needs to be changed but the `if` blocks can be deleted to prevent unnecessary updating.
