### ISSUE TITLE
Device specific errors to be tested and validated before app release 

### ISSUE THREAD

**Issue by YashodhaSamarawickrama** [WorldHealthOrganization/app#841]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
Please file specific bugs with specific problems on specific devices.  This is not currently actionable.

cc @pwicherski
