### ISSUE TITLE
YAMLs loaded from Server have missing charset

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#844]
<img width="329" alt="Screen Shot 2020-04-02 at 4 47 28 PM" src="https://user-images.githubusercontent.com/11729521/78310093-b167ac00-7501-11ea-8665-4900197e94e7.png">

**Comment by advayDev1** [comment]
It appears static files from AppEngine are missing response headers which include charset parameter of the Content-Type header field.  Thus they are interpreted as Latin-1 per RFC 2616 by Flutter.  Can you set the charset for static YAML files to be utf-8?

```
cache-control: public, max-age=600
content-type: application/octet-stream
date: Fri, 03 Apr 2020 15:28:19 GMT
etag: "NEGKpQ"
expires: Fri, 03 Apr 2020 15:38:19 GMT
server: Google Frontend
status: 200
```

**Comment by ayushr2** [comment]
I can take a look at this if possible.
