### ISSUE TITLE
Pull request handling

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#85]
I'm going to increase security settings to enforce our code review process.

Settings that I propose as a minimum:
- PRs must be reviewed and have at least 1 approval.
- Adding a commit to a PR will void approvals.
- Checks must pass
- Enforce these requirements for admins too

Questions:
- Should we increase the number of approvals to 2, or would this hamper quick merging?
- Should admins be allowed to merge PRs that don't satisfy these requirements?

Seeing as this will be a monorepo with several subprojects in it, it makes sense to use a `CODEOWNERS` file. https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by hspinks** [comment]
I like the idea of the `CODEOWNERS` file - how do you propose to break it down? `client` vs `server` vs any other of the top-level services we include in this repo?

**Comment by SamMousa** [comment]
Yes seems like a good start

**Comment by hspinks** [comment]
cool - I agree with this proposal. I like the 2 review requirement, but I think we should start with 1 to make sure we're not blocked as we figure out each other's schedules

**Comment by advayDev1** [comment]
how about 2 reviewers, at least one of whom is a committer?

**Comment by advayDev1** [comment]
cc: @crazybob in slack discussion re: process blockers

**Comment by hspinks** [comment]
Decisions made on this: PRs require approval of at least 1 committer, new commits do not void approvals, checks must pass, and these apply to admins too. CODEOWNERS still tbd

**Comment by SamMousa** [comment]
We need another committer in cet then. Otherwise my code can never be committed. I have been going with approval of core contributor as acceptable for me to merge.. Essentially it is the same thing whether they code, I approve and merge. Or I code, they approve and I merge.
