### ISSUE TITLE
Translate app to Sinhalese

### ISSUE THREAD

**Issue by YashodhaSamarawickrama** [WorldHealthOrganization/app#850]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by YashodhaSamarawickrama** [comment]
I'd like to contribute for this issue

**Comment by advayDev1** [comment]
Closing in favor of #908
