### ISSUE TITLE
Web preview onboarding broken due to analytics

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#851]
I can't go past the Location Sharing screen on the Web preview because I get the following error on the console:

```
Uncaught MissingPluginException(No implementation found for method setAnalyticsCollectionEnabled on channel plugins.flutter.io/firebase_analytics)
```

**Comment by britannio** [comment]
https://github.com/FirebaseExtended/flutterfire
No web support for analytics yet. Do we need the web build to stay intact? It's cool but we might bump into similar issues in the future.

**Comment by epicfaace** [comment]
Mainly, it would be nice if we could keep the web build intact so that we can use Netlify's Deploy Previews to quickly preview builds.

**Comment by SamMousa** [comment]
Also this indicates we're not checking the unhappy paths.

**Comment by SamMousa** [comment]
If asking for a permission fails we can and should notify the user and continue as if the answer was no.

**Comment by advayDev1** [comment]
No more web preview; no more bug ;)
