### ISSUE TITLE
Security Policy pointing to Vulnerability Disclosure Program

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#856]
Steps Needed:
1. Start here: https://github.com/WorldHealthOrganization/app/security/policy
2. Prefer users to report all issues within HackerOne VDP (Vulnerability Disclosure Program)
3. Advise them of private repos for collaborating on developing a fix: https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/collaborating-in-a-temporary-private-fork-to-resolve-a-security-vulnerability

**Comment by britannio** [comment]
@advayDev1 @hspinks Should this be P0?

**Comment by rmspeers** [comment]
I would suggest yes to have this before launch.

Per the Slack discussion, please let me know when there is something ready for review, or if you have any questions when creating a draft.

**Comment by cv692001** [comment]
I am new to Contributing can you please help me out that how to solve this issue 👍
