### ISSUE TITLE
ApplicationID

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#86]
Application ID has been set to `int.who.app`.
This breaks the android build:
> Package 'int.who.app' from AndroidManifest.xml is not a valid Java package name as 'int' is a Java keyword.

We need to decide on a different application ID. This also highlights the need for building the actual apps in our CI pipeline.

**Comment by hspinks** [comment]
does WHO have any standards they'd like us to follow on this?

**Comment by advayDev1** [comment]
Whatever we use should be prefixed by a WHO-owned domain name.

**Comment by SamMousa** [comment]
Or we pick a new one and hand it over later..

**Comment by SamMousa** [comment]
What about whoapp.com? It's available and we can change it later as well as hand the domain over.

**Comment by hspinks** [comment]
I like whoapp.com! seems simplest to me

**Comment by SamMousa** [comment]
Will go ahead and get that set up.

**Comment by SamMousa** [comment]
Can always remove / change

**Comment by epicfaace** [comment]
Let's use https://www.who.org/ -- it redirects to who.int, and it's owned by the WHO (do a whois lookup). Let's not do whoapp.com because it could sound like a phishing site.

**Comment by SamMousa** [comment]
But we don't have access to it. I have registered whoapp.org so that we can move forward

**Comment by epicfaace** [comment]
> But we don't have access to it. I have registered whoapp.org so that we can move forward

That seems fine (better than whoapp.com) -- but why does it matter whether we have access to the actual domain?

**Comment by SamMousa** [comment]
For this package name it doesn't, but for preview app it does

**Comment by SamMousa** [comment]
@hspinks please put the app id you thought of here. FYI Our domain is whoapp.org, the application ID needs to have at least 3 parts for android and CANNOT  be changed.

**Comment by kassim** [comment]
`org.whoapp.android` would be the most common pattern for an app ID

**Comment by kassim** [comment]
think this can be closed?

from Slack:
> based on my reading of the email, I’d changed Xcode to int.who.WHOMyHealth and Android to org.who.WHOMyHealth since it looked like that’s what they were expecting (small change on the Android side)
https://who-app.slack.com/archives/C0100FTK5FB/p1585162240053700

**Comment by hspinks** [comment]
Decisions made:
* iOS: `int.who.WHOMyHealth`
* Android: `org.who.WHOMyHealth`
