### ISSUE TITLE
Target kernel_snapshot failed

### ISSUE THREAD

**Issue by RodoQuezada** [WorldHealthOrganization/app#866]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [ x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Hi, guys ! 
   I want to contribute to development, but I have the following problem: 

![image](https://user-images.githubusercontent.com/11665385/78456206-ae42fc00-7678-11ea-827b-c09fd9102d16.png)

Apparently a file could not be found.

**Comment by SamMousa** [comment]
Did you follow the setup guides?

**Comment by RodoQuezada** [comment]
> Did you follow the setup guides?

Hi, Sam! I think I did (the MDs in doc files), but if you can give another, I will be grateful.

**Comment by RodoQuezada** [comment]
Config error.
