### ISSUE TITLE
Hand Washing Animation Finalized

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#871]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Based on WHO feedback, current hand wash animation should be updated.

**Comment by brunobowden** [comment]
@luigi-rosso - please send PR just as soon as you're ready

**Comment by hspinks** [comment]
Reopening based on WHO feedback (will be re-closed when #913 is merged)
