### ISSUE TITLE
Log errors in Analytics

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#876]
Log at least:
- Geocoding errors
- Notification errors
- Failure to parse responses from our own server (corrupt data)

As per analytics best practice, we should not log any variables (like exception text), only a closed set of strings.  This ensures no PII ever gets sent.

**Comment by brunobowden** [comment]
@advayDev1 - this isn't a blocker on release but would be nice to have. I wonder if Crash analytics might be more helpful, i.e. #877

**Comment by britannio** [comment]
Firebase Crashlytics has `recordFlutterError` and `recordError` for recording non-fatal errors.

**Comment by advayDev1** [comment]
Not a blocker

**Comment by britannio** [comment]
https://pub.dev/packages/firebase_lumberdash
