### ISSUE TITLE
Firebase Crashlytics

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#877]
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Firebase Crashlytics offers an integrated framework for accepting crash reports. It also works well with Firebase Test Lab for automated QA: https://firebase.google.com/docs/crashlytics

**Comment by advayDev1** [comment]
https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#manage_crash_insights_data
