### ISSUE TITLE
"Virus response & tools" change

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#882]
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

WHO expressed concern over the word "virus" and some people do not have a good reaction to it. I've asked them to come up with another subtitle that they prefer.

**Comment by brunobowden** [comment]
@britannio - I'll try to do this unless I turn out to be too busy

**Comment by hspinks** [comment]
This was updated to "Information and tools" as of #830 - closing this, feel free to re-open if an updated string is requested

**Comment by britannio** [comment]
It's still "Virus response & tools" in `intl_en_US.arb` and `messages_en.dart` presumably as a result of the former file.

**Comment by hspinks** [comment]
@britannio good catch - since I messed up the review, I opened the PR to make the change 🤦‍♂
