### ISSUE TITLE
“Get the Facts” ending text is cut off: “the spread”

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#884]
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

The “Get the Facts” section has the last words cut off: “the spread”. See screenshot.
Device: iPhone 11 Max Pro
Version: v0.4.0

![IMG_3049](https://user-images.githubusercontent.com/679339/78470212-7b325400-76dc-11ea-92de-63aa04b2474b.PNG)

**Comment by daohoangson** [comment]
[auto_size_text ](https://pub.dev/packages/auto_size_text) can be used to fit this. Assign me and I'll do a PR.

**Comment by britannio** [comment]
Fixing https://github.com/WorldHealthOrganization/app/issues/822 should fix this issue.

**Comment by hspinks** [comment]
Discussed in standup: #822 will partially fix this, but we want a more generalized solution that will work for the 3 main edge cases that cause overflow:
* Smaller screen sizes that are not very wide, causing more text to flow to new lines
* Accessibility options increasing the size of the text
* Localization where translations in other languages result in much longer text

The fix discussed in standup was:
* Use the [`StaggeredTile.fit` option](https://pub.dev/packages/flutter_staggered_grid_view#tiles) for tiles to be variable height based on the size of their internal content
* Use a [`ConstrainedBox`](https://api.flutter.dev/flutter/widgets/ConstrainedBox-class.html) within the tile as a container for all content inside to set the minimum height
  * Minimum height should be the same as the fixed height of the tiles as they are currently (e.g. [`1:0.73`](https://github.com/WorldHealthOrganization/app/pull/698/files#diff-6ac3b48a3508990c0e66b302adaefdc0R50)

@britannio said he already had a fix in progress using this strategy, so I will assign to him
