### ISSUE TITLE
Client-side Caching

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#893]
fill in

**Comment by SamMousa** [comment]
- [ ] Verify `http.get()` respects cache headers.
- [ ] Find transparent solution for caching the POST requests if needed.

**Comment by SamMousa** [comment]
The standard http library does not support caching: https://github.com/dart-lang/http/issues/334.

## Option 1, not my favorite:
There is an alternative http library called dio: https://pub.dev/packages/dio
It comes with a lot of extensions like: https://github.com/hurshi/dio-http-cache for caching http requests.

## Option 2
https://pub.dev/packages/flutter_cache_manager

This is a generic cache layer and we could possibly even use it (in vNext) to replace our  own loading mechanism. Instead we would, on app updates put the bundled content in that cache and not have it expire. Then when we need content we use the cache manager.

I'd prefer using an existing library over rolling our own caching layer.

**Comment by patniemeyer** [comment]
@SamMousa That cache manager seems reasonable but I would suggest that we use it explicitly from our content loader on the network call with an appropriate cache period (e.g. a day) and not change the way we fall back to the local assets, which is already implemented separately.  We should get some feedback on the cache period.  If no one has started this I can take a look.

**Comment by advayDev1** [comment]
Feel free to - and thank you!

**Comment by patniemeyer** [comment]
Working on this now...
