### ISSUE TITLE
Users may fail to get push notifications when internal FCM tokens change

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#899]
We also need to handle the changing of the token over time otherwise users will be stuck without notifications.  https://pub.dev/documentation/firebase_messaging/latest/firebase_messaging/FirebaseMessaging/onTokenRefresh.html

If we aren't already.

_Originally posted by @advayDev1 in https://github.com/WorldHealthOrganization/app/issues/874#issuecomment-609488185_

This is important because [Google's documentation](https://firebase.google.com/docs/cloud-messaging/android/client) says "Because the token could be rotated after initial startup, you are strongly recommended to retrieve the latest updated registration token."

**Comment by brunobowden** [comment]
FYI @crazybob

**Comment by epicfaace** [comment]
It's worth noting that the token u[sually changes only when](https://firebase.google.com/docs/cloud-messaging/android/client#sample-register):

- The app deletes Instance ID
- The app is restored on a new device
- The user uninstalls/reinstall the app
- The user clears app data.

**Comment by cbgrey** [comment]
Thoughts on this approach: 
* Store the FCMToken in user preferences. 
* Call getToken on every launch
* Call WhoService() to update the token only if changed

I can implement that fairly quickly if acceptable. Will also help in the case that there's an error getting a token from ticket #874

**Comment by patniemeyer** [comment]
@epicfaace @cbgrey and I talked about this as part of the fix for #847 and I agree with all of the above.  The absolute simplest thing to do would be to just update the token on each launch.  An easy optimization would be what @cbgrey suggested above - *being careful* to make sure we don't persist the token to preferences until a successful completion of the call to the `WhoService`.

**Comment by hspinks** [comment]
Closed in #914
