### ISSUE TITLE
Continuous preview

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#90]
Things I found while trying to set up a CI pipeline that would create a preview deployment for each PR:

- Publishing to external things like S3 is not possible for PRs, since secrets are not available.
- The app needs to run in the webroot, so we need a wildcard domain to make this work easily.
- Creating a preview app for every PR will always allow anyone to publish something to our host. (Could be used as an attack vector where others could impersonate us if we host this on a domain people trust)
- Publishing the master branch is simple, we can easily push the build anywhere via s3 or SFTP.

**Comment by epicfaace** [comment]
Since it's just a web app, we could use https://www.netlify.com/ to generate deploy previews from PRs?

**Comment by SamMousa** [comment]
I found that as well but have no experience with it. I think it does what we need & more.

**Comment by SamMousa** [comment]
Bob offered to set this up with Firebase.

**Comment by SamMousa** [comment]
@crazybob will set this up.

**Comment by SamMousa** [comment]
Any update on this @crazybob? If not I'll get some cheap hosting and set this up at whoapp-preview.nl or something.

**Comment by crazybob** [comment]
Hi! Aiming to have hosting working today. Not sure what automatic deployment will entail but shouldn’t be too difficult.

**Comment by SamMousa** [comment]
Great; I was also working on this in parallel (since I had to have some place to put the translation management system). 
Currently setting this up at https://preview.whoapp.org; can also point the DNS to you.

The idea is to just have something now and we can either move to a different domain or do a handover to WHO later.

**Comment by crazybob** [comment]
Awesome!

**Comment by epicfaace** [comment]
Given that we have https://preview.whoapp.org deploying automatically from master, would we still want to have deploy previews generated from PRs (this might speed up the process of examining the PR before merging)? We could integrate with https://www.netlify.com/, which I could help with if we decide to do so.

**Comment by epicfaace** [comment]
This is done by Netlify.
