### ISSUE TITLE
Push Notifications - disable push notifications when user changes iOS settings

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#902]
We need to finish up the TODO over here: https://github.com/WorldHealthOrganization/app/blob/1d03b2194f482a3e3e604faa9e10305d65831f3f/client/flutter/lib/main.dart#L101-L106

Here, we should modify the user's opt-in settings when they change their push notification settings through iOS settings.

**Comment by advayDev1** [comment]
cc: @kassim can you fix this in your notifications settigns PR?

**Comment by kassim** [comment]
yeah I can add some kind of fix in

**Comment by cbgrey** [comment]
If others can't get to this I can take it.

**Comment by kassim** [comment]
@cbgrey in my PR #954  I latched onto your logic from #914 to remove the push token from BE when the app starts if it's found that the iOS settings are disabled

`_firebaseMessaging.onIosSettingsRegistered` isn't actually reliable in understanding changes made to the OS setting (e.g. manually disabling)
