### ISSUE TITLE
Add social media icons on the home page above version details

### ISSUE THREAD

**Issue by ramuz108** [WorldHealthOrganization/app#905]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [ ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
 For ease of access to the WHO's social media resources. Why cant we add social media icons on the botton of the home page?. Just y opinion

**Comment by ramuz108** [comment]
any updates on this?

**Comment by brunobowden** [comment]
@ramuz108 - social media links are very sensitive given the association with spreading of misinformation. As an official WHO app, I think this would be unlikely to happen.
