### ISSUE TITLE
Latest numbers displaying the real time data as child elements from the home page itself.    Think it would be helpful like a dashboard.

### ISSUE THREAD

**Issue by ramuz108** [WorldHealthOrganization/app#906]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [ ] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by ramuz108** [comment]
any updates on this?

**Comment by brunobowden** [comment]
Home page now shows latest numbers fading between Global and National stats.
