### ISSUE TITLE
Translation Requests For All Languages

### ISSUE THREAD

**Issue by wiekiang** [WorldHealthOrganization/app#908]
**Please do not create individual issues for request language translation**

We already have a process in place for managing translations. Please do not create lots of issues as they become hard to track. Instead, add a comment here on the language you want and sign up to help with translations if you're able:

[Translation Volunteer Signup](https://docs.google.com/forms/d/e/1FAIpQLSewnYoz4xJWzuPGbbOZscnosmsl1j4BLvBFZLSZEt4inB9S2Q/viewform)

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by brunobowden** [comment]
@sapte91 - once we decide on an order for doing translations, please update this issue so that others can have public visibility in to it

**Comment by wiekiang** [comment]
@sapte91 @brunobowden - I am able and willing to translate this app into the Indonesian language. Please update once it's ready.

**Comment by Nizar-Albahri** [comment]
@sapte91 I'm a native Arabic language speaker, I can provide very accurate translations for the phrases and strings in the app.
