### ISSUE TITLE
"advsed" spelling mistake in "Travel Advice"

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#910]
"Travel Advice" page: "If symptoms occur, travellers are **advsed**...." should be "advised"

@orchardbirds and @jnimis - please check to see if you can find other typos

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by jnimis** [comment]
Found some typos.  I'm happy to make the following changes myself, but not sure exactly how:

in client/flutter/lib/generated/intl/messages_en.dart:
l.120: "travelAdviceContainerText" : ... "underlying healh conditions" should be "health"
l.129:  "travelAdvicePageListItem3Text" : "travellers are advsed" should be "advised"
** these same typos also appear in client/flutter/lib/l10n/intl_en_US.arb (and in client/flutter/lib/generated/l10n.dart)

in client/flutter/lib/generated/intl/messages_en_US.dart:
l.129:  "travelAdvicePageListItem3Text" : "travellers are advsed" should be "advised"
** I think technically, "travellers" is spelled "travelers" in US localization. Just a detail - there are 5 occurrences of "travellers" in this file, which should be localized to US

in client/flutter/assets/content_bundles/mythbusters.en.yaml:
consider including temperature in Fahrenheit when referring to body temperature (in items 2 and 3)
