### ISSUE TITLE
News & Press screen subheadings cut off when font resized for accessibility

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#920]
Accessibility Audit via @avkvirtru 

**Problem:** all subheadings ("Situation Reports", "Rolling Updates", "News Articles", "Press Briefings") are cut off when accessibility font sizing is turned on and fonts are too large (see screenshot).

**Suggested Solve:** text content should line wrap instead of being forced to stay on 1 line

<details>
<summary>Screenshot</summary>

![News subheadings don't wrap when large enough - Simulator Screen Shot - iPhone 8 - 2020-04-06 at 12 00 55](https://user-images.githubusercontent.com/1484366/78615892-8a71e880-7827-11ea-98ba-cf0962dca290.png)
</details>

---
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by avkvirtru** [comment]
@hspinks @advayDev1 you guys are awesome for fixing so quickly! Thank you!

**Comment by hspinks** [comment]
this was all @britannio! shout out to this team for moving fast all around 😄
