### ISSUE TITLE
Use Semantics widget to annotate widget tree for accessibility

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#923]
Accessibility Audit via @avkvirtru 

There are a large number of `Average` severity issues identified in the audit relating to setting traits for UI elements (e.g. the `button` trait for actionable items, `staticText` for static text, etc). Based on Flutter's [Accessibility docs](), it looks like the [`Semantics` widget](https://api.flutter.dev/flutter/widgets/Semantics-class.html) will need to be used as a wrapper widget around the internal widgets.

Will look for some additional feedback from @avkvirtru on this, but the highest priority here is that every actionable item in the app should use the `button` trait (`button == true` in [`SemanticsProperties`](https://api.flutter.dev/flutter/semantics/SemanticsProperties-class.html)) and every link to an external webpage should use the `link` trait (`link == true` in [`SemanticsProperties`](https://api.flutter.dev/flutter/semantics/SemanticsProperties-class.html)).

---
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
@avkvirtru plz update this issue with the impact to users of not doing this (degree of harm)

**Comment by avkvirtru** [comment]
Not having the "button" or "link" traits on buttons and links means those who use our app using a screen reader, like VoiceOver in iOS or TalkBack in Android, won't know how to navigate without lots of trial & error. 

Imagine if all links and buttons in a web site looked like plain text. I, as a sighted user, wouldn't know what's clickable without hunting and pecking based on words that sound actionable. We'd be asking screen reader users to take the same leap.

**Comment by advayDev1** [comment]
@britannio can you verify this is working on iOS and Anndroid?

**Comment by britannio** [comment]
> @britannio can you verify this is working on iOS and Anndroid?

@advayDev1 I can take a look at the behavior on Android, it might be best to split this up into pages considering the size and variety of the app.

**Comment by hspinks** [comment]
Pending another full accessibility review, the app appears to be annotated correctly. Closing this issue for now, we will open specific issues for any specific instances of a widget tree not being annotated
