### ISSUE TITLE
Enable landscape orientation for app for accessibility

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#925]
Accessibility audit via @avkvirtru:

> "The orientation of the user interface and content MUST not be locked to either landscape or portrait unless a specific orientation is essential for the functionality of the app." - WAI-WCAG 2.1

---
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
I can use the app in landscape on iPad pro 11in.

Where do you not see landscape enabled? @avkvirtru

**Comment by avkvirtru** [comment]
This was from the accessibility test over 2 weeks ago in `v0.3.0` in iOS Simulator on my Mac in iPhone 8 and iPhone X sizes. 

@advayDev1 is there a way for me to test in something like TestFlight, or is pulling down the latest release still the best way to test?

**Comment by advayDev1** [comment]
> This was from the accessibility test over 2 weeks ago in `v0.3.0` in iOS Simulator on my Mac in iPhone 8 and iPhone X sizes. 
> 
> 
> 
> @advayDev1 is there a way for me to test in something like TestFlight, or is pulling down the latest release still the best way to test? 

There is a private test flight I'll send it to you

**Comment by avkvirtru** [comment]
Ran `v0.7.1 (14)` in TestFlight on an iPhone 8. No landscape orientation support. Entire app is in portrait mode.

Same version in iPad (7th generation) has no restrictions on orientation.
