### ISSUE TITLE
Approved content for Diagnosis & Triage

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#93]
From the project proposal:

> The App will provide users an engaging, integrated, accurate, personalized and tailored (i.e. age, location,  language, culture, education level) related information on COVID-19 from trusted, validated sources

Initial launch goal is for the information to be static, not personalized and tailored, but we'll still need to know exactly what that content should be. There is a ton of content on the [WHO's Coronavirus site](https://www.who.int/emergencies/diseases/novel-coronavirus-2019), so it's hard to figure out what is most important. The sooner we can get definitive/authoritative content the better - even if it's just a little bit more structure around what information would be useful. Noting that this is a major need for initial launch

**Comment by SamMousa** [comment]
We could implement the WHO chatbot survey as an in-app survey (ie no chat, just single / multiple choice questions).

**Comment by hspinks** [comment]
Assuming this is approved for v0.1 as of #248 - will revisit for future releases
