### ISSUE TITLE
Add Hotline / Emergency line lists for each countries

### ISSUE THREAD

**Issue by robertwt7** [WorldHealthOrganization/app#930]
Here in Australia we have different hotline to call if you think you might have COVID symptoms. Surprisingly many people do not know and got confused when they call GP or overwhelmed hospital. Adding a new page for this might be helpful? 

I can help with this

**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by advayDev1** [comment]
Dupe to #562
