### ISSUE TITLE
Refactor Push Notification features into a utility class. 

### ISSUE THREAD

**Issue by cbgrey** [WorldHealthOrganization/app#931]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [X] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [X] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

The code that manages push notification settings should be factored out into a utility class. Currently, the logic is spread throughout multiple views and other classes.

**Comment by kassim** [comment]
can be done as part of https://github.com/WorldHealthOrganization/app/issues/936 probably

**Comment by hspinks** [comment]
It's all you, @kassim! thanks for volunteering 😄

**Comment by cbgrey** [comment]
Thanks @kassim !
