### ISSUE TITLE
If the user denies notifications in onboarding there should be a way to enable them later.

### ISSUE THREAD

**Issue by patniemeyer** [WorldHealthOrganization/app#936]
If the user denies notifications in onboarding there should be a way in our Settings page to re-enable them.   This can be pretty simple and just show the notifications page again.  However there is a complication on iOS where iOS will only prompt with the system dialog once and after that we may need to redirect the user to settings to enable them manually.  I"m not sure if Firebase gives us any help with this.

**Comment by kassim** [comment]
Firebase plugins won't tell us if it's enabled or give us a shortcut to the settings screen as far as I'm aware. But there are two plugins to both show whether it's enabled and to launch the settings screens.

check status https://github.com/Vanethos/flutter_notification_permissions
launch settings https://github.com/spencerccf/app_settings

I'm happy to implement this if desired.

**Comment by hspinks** [comment]
all you too, @kassim
