### ISSUE TITLE
Deployment: Google Cloud organization

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#94]
Need an entity to own the Google Cloud org and billing (and thus be the controller of data)

**Comment by crazybob** [comment]
@brunobowden Does the WHO already have a Google Cloud organization? I'll use my personal account in the mean time (you can move projects between orgs).

**Comment by vpaulino** [comment]
Where the costs/features/services in each public cloud provider evaluated to comparison? What was the driver for google cloud decision? Does google cloud has public datacenters globally? What are the tech stacks available to implement PaaS solutions? What are the pricing models that are going to be taken into considerations?

**Comment by crazybob** [comment]
Yes, they were, but this issue is focused on setting up our Google Cloud account, not the appropriate place to revisit our cloud provider decision. The answers to some of your questions can be easily found on Google, and we have a lot of work to do. 🙏

**Comment by hspinks** [comment]
Closing as this was completed by @crazybob
