### ISSUE TITLE
Putting server behind a CDN

### ISSUE THREAD

**Issue by epicfaace** [WorldHealthOrganization/app#947]
For endpoints such as`getCaseStats` (#946), it might be useful to put the app engine backend behind a CDN. This might save significant compute and make it faster for users to use compared to the caching solution in #946 (this could potentially also remove the need for a cron job to populate a cache as in #946, thus simplifying server-side logic)

Even if the data needs to be refreshed every five minutes and we thus have to invalidate content every five minutes, it's probably still worth it.

**Comment by advayDev1** [comment]
AppEngine provides a full CDN.  Furthermore getCaseStats is intended to provide user-specific stats depending on the user's location so cannot be cached at the CDN level.

Also, a (second) CDN would not remove the need for a cron job.  The intent of the cron job is to guarantee a maximum RPS to our downstream dependencies.  No matter how good or bad our caching is, we will never exceed the for example 0.003 RPS to WHO's data.

We've considered this in the past and believe it doesn't make sense.  cc @crazybob
