### ISSUE TITLE
Firebase implementation for iOS throws error: __FIRAPP_DEFAULT does not exist

### ISSUE THREAD

**Issue by stevan-milovanovic** [WorldHealthOrganization/app#948]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

When the application runs on the simulator, the following logs are displayed:

Configuring the default Firebase app...
6.21.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
Configured the default Firebase app __FIRAPP_DEFAULT.

**Comment by advayDev1** [comment]
What is the impact of this?  Why does this matter?
