### ISSUE TITLE
App store submission content

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#96]
Noting that we will need assets for submission to the Apple App Store and Google Play Store.

Apple App Store needs: https://developer.apple.com/app-store/product-page/
Google Play Store needs: https://support.google.com/googleplay/android-developer/answer/113469?hl=en (see "Set Up Your Store Listing")

**Comment by epicfaace** [comment]
I've split this into text assets (#188) and graphical assets (#187) needed for submission to both app stores.

**Comment by hspinks** [comment]
thank you @epicfaace! super helpful to pull all of those into one place. I'll close this issue now in favor of the 2 you've created
