### ISSUE TITLE
Deployment: WHO Asset Clearance

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#97]
Proposed language: "The WHO visual identity assets in identity/, including but not limited to the WHO Logo and Emblem, are not licensed under the MIT License and are instead subject to the policies at https://www.who.int/about/who-we-are/publishing-policies/copyright and https://www.who.int/about/who-we-are/publishing-policies/logo ." 

> Ursula Zhao  6 minutes ago
Advay Mengle, advayDev1, PST thank you, will need to check with publishing on this. but if this is a bottleneck and could be modified later, then yes this is sufficient.

Ship blocker: Ursula to get final approval on language.

**Comment by advayDev1** [comment]
Sign-off from WHO for WHO assets.

**Comment by borowiecth** [comment]
On-going action, I hope to close it soon. Otherwise Kev will handle this.

**Comment by brunobowden** [comment]
WHO approved
