### ISSUE TITLE
New Get the Facts illustrations

### ISSUE THREAD

**Issue by brunobowden** [WorldHealthOrganization/app#971]
Image / icon assets that may need updating:
1. Garlic should have picture of garlic (currently looks like meat tenderizer)
1. Hand dryer currently shows a hair dryer
1. Alcohol Sprayer currently looks like a fumigation sprayer

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by davidkaneda** [comment]
How are these? (Keep in mind I'm not an illustrator, literally just slicing/dicing other icons 😅)

<img width="677" alt="image" src="https://user-images.githubusercontent.com/21713/78935234-381c0c00-7a61-11ea-99e1-d3d7fc89cd00.png">

[fact-illos-2.zip](https://github.com/WorldHealthOrganization/app/files/4458346/fact-illos-2.zip)

Also, I realized the original images were just named with icon frames, so I've renamed them here, sorry for any annoyance this causes swapping things out, but figure it's better to be named by content.

**Comment by asianfoodlab** [comment]
@davidkaneda thanks for the quick turnaround :-)!  Hand dryer and spray looks good.  The garlic is a bit mysterious :-).  Can we add some lines for bulbs and roots?  See attached for inspiration from a coloring book!

![image](https://user-images.githubusercontent.com/15184887/78944710-5985f380-7a73-11ea-9568-6a63f269c034.png)
