### ISSUE TITLE
Include "gzip" and app version in User-Agent for all HTTP requests from client

### ISSUE THREAD

**Issue by crazybob** [WorldHealthOrganization/app#976]
The "User-Agent" header is currently set to "Dart/2.7 (dart:io)".

Set it on all HTTP requests to: `User-Agent: WHO-App/[VERSION] (gzip)`

Including "gzip" in the User-Agent tells Google's frontend that it can gzip responses.

Examples:

- RPCs
- YAML content updates
- Others?

**Comment by advayDev1** [comment]
Will be like `WHO-App/ANDROID/0.1.1/2 (gzip)`

The platform is in there because WHO-Platform is not send up for content bundles.  The last 2 parts are the version and build numbers.

**Comment by advayDev1** [comment]
@crazybob do we /also/ need to send the standard `Accept-Encoding: gzip` for Goog?
