### ISSUE TITLE
If Location is disabled on Android, extra step is required to enable location sharing

### ISSUE THREAD

**Issue by britannio** [WorldHealthOrganization/app#985]
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

### Current flow when location is disabled and permission hasn't been granted:
Tap **Allow Location Sharing** button > Grant location permission > Enable location > _Tap **Allow Location Sharing** button_ > Location is fetched and the page is dismissed 

### Expected flow:
 Tap **Allow Location Sharing** button > Grant location permission > Enable location > Location is fetched and the page is dismissed

This isn't our fault, the location package has a `Location().requestService()` Future that erroneously isn't completing when it's first awaited(Issue https://github.com/Lyokone/flutterlocation/issues/342)

Related to https://github.com/WorldHealthOrganization/app/issues/915

**Comment by britannio** [comment]
Whoever fixes it might also want to create a final variable `final Location _location = Location()` and use that instead of using `Location().function` everywhere

**Comment by advayDev1** [comment]
is this repro-ing from HEAD?

Does it only happen on Android or on iOS too?

**Comment by advayDev1** [comment]
No more location permissions in v1
