### ISSUE TITLE
Update ROADMAP, README, and ONBOARDING docs to updated plan

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#987]
Make sure that these reflect our most updated thinking

---
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by purpledrosophila** [comment]
Is there any way I can help with this? I would be happy to, if so.
