### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/app#99]
If you need permissions for this repo post here with the access that you need.

**Comment by chrishosmer** [comment]
I need read write and triage

**Comment by SamMousa** [comment]
@chrishosmer I have given you triage permission.

**Comment by myiremark** [comment]
I need triage.

**Comment by ltphan** [comment]
Hi! I was wondering if I could be sent access to the Slack group :) Would love to help out!

**Comment by advayDev1** [comment]
FYI the GitHub permissions are as follows (essentially):
Triage - issue management including taking issues for yourself
Write - code review approvers (i.e. people with commit authority)

**Comment by ltphan** [comment]
Hi @SamMousa Sorry, do you mind sending it to my personal email account? My bad 🤦‍♀️ phanthuclinh@gmail.com

**Comment by sjwalter** [comment]
Requesting Triage permissions.

**Comment by epicfaace** [comment]
Could you give me triage permissions?

**Comment by brunobowden** [comment]
@epicfaace sent Triage invite
@sjwalter already has pending Triage (presumably from @SamMousa)

Welcome to you both, along with @ltphan

**Comment by SamMousa** [comment]
I have been using the rocket emoji for people I've added.

**Comment by sstur** [comment]
Hey team! Could you add me to triage and write access for PR review?

**Comment by ivancastrogw1** [comment]
Hi everyone I just joined can I have triage access?

**Comment by RohanTalip** [comment]
Could I get triage and write permisions?  I'll likely just review and approve small pull requests at this point.

**Comment by epicfaace** [comment]
FYI, anyone can review / approve PRs without any extra access permissions. Triage access allows you to label / close / assign issues and assign PRs. Write access allows you to merge PRs.

**Comment by sstur** [comment]
Right! I'm looking to triage (label, assign tasks and PRs) and to help out merging PRs after approval if possible. Triage access is more important because at this point I can't even self-assign a task to claim that I'm working on it.

**Comment by navikalingoth** [comment]
Hi everyone I just joined can I have triage access?

**Comment by polenoso** [comment]
Hi all!

**Comment by SamMousa** [comment]
Hi everyone, at this point we're no longer assigning everyone triage permissions (onboarding docs will be updated soon).

If you want to be assigned an issue to work on please add a comment to the issue and one of us will assign it to you.

Welcome to the project and thanks in advance for all your future contributions!

**Comment by vibraniumSwaleh** [comment]
Hi all!
Just joined. Triage access?

**Comment by nelsonmfinda** [comment]
Hi @SamMousa I want to join Slack community, the link in description are unavailable.

**Comment by SamMousa** [comment]
https://join.slack.com/t/who-app/shared_invite/zt-cx6ycppt-ccqPJ7ZSGy3~77gSByexJw

**Comment by a-oboh** [comment]
Requesting permission for triage

**Comment by marciowelben** [comment]
Requesting triage permissions

**Comment by HackrHIVE** [comment]
Hi everyone I just joined can I have triage access?

**Comment by SamMousa** [comment]
Please check the first post guys.
