### ISSUE TITLE
New assets for Notifications and Location screens

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#998]
Please let us know if the new assets are not MIT License, and if not, which license.

**Comment by davidkaneda** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/21713/79083008-285e2b00-7ce0-11ea-8aa1-3e853c8ad49f.png">

Here's a quick first stab—nothing amazing, but I think a small improvement.

[onboarding-illos.zip](https://github.com/WorldHealthOrganization/app/files/4467421/onboarding-illos.zip)

**Comment by advayDev1** [comment]
Thanks David!  These are OC under MIT License?

**Comment by davidkaneda** [comment]
They aren't, same as the others in Get the Facts

**Comment by davidkaneda** [comment]
These are now unDraw, not sure if they've been added already-
